feat(plasma-new-hope): Add Select component #956
salute-developers/plasma pull request #1032
Opened 2024-02-05 16:06 UTC by neretin-trike

### Combobox

Добавлен новый компонент

### What/why changed

Добавлен новый компонент

2024-02-05 16:28 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1032/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1032/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1032/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1032/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1032/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1032/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1032/caldera-online-storybook/
sdds-srvc storybook: http://plasma.sberdevices.ru/pr/pr-1032/sdds-srvc-storybook/

2024-02-06 12:13 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Combobox/Combobox.styles.ts
> +    inset: 0;
Предлагаю вынести на обсуждение введения следующего declaration ордера для написания стилей: https://codeguide.co/#declaration-order

Сейчас в компонентах стили разбросаны, надо тратить время на понимание, св-во position куда более важное чем opacity, следовательно должно стоят вначале.

2024-02-06 12:17 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Combobox/Combobox.tsx
> +            const uniqId = safeUseId();
Могу ошибаться, но по-моему логика в утилите useUniqId из plasma/core сейчас депрекейтед. 
Сможем заюзать useId из реакта напрямую?

2024-02-06 12:19 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Combobox/Combobox.tsx
> +            const [search, setSearch] = useState<string | undefined>('');
Оно может быть undefined?

2024-02-06 12:27 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Combobox/Combobox.tsx
> +            const [, forceRender] = useState(0);
Лучше вынести это в кастомный хук примерно такого содержания:
```
const [, updateState] = useState();
const forceUpdate = useCallback(() => updateState({}), []);
return forceUpdate
```

2024-02-06 12:29 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Combobox/Combobox.tsx
> +                [disabled, readOnly, search],
Разве не надо прокинуть onToggle в deps?

2024-02-06 12:34 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Combobox/Combobox.tsx
А есть ли смысл применять мемоизацию для данного компонента?

2024-02-06 12:35 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Combobox/Combobox.tsx
> +                        value={`${value}`}
Можно же просто value передать, ну или на крайний случай value.toString()

2024-02-06 12:37 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Combobox/hooks/useFocusController.ts
> +        }
```
if (isOpen) {

} else {

}
```

2024-02-06 12:41 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Combobox/ui/ComboboxTarget/ComboboxTarget.tsx
> +        const hasValue = Boolean(values?.some(([value]) => value));
Boolean не нужен

2024-02-07 07:26 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1032/

2024-02-07 07:40 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1032/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1032/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1032/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1032/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1032/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1032/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1032/caldera-online-storybook/
sdds-srvc storybook: http://plasma.sberdevices.ru/pr/pr-1032/sdds-srvc-storybook/

2024-02-07 13:27 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1032/

2024-02-07 13:38 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1032/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1032/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1032/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1032/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1032/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1032/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1032/caldera-online-storybook/
sdds-srvc storybook: http://plasma.sberdevices.ru/pr/pr-1032/sdds-srvc-storybook/

2024-02-07 15:16 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1032/

2024-02-07 15:29 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1032/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1032/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1032/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1032/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1032/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1032/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1032/caldera-online-storybook/
sdds-srvc storybook: http://plasma.sberdevices.ru/pr/pr-1032/sdds-srvc-storybook/

2024-02-08 13:59 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1032/

2024-02-08 14:12 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1032/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1032/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1032/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1032/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1032/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1032/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1032/caldera-online-storybook/
sdds-srvc storybook: http://plasma.sberdevices.ru/pr/pr-1032/sdds-srvc-storybook/

2024-02-12 07:33 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Combobox/ui/ComboboxTarget/ComboboxTarget.tsx
> +        const withHasChips = hasValue && enumerationType === 'chip' ? hasChips : undefined;
я поправил как смог

2024-02-12 07:33 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1032/

2024-02-12 07:45 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1032/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1032/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1032/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1032/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1032/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1032/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1032/caldera-online-storybook/
sdds-srvc storybook: http://plasma.sberdevices.ru/pr/pr-1032/sdds-srvc-storybook/

2024-02-12 08:03 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Combobox/Combobox.tsx
> +                [disabled, readOnly, search],
прокинул 👌

2024-02-12 08:04 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Combobox/hooks/useFocusController.ts
> +        }
тут уже поменялась логика, поэтому обычным else уже не обойдёшься. Но вообще я стараюсь максимально избегать этого, чтобы не было лишних вложенностей

2024-02-12 08:05 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Combobox/Combobox.tsx
> +                        value={`${value}`}
не, просто value не получится, он ругается на типы, т.к. нативный селект другие ожидает. А по поводу toString(), если я не ошибаюсь, у нас в проекте чаще используется имено `${}` такой подход. По перфу вроде особо разницы нет

2024-02-12 08:06 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Combobox/Combobox.tsx
мне кажется не особо, слишком много динамических пропсов

2024-02-12 08:07 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Combobox/Combobox.tsx
> +            const uniqId = safeUseId();
не совсем deprecate. Просто в методе `safeUseId` возвращается либо свой хук, либо реактовский. Эта обёртка нужна для тех, кто не использует 18 версию

2024-02-12 08:24 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Combobox/Combobox.tsx
> +                    rest.onChangeValue?.(newSelected);
Может сократить код
```
const newSelected = getNewSelected(rest.value, newValue, rest.valueType);
rest.onChangeValue?.(newSelected);

if(rest.valueType === 'multiple') {
   return;
 }
```

2024-02-12 08:43 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Combobox/Combobox.tsx
> +                        value={`${value}`}
toString по мне так понятней, чем эта конструкция

2024-02-12 08:51 UTC, shuga2704 commented on packages/plasma-b2c/src/components/Combobox/Combobox.stories.tsx
> +    const [value, setValue] = useState<ComboboxPrimitiveValue | undefined>('item_0');
Тут точно нужен undefined?

2024-02-12 09:39 UTC, shuga2704 requested changes

2024-02-12 09:39 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Combobox/Combobox.tsx
> +                        offset={[0, 4]}
Может вынесем наверх в `const OFFSET = [0, 4]`

2024-02-12 09:39 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Combobox/ui/ComboboxChip/ComboboxChip.tsx
> +        );
Здесь не нужны useCallback, их можно убрать.

2024-02-12 09:39 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Combobox/ui/ComboboxTarget/ComboboxTarget.tsx
> +                if (code === Keys.Tab || (code === Keys.Tab && shiftKey)) {
`if (code === Keys.Tab) {`

2024-02-12 09:39 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Combobox/ui/ComboboxTarget/ComboboxTarget.tsx
> +                if (opened && (code === Keys.Tab || (code === Keys.Tab && shiftKey))) {
`if (opened && code === Keys.Tab) {`

2024-02-12 09:39 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Combobox/ui/ComboboxTarget/ComboboxTarget.tsx
> +                    const newValue = values?.map(([itemValue]) => itemValue);
Я же правильно понимаю, что это двухмерный массив, из которого надо достать только первые значения?

2024-02-12 09:39 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Select/Select.tsx
> +                        offset={[0, 4]}
Тоже можно вынести как константу на самый верх.

2024-02-12 09:39 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Select/hooks/useKeyNavigation.ts
> +                ].includes(code)
На твое усмотрение, но я бы вынес это в отдельную утилиту `notIncludes`

2024-02-12 10:11 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1032/

2024-02-12 10:25 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1032/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1032/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1032/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1032/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1032/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1032/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1032/caldera-online-storybook/
sdds-srvc storybook: http://plasma.sberdevices.ru/pr/pr-1032/sdds-srvc-storybook/

2024-02-12 10:35 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Combobox/Combobox.tsx
> +                async (openValue: boolean, event: React.SyntheticEvent | Event) => {
oops, забыл удалить, спасиб

2024-02-12 13:17 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Combobox/Combobox.tsx
> +            const [search, setSearch] = useState<string | undefined>('');
ага, в кейсе, когда `textContent` возвращает undefined

2024-02-12 14:29 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Combobox/Combobox.tsx
обсудили этот вопрос и пришли к выводу, что можно отовсюду мемоизацию выпилить

2024-02-12 14:32 UTC, neretin-trike commented on packages/plasma-b2c/src/components/Combobox/Combobox.stories.tsx
> +    const [value, setValue] = useState<ComboboxPrimitiveValue | undefined>('item_0');
ага, т.к. можно "обнулить" значение, когда выбираешь вариант `Clear`

2024-02-12 14:34 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Combobox/Combobox.tsx
> +                    rest.onChangeValue?.(newSelected);
к сожалению так не получится сделать :( Т.к. ts не понимает, какой тип ему ожидать в rest.value без type-guard'ов

<img width="580" alt="image" src="https://github.com/salute-developers/plasma/assets/26903236/0e696b3b-d117-4fbe-8190-2da99ebf9ea2">

2024-02-12 14:36 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Combobox/ui/ComboboxTarget/ComboboxTarget.tsx
> +                    const newValue = values?.map(([itemValue]) => itemValue);
ага, всё так

2024-02-12 14:44 UTC, TitanKuzmich approved these changes

2024-02-12 14:50 UTC, Yeti-or reviewed
давай из шапки pr уберем кучу всего про клавиатурнную навигацию, ну то есть хорошо что это описанно и это поможет тестированию, но в changelog лучшечтобы попало пару скриншотов самого Combobox а не портянку текста про сочетания клаввиш.

2024-02-12 15:26 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Combobox/Combobox.tsx
отовсюду не получилось, т.к. поведение изменяется (выпадающий список "бликует" при открытии), если полностью убрать её из Combobox.tsx

2024-02-12 15:35 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Select/hooks/useKeyNavigation.ts
> +                ].includes(code)
не увидел особого профита выноса это в отдельную утилиту, но в отдельную переменную для лучшего восприятия вынес 👌

2024-02-12 16:14 UTC, Irinkv approved these changes

2024-02-12 16:17 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1032/

2024-02-12 16:31 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1032/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1032/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1032/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1032/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1032/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1032/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1032/caldera-online-storybook/
sdds-srvc storybook: http://plasma.sberdevices.ru/pr/pr-1032/sdds-srvc-storybook/

2024-02-13 09:50 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/Combobox/Combobox.types.ts
> +          onChangeValue?: (value?: ComboboxPrimitiveValue) => void;
почему он просто не onChange ?

2024-02-13 09:50 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/Combobox/hooks/useFocusController.ts
> +            inputRef.current.style.flex = '1';
а почему нужно менять flex ?

2024-02-13 09:50 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/Combobox/ui/ComboboxTarget/ComboboxTarget.tsx
> +import { Keys } from '../../../Select/hooks/useKeyNavigation';
видимо мы в какой-то момент придем к тому чтобы вынести это в хук ?

2024-02-13 09:50 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/Combobox/ui/ComboboxTarget/ComboboxTarget.tsx
> +import { Keys } from '../../../Select/hooks/useKeyNavigation';
имею ввиду в общий хук

2024-02-13 09:50 UTC, Yeti-or commented on website/plasma-web-docs/docs/components/Combobox.mdx
> +```
функция фильтрации не хочешь в примере описать ?

2024-02-13 11:24 UTC, neretin-trike commented on packages/plasma-b2c/src/components/Combobox/Combobox.stories.tsx
> +                    <ComboboxItem
ты предлагаешь прям завести этот отдельный комопнент в ядре, или добавить только в сторю?

2024-02-13 11:25 UTC, neretin-trike commented on packages/plasma-b2c/src/components/Combobox/Combobox.stories.tsx
> +    const filterFunction = () => true;
что он не фильтровал значения в этом кейсе, когда их надо просто добавлять

2024-02-13 11:27 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Combobox/Combobox.types.ts
> +          onChangeValue?: (value?: ComboboxPrimitiveValue) => void;
я пытался ещё в селекте просто onChange сделать, но ts сходил сума и не мог нормально зарезолвить Omit'ы

2024-02-13 11:28 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Combobox/hooks/useFocusController.ts
> +            inputRef.current.style.flex = '1';
нашёл единственный работающий способ, который смог воспроизвести ожидаемое по дизайну поведение

2024-02-13 11:28 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Combobox/ui/ComboboxTarget/ComboboxTarget.tsx
> +import { Keys } from '../../../Select/hooks/useKeyNavigation';
да, тоже на это поглядывал, но там нужно будет как-то по-умному это делать, чтобы не тащить логику того же календаря в селект / комбобокс

2024-02-13 11:29 UTC, neretin-trike commented on website/plasma-web-docs/docs/components/Combobox.mdx
> +```
да, хотел как раз следующей правкой добавить

2024-02-13 11:36 UTC, neretin-trike commented on packages/plasma-b2c/src/components/Combobox/Combobox.stories.tsx
> +import { Combobox, ComboboxItem } from './Combobox';
кроме Divider, на него есть, могу добавить

2024-02-13 11:45 UTC, neretin-trike commented on packages/plasma-b2c/src/components/Combobox/Combobox.stories.tsx
> +                    <ComboboxItem
просто если в ядре, то придётся ещё и добавлять ComboboxItemWithIconDone, либо в каждый item пользователю придётся явно прокидывать, single или multiple режим у Combobox'а выбран

2024-02-13 11:52 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1032/

2024-02-13 12:08 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1032/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1032/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1032/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1032/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1032/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1032/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1032/caldera-online-storybook/
sdds-srvc storybook: http://plasma.sberdevices.ru/pr/pr-1032/sdds-srvc-storybook/

2024-02-13 13:34 UTC, shuga2704 approved these changes

2024-02-13 15:13 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1032/

2024-02-13 20:43 UTC, Yeti-or approved these changes

2024-02-13 20:43 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/Select/hooks/useKeyNavigation.ts
> +            if (code === Keys.Enter || (code === Keys.Space && componentType !== 'combobox')) {
ну такое конечно видеть это в select/hooks
лучше бы componentType === 'select'
хотя так я надеюсь мы это заметим и разорвем эту неявную связь между компонентами

2024-02-13 20:43 UTC, Yeti-or commented on packages/plasma-new-hope/src/hooks/useForceUpdate.ts
> +    const forceUpdate = useCallback(() => updateState({}), []);
а зачем тут useCallback ?

2024-02-13 20:47 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1032/

2024-02-13 21:00 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1032/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1032/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1032/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1032/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1032/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1032/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1032/caldera-online-storybook/
sdds-srvc storybook: http://plasma.sberdevices.ru/pr/pr-1032/sdds-srvc-storybook/

2024-02-13 21:26 UTC, shuga2704 commented on packages/plasma-new-hope/src/hooks/useForceUpdate.ts
> +    const forceUpdate = useCallback(() => updateState({}), []);
Мы сохранили аутентичность от [оригинального](https://www.npmjs.com/package/use-force-update) пакета) Но вообще это юзлесс

2024-02-14 05:40 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Select/hooks/useKeyNavigation.ts
> +            if (code === Keys.Enter || (code === Keys.Space && componentType !== 'combobox')) {
вообще согласен, и изначально хотел на select сравнивать. Но потом подумал, что появится автокомплит, который будет скорее всего этот хук переиспользовать, или тот же дропдаун, и тогда придётся перечислять в ифе все эти типы, кроме комбобокса

2024-02-14 05:41 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Combobox/Combobox.tsx
починили это поведение, поэтому убрали мемоизацию из оставшихся мест

2024-02-14 07:06 UTC, merged

2024-02-14 07:23 UTC, Salute-Eva commented
<!-- GITHUB_RELEASE COMMENT: released -->
🚀 This PR is included in version: @salutejs/caldera-online@0.8.0-dev.0, @salutejs/caldera@0.8.0-dev.0, @salutejs/plasma-asdk@0.43.0-dev.0, @salutejs/plasma-b2c@1.285.0-dev.0, @salutejs/plasma-core@1.149.0-dev.0, @salutejs/plasma-cy-utils@0.81.0-dev.0, @salutejs/plasma-hope@1.263.0-dev.0, @salutejs/plasma-icons@1.182.0-dev.0, @salutejs/plasma-new-hope@0.49.0-dev.0, @salutejs/plasma-sb-utils@0.147.0-dev.0, @salutejs/plasma-temple-docs@0.223.0-dev.0, @salutejs/plasma-temple@1.201.0-dev.0, @salutejs/plasma-ui-docs@0.272.0-dev.0, @salutejs/plasma-ui@1.233.0-dev.0, @salutejs/plasma-web-docs@0.239.0-dev.0, @salutejs/plasma-web@1.285.0-dev.0, @salutejs/plasma-website@0.247.0-dev.0, @salutejs/sdds-srvc@0.9.0-dev.0 🚀

2024-02-14 07:23 UTC, Salute-Eva commented
<!-- GITHUB_RELEASE COMMENT: released -->
🚀 This PR is included in version: @salutejs/caldera-online@0.8.0-dev.0, @salutejs/caldera@0.8.0-dev.0, @salutejs/plasma-asdk@0.43.0-dev.0, @salutejs/plasma-b2c@1.285.0-dev.0, @salutejs/plasma-core@1.149.0-dev.0, @salutejs/plasma-cy-utils@0.81.0-dev.0, @salutejs/plasma-hope@1.263.0-dev.0, @salutejs/plasma-icons@1.182.0-dev.0, @salutejs/plasma-new-hope@0.49.0-dev.0, @salutejs/plasma-sb-utils@0.147.0-dev.0, @salutejs/plasma-temple-docs@0.223.0-dev.0, @salutejs/plasma-temple@1.201.0-dev.0, @salutejs/plasma-ui-docs@0.272.0-dev.0, @salutejs/plasma-ui@1.233.0-dev.0, @salutejs/plasma-web-docs@0.239.0-dev.0, @salutejs/plasma-web@1.285.0-dev.0, @salutejs/plasma-website@0.247.0-dev.0, @salutejs/sdds-srvc@0.9.0-dev.0 🚀

2024-02-14 07:23 UTC, Salute-Eva commented
<!-- GITHUB_RELEASE COMMENT: released -->
🚀 This PR is included in version: @salutejs/caldera-online@0.8.0-dev.0, @salutejs/caldera@0.8.0-dev.0, @salutejs/plasma-asdk@0.43.0-dev.0, @salutejs/plasma-b2c@1.285.0-dev.0, @salutejs/plasma-core@1.149.0-dev.0, @salutejs/plasma-cy-utils@0.81.0-dev.0, @salutejs/plasma-hope@1.263.0-dev.0, @salutejs/plasma-icons@1.182.0-dev.0, @salutejs/plasma-new-hope@0.49.0-dev.0, @salutejs/plasma-sb-utils@0.147.0-dev.0, @salutejs/plasma-temple-docs@0.223.0-dev.0, @salutejs/plasma-temple@1.201.0-dev.0, @salutejs/plasma-ui-docs@0.272.0-dev.0, @salutejs/plasma-ui@1.233.0-dev.0, @salutejs/plasma-web-docs@0.239.0-dev.0, @salutejs/plasma-web@1.285.0-dev.0, @salutejs/plasma-website@0.247.0-dev.0, @salutejs/sdds-srvc@0.9.0-dev.0 🚀

2024-02-14 07:24 UTC, Salute-Eva commented
<!-- GITHUB_RELEASE COMMENT: released -->
🚀 This PR is included in version: @salutejs/caldera-online@0.8.0-dev.0, @salutejs/caldera@0.8.0-dev.0, @salutejs/plasma-asdk@0.43.0-dev.0, @salutejs/plasma-b2c@1.285.0-dev.0, @salutejs/plasma-core@1.149.0-dev.0, @salutejs/plasma-cy-utils@0.81.0-dev.0, @salutejs/plasma-hope@1.263.0-dev.0, @salutejs/plasma-icons@1.182.0-dev.0, @salutejs/plasma-new-hope@0.49.0-dev.0, @salutejs/plasma-sb-utils@0.147.0-dev.0, @salutejs/plasma-temple-docs@0.223.0-dev.0, @salutejs/plasma-temple@1.201.0-dev.0, @salutejs/plasma-ui-docs@0.272.0-dev.0, @salutejs/plasma-ui@1.233.0-dev.0, @salutejs/plasma-web-docs@0.239.0-dev.0, @salutejs/plasma-web@1.285.0-dev.0, @salutejs/plasma-website@0.247.0-dev.0, @salutejs/sdds-srvc@0.9.0-dev.0 🚀

2024-02-14 07:24 UTC, Salute-Eva commented
<!-- GITHUB_RELEASE COMMENT: released -->
🚀 This PR is included in version: @salutejs/caldera-online@0.8.0-dev.0, @salutejs/caldera@0.8.0-dev.0, @salutejs/plasma-asdk@0.43.0-dev.0, @salutejs/plasma-b2c@1.285.0-dev.0, @salutejs/plasma-core@1.149.0-dev.0, @salutejs/plasma-cy-utils@0.81.0-dev.0, @salutejs/plasma-hope@1.263.0-dev.0, @salutejs/plasma-icons@1.182.0-dev.0, @salutejs/plasma-new-hope@0.49.0-dev.0, @salutejs/plasma-sb-utils@0.147.0-dev.0, @salutejs/plasma-temple-docs@0.223.0-dev.0, @salutejs/plasma-temple@1.201.0-dev.0, @salutejs/plasma-ui-docs@0.272.0-dev.0, @salutejs/plasma-ui@1.233.0-dev.0, @salutejs/plasma-web-docs@0.239.0-dev.0, @salutejs/plasma-web@1.285.0-dev.0, @salutejs/plasma-website@0.247.0-dev.0, @salutejs/sdds-srvc@0.9.0-dev.0 🚀

2024-02-14 07:24 UTC, Salute-Eva commented
<!-- GITHUB_RELEASE COMMENT: released -->
🚀 This PR is included in version: @salutejs/caldera-online@0.8.0-dev.0, @salutejs/caldera@0.8.0-dev.0, @salutejs/plasma-asdk@0.43.0-dev.0, @salutejs/plasma-b2c@1.285.0-dev.0, @salutejs/plasma-core@1.149.0-dev.0, @salutejs/plasma-cy-utils@0.81.0-dev.0, @salutejs/plasma-hope@1.263.0-dev.0, @salutejs/plasma-icons@1.182.0-dev.0, @salutejs/plasma-new-hope@0.49.0-dev.0, @salutejs/plasma-sb-utils@0.147.0-dev.0, @salutejs/plasma-temple-docs@0.223.0-dev.0, @salutejs/plasma-temple@1.201.0-dev.0, @salutejs/plasma-ui-docs@0.272.0-dev.0, @salutejs/plasma-ui@1.233.0-dev.0, @salutejs/plasma-web-docs@0.239.0-dev.0, @salutejs/plasma-web@1.285.0-dev.0, @salutejs/plasma-website@0.247.0-dev.0, @salutejs/sdds-srvc@0.9.0-dev.0 🚀

2024-02-14 07:24 UTC, Salute-Eva commented
<!-- GITHUB_RELEASE COMMENT: released -->
🚀 This PR is included in version: @salutejs/caldera-online@0.8.0-dev.0, @salutejs/caldera@0.8.0-dev.0, @salutejs/plasma-asdk@0.43.0-dev.0, @salutejs/plasma-b2c@1.285.0-dev.0, @salutejs/plasma-core@1.149.0-dev.0, @salutejs/plasma-cy-utils@0.81.0-dev.0, @salutejs/plasma-hope@1.263.0-dev.0, @salutejs/plasma-icons@1.182.0-dev.0, @salutejs/plasma-new-hope@0.49.0-dev.0, @salutejs/plasma-sb-utils@0.147.0-dev.0, @salutejs/plasma-temple-docs@0.223.0-dev.0, @salutejs/plasma-temple@1.201.0-dev.0, @salutejs/plasma-ui-docs@0.272.0-dev.0, @salutejs/plasma-ui@1.233.0-dev.0, @salutejs/plasma-web-docs@0.239.0-dev.0, @salutejs/plasma-web@1.285.0-dev.0, @salutejs/plasma-website@0.247.0-dev.0, @salutejs/sdds-srvc@0.9.0-dev.0 🚀

2024-02-14 07:24 UTC, Salute-Eva commented
<!-- GITHUB_RELEASE COMMENT: released -->
🚀 This PR is included in version: @salutejs/caldera-online@0.8.0-dev.0, @salutejs/caldera@0.8.0-dev.0, @salutejs/plasma-asdk@0.43.0-dev.0, @salutejs/plasma-b2c@1.285.0-dev.0, @salutejs/plasma-core@1.149.0-dev.0, @salutejs/plasma-cy-utils@0.81.0-dev.0, @salutejs/plasma-hope@1.263.0-dev.0, @salutejs/plasma-icons@1.182.0-dev.0, @salutejs/plasma-new-hope@0.49.0-dev.0, @salutejs/plasma-sb-utils@0.147.0-dev.0, @salutejs/plasma-temple-docs@0.223.0-dev.0, @salutejs/plasma-temple@1.201.0-dev.0, @salutejs/plasma-ui-docs@0.272.0-dev.0, @salutejs/plasma-ui@1.233.0-dev.0, @salutejs/plasma-web-docs@0.239.0-dev.0, @salutejs/plasma-web@1.285.0-dev.0, @salutejs/plasma-website@0.247.0-dev.0, @salutejs/sdds-srvc@0.9.0-dev.0 🚀

2024-02-14 07:24 UTC, Salute-Eva commented
<!-- GITHUB_RELEASE COMMENT: released -->
🚀 This PR is included in version: @salutejs/caldera-online@0.8.0-dev.0, @salutejs/caldera@0.8.0-dev.0, @salutejs/plasma-asdk@0.43.0-dev.0, @salutejs/plasma-b2c@1.285.0-dev.0, @salutejs/plasma-core@1.149.0-dev.0, @salutejs/plasma-cy-utils@0.81.0-dev.0, @salutejs/plasma-hope@1.263.0-dev.0, @salutejs/plasma-icons@1.182.0-dev.0, @salutejs/plasma-new-hope@0.49.0-dev.0, @salutejs/plasma-sb-utils@0.147.0-dev.0, @salutejs/plasma-temple-docs@0.223.0-dev.0, @salutejs/plasma-temple@1.201.0-dev.0, @salutejs/plasma-ui-docs@0.272.0-dev.0, @salutejs/plasma-ui@1.233.0-dev.0, @salutejs/plasma-web-docs@0.239.0-dev.0, @salutejs/plasma-web@1.285.0-dev.0, @salutejs/plasma-website@0.247.0-dev.0, @salutejs/sdds-srvc@0.9.0-dev.0 🚀