feat(plasma-new-hope): add button group component
salute-developers/plasma pull request #1061
Opened 2024-02-20 09:45 UTC by TitanKuzmich

### ButtonGroup

- добавлен новый компонент ButtonGroup
- написаны тесты и документация для ButtonGroup
- переделана структура файлов для Spiner
- Button добавлен в поставку в b2c/web
- обновлена документация для Button
- обновлены тесты, зависящие от Button

### What/why changed

Добавлен новый компонент ButtonGroup. Button доработан и перенесен в web/b2c, так как без этого ButtonGroup не имел бы смысла.

2024-02-20 09:48 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1061/

2024-02-20 10:12 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1061/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1061/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1061/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1061/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1061/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1061/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1061/caldera-online-storybook/

2024-02-20 10:32 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1061/

2024-02-20 10:44 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1061/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1061/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1061/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1061/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1061/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1061/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1061/caldera-online-storybook/

2024-02-22 14:22 UTC, shuga2704 requested changes

2024-02-26 07:27 UTC, neretin-trike commented on packages/plasma-web/src/components/ButtonGroup/ButtonGroup.config.ts
> +                }
кажется, что лучше создать дополнительные переменные с модиификаторами, то есть `buttonGroupTokens.buttonSegmentRadius`, `buttonGroupTokens.buttonRadius` и `buttonGroupTokens.buttoniPilledRadius` и расставлять их уже внутри компонента с помощью динамического класса в зависимости от пропса. Ибо хочется по максимуму избежать логики внутри конфига, т.к. когда мы будем генерировать его автоматически для разных компонент

2024-02-26 08:33 UTC, TitanKuzmich commented on packages/plasma-web/src/components/ButtonGroup/ButtonGroup.config.ts
> +                }
Подумаю, как поправить это. Но сейчас в данном компоненте тройное пересечение: border-radius зависит от размера, формы и отступами между кнопками внутри группы

2024-02-26 17:54 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1061/

2024-02-26 18:07 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1061/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1061/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1061/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1061/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1061/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1061/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1061/caldera-online-storybook/

2024-02-26 20:12 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1061/

2024-02-26 20:25 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1061/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1061/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1061/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1061/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1061/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1061/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1061/caldera-online-storybook/

2024-02-27 06:40 UTC, luizasok approved these changes

2024-02-27 08:47 UTC, neretin-trike commented
mr размер потерялся в new-hope
<img width="891" alt="image" src="https://github.com/salute-developers/plasma/assets/26903236/53cc9aa8-70ab-4cae-b17d-25ce56b26797">

2024-02-27 09:11 UTC, neretin-trike commented on website/plasma-web-docs/docs/components/Button.mdx
> +            <Button text="Текст" contentLeft={<IconDownload  color="inherit" />} />
а почему теперь необходимо явно указывать значение в иконках?

2024-02-27 09:14 UTC, neretin-trike commented on packages/plasma-new-hope/src/mixins/applyBlur.ts
> +    large: '50px',
нужно в rem превратить

2024-02-27 09:16 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Button/Button.tsx
> +        const stretchingClass = classes[`${stretching}Stretching` as keyof typeof classes];
хитро 👌

2024-02-27 09:20 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Button/Button.tsx
> +        const stretchingClass = classes[`${stretching}Stretching` as keyof typeof classes];
но свойство `stretch` всё-равно нужно сохранить (сделать какой-нибудь фолбэк). Т.к. у тех, кто сейчас используют кнопку из palsma-web / plasma-b2c с этим включенным свойством, сломается обратная совместимость

2024-02-27 09:23 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Button/Button.types.ts
> +    blur?: Blur;
для этих свойств: `outline`, `shiftLeft`, `shiftRight` и `blur` так же нужно добавить фолбэк, чтобы у пользователей не ломалось. Не уверен насколько это критично для shfit* свойств, но кажется, что тоже надо

2024-02-27 09:27 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Button/variations/_stretching/base.ts
> +        width: unset;
а почему не `auto`?

2024-02-27 09:36 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Button/Button.types.ts
> +        AsProps,
наверное надо бы как-то пометить, что эти свойства (`as`, `forwradedAs`) работают только для styled-component

2024-02-27 09:46 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Toast/utils.ts
> +});
а это для чего понадобилось делать? В компоненте `CloseIconWrapper` переопределяется ширина кнопки. У этого стиля специфичности не хватает чтобы твой класс fixedStretching перебить?

2024-02-27 09:48 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Spinner/hooks/index.ts
> +        if (width && height) {
*минор*

если не сложно, заинверти пожалуйста

2024-02-27 09:58 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Button/Button.config.ts
> +            fixed: css``,
сюда же не обязательно это добавлять? Мне кажется достаточно того, что ты в типе самой кнопки это перечисление указал

2024-02-27 10:01 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/sds_engineer/components/Button/Button.config.ts
> +            default: css`
вроде в итоге договаривались, что используем не default, а primary там, где это возможно? Особенно если используются эти токены внутри. @Yeti-or Посмотри пожалуйста тоже

2024-02-27 10:04 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/sds_engineer/components/Button/Button.config.ts
> +            default: css`
да, пробежался по всем компонентам в new-hope. И нейминг `default` используется в основном в кейсах, где вообще нет других вьюх

2024-02-27 10:05 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/sds_engineer/components/ButtonGroup/ButtonGroup.config.ts
> +        },
здесь тоже shape и stretching не нужно указывать

2024-02-27 10:13 UTC, neretin-trike commented
добавь пожалуста ещё отдельным коммитом удаление Button'a из hope (если это сейчас возможно)

2024-02-27 10:26 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/examples/sds_engineer/components/Button/Button.config.ts
> +            default: css`
Там получается так, что и primary вьюха есть и default

2024-02-27 10:28 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Toast/utils.ts
> +});
По дефолту stretching="auto" и токен с шириной просто не попадает в стиль кнопки.
Хотя я сейчас понял, что это можно сделать через пропс, а не тут в конфиг прокидывать

2024-02-27 10:36 UTC, TitanKuzmich commented on website/plasma-web-docs/docs/components/Button.mdx
> +            <Button text="Текст" contentLeft={<IconDownload  color="inherit" />} />
По-моему так и раньше было. Там же color по-умолчанию не указан

2024-02-27 10:38 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/sds_engineer/components/Button/Button.config.ts
> +            default: css`
там немного смещенно всё. Default это primary, а primary это accent

2024-02-27 11:22 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Button/Button.config.ts
> +                ${buttonTokens.buttonSpinnerSize}: 22px;
Нет, все работает. Переведу в ремы

2024-02-27 15:31 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/examples/sds_engineer/components/ButtonGroup/ButtonGroup.config.ts
> +        },
Они нужны, иначе не навешиваются классы

2024-02-27 16:13 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1061/

2024-02-27 16:17 UTC, shuga2704 approved these changes

2024-02-27 16:17 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1061/

2024-02-28 05:42 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/sds_engineer/components/ButtonGroup/ButtonGroup.config.ts
> +        },
чот не понимаю, как это работает 🤔

2024-02-28 05:54 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/sds_engineer/components/ButtonGroup/ButtonGroup.config.ts
> +        },
https://github.com/salute-developers/plasma/issues/1073

2024-02-28 06:05 UTC, neretin-trike approved these changes

2024-02-28 06:20 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1061/

2024-02-28 06:32 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1061/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1061/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1061/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1061/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1061/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1061/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1061/caldera-online-storybook/

2024-02-28 06:58 UTC, merged