feat(new-hope): edit calendar range logic and fix name
salute-developers/plasma pull request #1084
Opened 2024-03-03 16:04 UTC by iljs

### Calendar

-   добавлено возможность выбрать 1 дня в типе range

### What/why changed

Возможность выбор 1 дня в типе range, убрал проверку на hoverDate со startDate. И изменил название функции, которая была написана неправильно

2024-03-03 16:07 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1084/

2024-03-03 16:26 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1084/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1084/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1084/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1084/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1084/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1084/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1084/caldera-online-storybook/
sdds-serv storybook: http://plasma.sberdevices.ru/pr/pr-1084/sdds-serv-storybook/

2024-03-04 08:40 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Calendar/hooks/useDays.ts
> +    isDayInRange,
👍

2024-03-04 08:42 UTC, TitanKuzmich approved these changes

2024-03-04 08:43 UTC, shuga2704 requested changes

2024-03-04 08:43 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Calendar/utils/index.ts
> +    return startValue && startValue < day && day <= endValue;
```suggestion
    return startValue < day && day <= endValue;
```

2024-03-06 07:46 UTC, shuga2704 requested changes

2024-03-06 07:55 UTC, shuga2704 approved these changes

2024-03-06 07:56 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1084/

2024-03-06 07:57 UTC, Yakutoc approved these changes

2024-03-06 08:12 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1084/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1084/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1084/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1084/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1084/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1084/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1084/caldera-online-storybook/
sdds-serv storybook: http://plasma.sberdevices.ru/pr/pr-1084/sdds-serv-storybook/

2024-03-06 08:23 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1084/

2024-03-06 08:37 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1084/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1084/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1084/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1084/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1084/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1084/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1084/caldera-online-storybook/
sdds-serv storybook: http://plasma.sberdevices.ru/pr/pr-1084/sdds-serv-storybook/

2024-03-06 10:14 UTC, merged