plasma-infra: Scaffold docs dir CLI
salute-developers/plasma pull request #1099
Opened 2024-03-06 09:30 UTC by Yakutoc

### Scaffold docs CLI

- добавлен CLI для создание директории документации по шаблону
- добавлен CLI для создание компонента документации по шаблону

### What/why changed

Автоматизация развертывания документации для новых пакетов/дизайн вертикалей

2024-03-06 09:31 UTC, Yakutoc commented on package.json
> +    "simple-scaffold": "2.2.0",
[Note]: 

Пакет для scaffold - https://chenasraf.github.io/simple-scaffold/

2024-03-06 09:32 UTC, Yakutoc commented on scaffold/template-component/{{name}}.mdx
> +id: {{name}}
[Note]: будет подставлено название компонента, например `Avatar`

2024-03-06 09:32 UTC, Yakutoc commented on scaffold/template-component/{{name}}.mdx
> +import { {{name}} } from '@salutejs/{{package}}';
[Note]: Название пакета, например `caldera`.

2024-03-06 09:33 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1099/

2024-03-06 09:36 UTC, Yakutoc commented on scaffold/template-docs/src/components/CodeSandbox.tsx
> +import { {{ theme }}__light } from "@salutejs/{{ vertical }}-themes";
[Note]: 

- `theme` - конкретное название темы, например `sdds_serv`
- `vertical` - дизайн вертикаль, например `plasma` или `sdds`

2024-03-06 09:37 UTC, Yakutoc commented on scaffold/template-docs/src/theme/Playground/index.tsx
> +import { {{ theme }}__dark, {{ theme }}__light } from '@salutejs/{{ vertical }}-themes';
[Note]: 

- `theme` - конкретное название темы, например `sdds_serv`
- `vertical` - дизайн вертикаль, например `plasma` или `sdds`

2024-03-06 09:43 UTC, Yakutoc commented on scaffold/template-docs/docusaurus.config.js
> +const baseUrl = VERSION_NAME ? `/versions/${VERSION_NAME}/` : `${prefix}/{{name}}/`;
[Вопрос] для `${prefix}/{{name}}/`

У нас есть пакет `plasma-asdk`, какой хвост для URL мы хотим? `/asdk` ?

Я к тому что всегда откидываем `plasma-` ?

2024-03-07 07:42 UTC, Yakutoc commented on scaffold/template-docs/docusaurus.config.js
> +const baseUrl = VERSION_NAME ? `/versions/${VERSION_NAME}/` : `${prefix}/{{name}}/`;
**[Обсуждение]**

У нас есть сценарий, когда мы заливаем документацию на `/dev` ресурс

предлагаю  заменить переменную `PR_NAME `  на `PREFIX` 

Возможные значения:

- `pr/${PR_NAME}` (pull request workflow)
- `dev`  (upload to `/dev`) 

Весь смысл в том что эту переменную определяет процесс в котором запустилась сборка документации.

2024-03-11 18:57 UTC, Yeti-or requested changes

2024-03-11 18:57 UTC, Yeti-or commented on scaffold/scaffold-components.js
> +        fs.readdir(packageDir, (err, files) => {
а может fs/proisses ? 
то как-то в перемешку async и колбеки
https://nodejs.org/docs/latest-v18.x/api/fs.html#promise-example

2024-03-11 18:57 UTC, Yeti-or commented on scaffold/template-docs/docs/_category_.json
> +    "label": "Plasma Web",
а это зачем в template?

2024-03-11 18:57 UTC, Yeti-or commented on scaffold/template-docs/docs/intro.mdx
> +
в интро не должно быть это либа такая то
токены такие-то
все дела?

2024-03-11 18:57 UTC, Yeti-or commented on scaffold/template-docs/docusaurus.config.js
> +// eslint-disable-next-line @typescript-eslint/no-var-requires,import/order
а мы не можем тут esm использовать ?

2024-03-11 18:57 UTC, Yeti-or commented on scaffold/template-docs/docusaurus.config.js
> +const baseUrl = VERSION_NAME ? `/versions/${VERSION_NAME}/` : `${prefix}/{{name}}/`;
на самом деле мы бы хотели 
`plasma.sdds.sberdevices.ru`
что-то такое пожалуй

2024-03-11 18:57 UTC, Yeti-or commented on scaffold/template-docs/docusaurus.config.js
> +    projectName: 'Plasma',
на что это влияет ?

2024-03-11 18:57 UTC, Yeti-or commented on scaffold/template-docs/docusaurus.config.js
> +            title: 'Plasma',
почему везде Plasma ?

2024-03-11 18:57 UTC, Yeti-or commented on scaffold/template-docs/docusaurus.config.js
> +                                '../../packages/plasma-hope/src/**/*.{ts,tsx}',
боюсь представить зачем это туту

2024-03-11 18:57 UTC, Yeti-or commented on scaffold/template-docs/src/css/custom.css
> +@import 'https://cdn-app.sberdevices.ru/shared-static/0.0.0/styles/SBSansText.0.2.0.css';
а sbs-display нам не нужно подключать ?

2024-03-11 18:57 UTC, Yeti-or commented on scaffold/update-docs-ui.js
> +        console.error(`The package: "${npmConfigPackage}" note exists`);
ну тут кажется должна быть какая-то другая ошибка

2024-03-11 18:57 UTC, Yeti-or commented on scaffold/update-package-json.js
> +        const packageJSON = require(`${packageDir}/package.json`);
А может попользоваться fs-extra ?
https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/readJson.md
https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/ensureDir.md

2024-03-11 18:57 UTC, Yeti-or commented on package.json
> +    "scaffold:update-docs-ui": "DIR=$(echo $npm_config_dir) && node scaffold/update-docs-ui.js && npm i --no-audit --no-progress --package-lock-only --lockfile-version 2 --legacy-peer-deps --prefix=$
а давай DШК передадим через аргументы и достанем из process.argv 
а не через переменную окружения

2024-03-11 18:57 UTC, Yeti-or commented on package.json
> +    "scaffold:bootstrap": "DIR=$(node -p \"require('./scaffold/update-package-json.js').dir\") && npm i --prefix=$DIR && npm run scaffold:update-docs-ui --dir=$DIR",
тут я тоже не понял почему мы вычисляем директорию где надо сделать npm i так хитро?
можно проще ?

2024-03-11 18:57 UTC, Yeti-or commented on scaffold/update-package-json.js
> +    dir: `website/${npmConfigPackage}-docs/`,
выглядит диковато,
мы передаем в этот файл npmConfigPackage и потому его же почти не меняя возвращаем как экспорт

2024-03-12 06:35 UTC, Yakutoc commented on scaffold/template-docs/docs/intro.mdx
> +
@Yeti-or Я тогда могу за шаблон взять пример из `sdds-serv` ?

2024-03-12 07:12 UTC, Yeti-or commented on scaffold/template-docs/docs/intro.mdx
> +
ну в целом мы можем это сделать отдельно, в sdds-serv нужно переписать на plasma-themes

2024-03-12 07:28 UTC, Yakutoc commented on scaffold/template-docs/docusaurus.config.js
> +    projectName: 'Plasma',
@Yeti-or 

> The name of the branch to deploy the static files to. 
> You don't need this if you are not using the `docusaurus deploy` command.

Звучит как нам не нужно.

2024-03-12 07:41 UTC, Yakutoc commented on scaffold/template-docs/docusaurus.config.js
> +            title: 'Plasma',
@Yeti-or Заменю на placeholder

2024-03-12 10:20 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1099/

2024-03-12 10:43 UTC, Yakutoc commented on scaffold/template-docs/docusaurus.config.js
> +const baseUrl = VERSION_NAME ? `/versions/${VERSION_NAME}/` : `${prefix}/{{name}}/`;
@Yeti-or Я это обсужу, возможен ли такой вариант.

2024-03-12 10:45 UTC, Yakutoc commented on package.json
> +    "scaffold:bootstrap": "node scaffold/update-package-json.js && npm run scaffold:install --dir=$(echo 'website/'$npm_config_package'-docs/')",
@Yeti-or 

> тут я тоже не понял почему мы вычисляем директорию где надо сделать npm i так хитро?
можно проще ?

Переписал, стало по проще читать.

2024-03-12 10:46 UTC, Yakutoc commented on scaffold/template-docs/docs/intro.mdx
> +
Давай тогда в задаче про генерацию содержимого для компонентов

2024-03-12 10:48 UTC, Yakutoc commented on scaffold/template-docs/src/css/custom.css
> +@import 'https://cdn-app.sberdevices.ru/shared-static/0.0.0/styles/SBSansText.0.2.0.css';
@Yeti-or А кто знает ответ на вопрос? ) 

Тут сделано по аналогии как `plasma-web-docs`.

2024-03-12 10:48 UTC, Yakutoc commented on scaffold/template-docs/static/images/plasma-logo.png
@Yeti-or Я так понимаю это logo нам не нужно?

2024-03-12 11:03 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1099/

2024-03-13 05:17 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1099/

2024-03-13 05:19 UTC, Yakutoc commented on scaffold/template-docs/docusaurus.config.js
> +const baseUrl = VERSION_NAME ? `/versions/${VERSION_NAME}/` : `${prefix}/{{name}}/`;
Пока предлагаю остановиться на варианте предложенном в этом пр.

2024-03-13 10:42 UTC, TitanKuzmich approved these changes

2024-03-13 11:13 UTC, Yakutoc commented on package.json
> +    "scaffold:update-docs-ui": "node scaffold/update-docs-ui.js && npm i --no-audit --no-progress --package-lock-only --lockfile-version 2 --legacy-peer-deps --prefix=$npm_config_dir",
@Yeti-or 

У нас так по всему проекту. Связано с тем что ряд зависимостей имеет разные версии и без этого флага ломалось.

2024-03-14 12:16 UTC, shuga2704 approved these changes

2024-03-17 09:55 UTC, neretin-trike commented on scaffold/Readme.md
> +Для развертывания нового пакета документации, например для пакета `"@salutejs/asdk"`, выполните команду в корне проекта:
Тут нужно поправить на @salutejs/plasma-asdk

2024-03-17 10:05 UTC, neretin-trike commented on scaffold/scaffold-components.js
> +const { readdir } = require('node:fs/promises');
*минор*

А просто readdirSync не подойдет?

2024-03-17 10:34 UTC, neretin-trike commented on scaffold/template-docs/docs/intro.mdx
> +
Вы имеете в виду доку? Потому что если вы про либу, то она уже использует sdds-themes пакет

2024-03-17 10:48 UTC, neretin-trike commented on scaffold/template-docs/src/css/custom.css
> +@import 'https://cdn-app.sberdevices.ru/shared-static/0.0.0/styles/SBSansText.0.2.0.css';
Вообще это зависит от подключаемой в итоге темы. Так что тут вообще любое значение в теории может быть.

На данном этапе нужно добавить еще sb display, и завести тудушку на подумать, как это сделать в будущем

2024-03-17 10:55 UTC, neretin-trike commented on scaffold/template-docs/src/theme/Playground/index.tsx
> +    const regexp = /import\s+?(?:(?:(?:[\w*\s{},]*)\s+from\s+?)|)(?:(?:".*?")|(?:'.*?'))[\s]*?(?:;|$|)/g;
А можешь плс в комментах указать, что тут происходит + пример

2024-03-17 10:56 UTC, neretin-trike commented on scaffold/template-docs/src/theme/Playground/index.tsx
> +const lightTheme = {{ theme }}__dark[':root'];
может тут тоже вместо этого createGlobalStyle как с типографикой?

2024-03-17 10:59 UTC, neretin-trike commented on scaffold/template-docs/sidebars.js
> +   */
Кажется, что этот пример можно удалить. Чтоб из доки в доку не повторялось

2024-03-18 04:46 UTC, Yakutoc commented on scaffold/scaffold-components.js
> +const { readdir } = require('node:fs/promises');
@neretin-trike А какие бенефиты?

2024-03-18 06:08 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1099/

2024-03-18 07:57 UTC, merged