Add Toolbar component
salute-developers/plasma pull request #1103
Opened 2024-03-07 13:06 UTC by eg-zhuravlev

### Toolbar

-   добавили компонент Toolbar

<img width="165" alt="Screenshot 2024-03-07 at 18 05 14" src="https://github.com/salute-developers/plasma/assets/38912157/bdf7480b-ed80-44c8-8079-2e0f612e0acf">

2024-03-12 06:47 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1103/

2024-03-13 13:39 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1103/

2024-03-13 13:54 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1103/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1103/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1103/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1103/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1103/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1103/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1103/caldera-online-storybook/
sdds-serv storybook: http://plasma.sberdevices.ru/pr/pr-1103/sdds-serv-storybook/

2024-03-14 14:31 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1103/

2024-03-14 14:48 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1103/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1103/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1103/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1103/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1103/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1103/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1103/caldera-online-storybook/
sdds-serv storybook: http://plasma.sberdevices.ru/pr/pr-1103/sdds-serv-storybook/

2024-03-15 08:11 UTC, luizasok approved these changes

2024-03-18 15:04 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Toolbar/ui/ToolbarDivider/ToolbarDivider.tsx
> +                <StyledToolbarDividerContainer>
Для чего StyledToolbarDividerContainer нужен? Можем его стили просто в Root положить?

2024-03-18 15:04 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Toolbar/Toolbar.tsx
> +export const toolbarRoot = (Root: RootProps<HTMLDivElement, ToolbarProps>) =>
Можем сделать переопределение токенов для кнопки (как в ButtonGroup), чтобы не нужно было на каждую кнопку в отдельности вешать пропсы по типу size

2024-03-19 09:56 UTC, eg-zhuravlev commented on packages/plasma-new-hope/src/components/Toolbar/Toolbar.types.ts
> +    size?: 'xs' | 's' | 'm' | 'l';
Я вот чет не понял зачем у вас этот view везде, даже в местах где у него значение только default может быть ?
Для примера компонент Tooltip

2024-03-19 10:01 UTC, eg-zhuravlev commented on packages/plasma-new-hope/src/components/Toolbar/Toolbar.tsx
> +export const toolbarRoot = (Root: RootProps<HTMLDivElement, ToolbarProps>) =>
Звучит не явно и + нет строго типа какой компонент можно в children тулбара прокинуть

2024-03-20 08:21 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Toolbar/Toolbar.types.ts
> +    size?: 'xs' | 's' | 'm' | 'l';
Для консистентности типов нужно добавить view?: string. Пропс такой будет, потому что в конфиге он указан. Еще поменяй пожалуйста в size тип на string

2024-03-20 08:21 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Toolbar/ui/ToolbarDivider/ToolbarDivider.types.ts
> +type ToolbarDividerCustomProps = {};
Тут так же будет проп view и в типе он нужен тогда

2024-03-20 08:21 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Toolbar/ui/ToolbarDivider/ToolbarDivider.tsx
> + * Элемент выпадающего списка
[опечатка]
Разделитель тулбара

2024-03-20 08:22 UTC, shuga2704 requested changes

2024-03-20 08:22 UTC, shuga2704 commented on packages/plasma-new-hope/src/.DS_Store
Нам точно нужен этот файл в репо?

2024-03-20 08:22 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Toolbar/Toolbar.styles.ts
> +export const StyledToolbar = styled.div<{ placement: 'vertical' | 'horizontal'; hasShadow: boolean }>`
Давай эти 2 пропса напрямую достанем из ToolbarProps, чтобы не дублировать типы.

2024-03-20 08:22 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Toolbar/Toolbar.styles.ts
> +    box-shadow: ${(props) => (props.hasShadow ? `var(${tokens.boxShadow})` : 'none')};
Сделай пожалуйста деструктуризацию

2024-03-20 08:22 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Toolbar/Toolbar.tsx
> +        const { children, placement = 'vertical', hasShadow = true, size = 'm', ...rest } = props;
Если в конфиге добавить size по дефолту, то тут его уже можно не указывать.

2024-03-20 08:22 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Toolbar/Toolbar.types.ts
> +    size?: 'xs' | 's' | 'm' | 'l';
Мы обычно во `view` и `size` (и тд.) здесь ставим тип string, движок сам проставит необходимые пропы.

2024-03-20 08:22 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Toolbar/Toolbar.types.ts
> +export type ToolbarProps = HTMLAttributes<HTMLDivElement> & PropsWithChildren<CustomToolbarProps>;
Не уверен, но по-моему `PropsWithChildren` делает children опциональным. Это валидный сценарий?

2024-03-20 08:22 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Toolbar/ui/ToolbarDivider/ToolbarDivider.tsx
> +            </Root>
Точно нужно 2 дива на разделитель?

2024-03-20 08:22 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Toolbar/ui/ToolbarDivider/ToolbarDivider.types.ts
> +type ToolbarDividerCustomProps = {};
Зачем нам пустой тип?

2024-03-20 08:22 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Toolbar/Toolbar.tsx
> +            </Root>
Не получилось сделать все через Root? Не очень пока вижу смысл дополнительного `StyledToolbar` внутри.

2024-03-20 10:48 UTC, eg-zhuravlev commented on packages/plasma-new-hope/src/components/Toolbar/ui/ToolbarDivider/ToolbarDivider.tsx
> +            </Root>
Чтобы по центру родителя его сделать, могу вытащить в псевдоэлемент

2024-03-20 11:23 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Toolbar/Toolbar.types.ts
> +export type ToolbarProps = HTMLAttributes<HTMLDivElement> & PropsWithChildren<CustomToolbarProps>;
Вроде как PropsWithChildren не нужен. children по дефолту будет доступен

2024-03-21 11:31 UTC, neretin-trike commented on packages/plasma-web/src/components/Toolbar/Toolbar.tsx
> +    component,
не используемая переменная (странно, что билд прошёл(

2024-03-21 11:32 UTC, neretin-trike commented on packages/plasma-b2c/src/components/Toolbar/Toolbar.tsx
> +    component,
не используемая переменная. Странно, что билд прошёл 🤔

2024-03-21 11:35 UTC, neretin-trike commented
добавь пожалуйста небольшую документацию по примеру с [Chip](https://github.com/salute-developers/plasma/blob/391e305417acd9b478d3be5811b4ae2676f202f1/website/plasma-web-docs/docs/components/Chip.mdx)

2024-03-21 11:42 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Toolbar/Toolbar.styles.ts
> +        height: 0.063rem;
а автоматически эту величину нельзя рассчитать?

2024-03-21 12:05 UTC, eg-zhuravlev commented on packages/plasma-web/src/components/Toolbar/Toolbar.tsx
> +    component,
используется

2024-03-21 12:05 UTC, eg-zhuravlev commented on packages/plasma-b2c/src/components/Toolbar/Toolbar.tsx
> +    component,
используется

2024-03-22 08:12 UTC, neretin-trike commented on packages/plasma-b2c/src/components/Toolbar/Toolbar.tsx
> +    component,
сорри, не по глазам было :(

2024-03-22 08:12 UTC, neretin-trike commented on packages/plasma-web/src/components/Toolbar/Toolbar.tsx
> +    component,
сорри, не по глазам было :(

2024-03-22 11:44 UTC, neretin-trike approved these changes

2024-03-25 10:37 UTC, TitanKuzmich approved these changes

2024-03-26 09:24 UTC, shuga2704 approved these changes

2024-03-27 07:59 UTC, IgorYar commented
Протестировал и багов не нашел.

2024-03-27 08:03 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Toolbar/Toolbar.types.ts
> +    placement?: 'vertical' | 'horizontal';
Можем placement переименовать в orientation?

2024-03-27 11:26 UTC, closed without merging

2024-03-27 11:26 UTC, TitanKuzmich commented
Функционал перенесен в https://github.com/salute-developers/plasma/pull/1150