feat(new-hope): Pagination
salute-developers/plasma pull request #1107
Opened 2024-03-12 08:01 UTC by iljs

### Pagination

Компонент пагинации

### What/why changed

Добавил параметр slots. Он позволяет определить сколько кнопок со страницами будет в компоненте и система сама распределит их по секциям 

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/caldera-online@0.26.0-canary.1107.8441154681.0
  npm install @salutejs/caldera@0.26.0-canary.1107.8441154681.0
  npm install @salutejs/plasma-asdk@0.63.0-canary.1107.8441154681.0
  npm install @salutejs/plasma-b2c@1.305.0-canary.1107.8441154681.0
  npm install @salutejs/plasma-new-hope@0.66.0-canary.1107.8441154681.0
  npm install @salutejs/plasma-web@1.305.0-canary.1107.8441154681.0
  npm install @salutejs/sdds-serv@0.30.0-canary.1107.8441154681.0
  # or 
  yarn add @salutejs/caldera-online@0.26.0-canary.1107.8441154681.0
  yarn add @salutejs/caldera@0.26.0-canary.1107.8441154681.0
  yarn add @salutejs/plasma-asdk@0.63.0-canary.1107.8441154681.0
  yarn add @salutejs/plasma-b2c@1.305.0-canary.1107.8441154681.0
  yarn add @salutejs/plasma-new-hope@0.66.0-canary.1107.8441154681.0
  yarn add @salutejs/plasma-web@1.305.0-canary.1107.8441154681.0
  yarn add @salutejs/sdds-serv@0.30.0-canary.1107.8441154681.0
  ```
</details>

2024-03-12 10:35 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1107/

2024-03-12 16:34 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1107/

2024-03-12 18:53 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1107/

2024-03-12 19:08 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1107/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1107/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1107/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1107/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1107/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1107/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1107/caldera-online-storybook/
sdds-serv storybook: http://plasma.sberdevices.ru/pr/pr-1107/sdds-serv-storybook/

2024-03-13 09:14 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1107/

2024-03-13 09:56 UTC, simashova approved these changes

2024-03-13 11:10 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1107/

2024-03-13 11:15 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1107/

2024-03-13 11:27 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1107/

2024-03-13 11:42 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1107/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1107/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1107/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1107/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1107/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1107/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1107/caldera-online-storybook/
sdds-serv storybook: http://plasma.sberdevices.ru/pr/pr-1107/sdds-serv-storybook/

2024-03-13 11:57 UTC, iljs commented on packages/plasma-b2c/scripts/copy-linaria-components.sh
> +        egrep "\<$component\>" src/index.ts >> src-css/index.ts
Вообще странно, ветки менял. Случайно попало, ща поправлю

2024-03-13 12:03 UTC, iljs commented on packages/plasma-b2c/scripts/copy-linaria-components.sh
> +        egrep "\<$component\>" src/index.ts >> src-css/index.ts
fixed

2024-03-13 12:04 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1107/

2024-03-13 12:09 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +                onChangeValue && onChangeValue(pageValue, perPageValue);
можно такую запись `onChangeValue?.(pageValue, perPageValue)` и убрать на проверку `onChangeValue &&`

2024-03-13 12:18 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1107/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1107/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1107/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1107/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1107/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1107/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1107/caldera-online-storybook/
sdds-serv storybook: http://plasma.sberdevices.ru/pr/pr-1107/sdds-serv-storybook/

2024-03-13 12:22 UTC, iljs commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +                if (pageValue > pages) pageValue = pages;
fixed

2024-03-13 12:23 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1107/

2024-03-13 12:55 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1107/

2024-03-13 13:10 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1107/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1107/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1107/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1107/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1107/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1107/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1107/caldera-online-storybook/
sdds-serv storybook: http://plasma.sberdevices.ru/pr/pr-1107/sdds-serv-storybook/

2024-03-14 11:06 UTC, iljs commented on packages/plasma-new-hope/src/components/Pagination/Pagination.types.ts
> +    slots?: NumericRange<CreateArrayWithLengthX<7>, 15>;
Ну перечислять цифры тоже как то не очень

2024-03-14 11:55 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1107/

2024-03-14 12:11 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1107/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1107/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1107/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1107/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1107/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1107/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1107/caldera-online-storybook/
sdds-serv storybook: http://plasma.sberdevices.ru/pr/pr-1107/sdds-serv-storybook/

2024-03-14 12:26 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1107/

2024-03-15 09:47 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Pagination/utils/index.ts
> +const generateSectiion = (length: number, add: number) => {
[опечатка]
Section

2024-03-15 14:55 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1107/

2024-03-15 15:04 UTC, TitanKuzmich approved these changes

2024-03-15 15:11 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1107/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1107/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1107/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1107/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1107/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1107/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1107/caldera-online-storybook/
sdds-serv storybook: http://plasma.sberdevices.ru/pr/pr-1107/sdds-serv-storybook/

2024-03-17 17:08 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/plasma_web/components/Pagination/Pagination.stories.tsx
> +export const Default: Story = {
<img width="1184" alt="image" src="https://github.com/salute-developers/plasma/assets/26903236/36ec848a-5bb5-4213-bca0-eb78490fb56e">

не совсем очевидно, как должен работать селект - разве выбор значения не должен влиять на пагинацию?

2024-03-17 17:10 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/plasma_web/components/Pagination/Pagination.stories.tsx
> +        size: 'xs',
![Uploading image.png…]()

также при сайзе `s` и выше ширина выпадающего меню не увеличивается. Либо её нужно сделать сразу широкой, либо менять в зависимости от значения

2024-03-17 17:13 UTC, neretin-trike commented
добавь пожалуйста документацию для компонента. По аналогии с другими компонентами. За пример / основу можешь взять [Chip.mdx](https://github.com/salute-developers/plasma/blob/391e305417acd9b478d3be5811b4ae2676f202f1/website/plasma-web-docs/docs/components/Chip.mdx)

2024-03-17 17:15 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/plasma_web/components/Pagination/Pagination.stories.tsx
> +        isQuickJump: true,
нужно переименовать здесь, и вдругих сторях на `hasQuickJump`

2024-03-17 17:15 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/plasma_web/components/Pagination/Pagination.stories.tsx
> +        isPerPage: true,
нужно переименовать здесь, и вдругих сторях на `hasPerPage`

2024-03-17 17:16 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/plasma_web/components/Pagination/Pagination.stories.tsx
> +export const Default: Story = {
возможно ломается из-за старого нейминга (isPerPage) свойств

2024-03-17 17:19 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.types.ts
> +    stretching?: boolean;
для сохранения консистетности API, вместо boolean нужно использовать перечисление. Например как это сейчас сделано в кнопке. Сохранить нужно только используемые значения

```typescript
type Stretching = 'fixed' | 'filled' | 'auto';

/**
 * Ширина кнопки
 * @description
 * Может принимать три значения:
 * fixed - кнопка фиксированной ширины;
 * filled - кнопка занимает всю доступную ширину
 * auto - кнопка растягивается в зависимости от контента
 */
stretching?: Stretching;

```

2024-03-17 17:22 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Pagination/Pagination.config.ts
> +                ${paginationTokens.paginationButtonColor}: var(--text-primary);
кажется, что добавлять название компонента в сами токены данном случае избыточно. Поэтому привести всё к такому виду:

```diff
-
${paginationTokens.paginationButtonColor}: var(--text-primary);
+
${paginationTokens.buttonColor}: var(--text-primary);
```

2024-03-17 17:25 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/variations/_size/base.ts
> +    font-weight: var(${tokens.paginationFontWeight});
нужно докинуть остальные свойства: letter-spacing и line-height

2024-03-17 17:26 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.types.ts
> +type CreateArrayWithLengthX<LENGTH extends number, ACC extends unknown[] = []> = ACC['length'] extends LENGTH
а можешь вкратце рассказать, какую задачу это решает?

2024-03-17 17:27 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.types.ts
> +type NumericRange<
и здесь тоже

2024-03-17 17:33 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.types.ts
> +type NumericRange<
<img width="551" alt="image" src="https://github.com/salute-developers/plasma/assets/26903236/1f3b74a3-7ef6-4063-ba33-b4c30b51a87f">

я правильно понимаю, что в итоге этот тип генерирует набор последовательных чисел с учётом их количества? То есть как в данном примере: мы хотим, чтобы было 7 чисел до 15, но тогда выводится корректное количество значений

2024-03-17 18:27 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.types.ts
> +    size?: 'xs' | 's' | 'm' | 'l';
тут нужно просто string указать, т.к. сам набор формируется на уровне типов автоматически, когда указываешь эти значения в конфигах

2024-03-17 18:27 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.types.ts
> +    view?: 'clear' | 'disabled' | 'secondary';
тут нужно просто string указать, т.к. сам набор формируется на уровне типов автоматически, когда указываешь эти значения в конфигах

2024-03-17 18:29 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +            css: typeCSS,
пока не пойму, насколько обязательно это сюда выводить 🤔 Может можно обойтись без такого способа? Чтобы потом в конфиге пустые стили не создавать

2024-03-17 18:33 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.types.ts
> +    disabled?: number[];
давай подложим себе соломку на будущее и сделаем string[] на случай, если появится необходимость поддерживать диапазоны заблокированных значений. И чтобы можно было в итоге передавать `['1', '5-59','99']`

2024-03-17 18:34 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.types.ts
> +    isCommonButtonStyles?: boolean;
а тут не надо переименовать в hasCommonButtonStyles?

2024-03-17 18:36 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.types.ts
> +     * Выбренное количество результатов на странице
кажется нужно переименовать

2024-03-17 18:38 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.styles.ts
> +        flex-direction: row !important;
а почему понадобилось именно important использовать?

2024-03-17 18:41 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +                            hasPerPage ? classes.isPerPageSelect : '',
давай перенесем в переменную. Как-нибудь типа `withHasPerPageSelect`

2024-03-17 18:42 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tokens.ts
> +    isPerPageSelect: 'pagination-is-per-page-select',
тут тоже нужно переименовать `is` => `has`

2024-03-17 18:44 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +                                return (
*минор*

давай попробуем return убрать

2024-03-17 18:45 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +                                                                : '',
давай вот это в переменную-функцию завернём

2024-03-17 18:46 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +                                                        pin={pilled ? 'circle-circle' : 'square-square'}
это тоже пожалуста в переменную

2024-03-17 18:47 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +                        {hasQuickJump && <PaginationQuickJumpToPage onChangeValue={(event) => setPage(event)} />}
предлагаю переименовать хенделр в onChangeValue={onChangeValuePage}

2024-03-17 18:48 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +                                onChangeValue={(event) => setPerPage(event)}
предлагаю переименовать хендлер в onChangeValue={onChangeValuePerPage}

2024-03-17 18:50 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/ui/PaginationQuickJumpToPage/PaginationQuickJumpToPage.styles.ts
> +export const QuickJumpToPageInput = styled.input`
по-идее тут нужно использовать компонент TextField. Попробуй его заюзать и стилизовать по аналогии с Button

2024-03-17 18:51 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/ui/PaginationQuickJumpToPage/PaginationQuickJumpToPage.tsx
> +            <QuickJumpToPageInput type="number" placeholder="#" onKeyUp={handleKeyPress} onChange={handleChangeInput} />
placeholder не должен мочь переопределяться?

2024-03-17 18:54 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/ui/PaginationSelectPerPage/PaginationSelectPerPage.tsx
> +            <SelectPerPageTypography>Show</SelectPerPageTypography>
надо подумать, что делать с локализацией. Но вообще не уверен, что именно `Show` должно быть, поскольку компонент будет использоваться в русскоязычных сервисах в том числе. 
Ребят, подскажите плс @iljs

2024-03-17 18:54 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/ui/PaginationSelectPerPage/PaginationSelectPerPage.tsx
> +                onChangeValue={(event: SelectPrimitiveValue | undefined) => handleSelectChange(event)}
можно упросить до onChangeValue={handleSelectChange}

2024-03-17 23:24 UTC, shuga2704 requested changes

2024-03-17 23:24 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +                                                        key={indexPage}
Не уверен, но в теории тут могут быть траблы, если будет меняться массив `sections`. Мы не можем привязаться к `pageValue` (оно ведь уникальное, если я правильно понимаю)?

2024-03-17 23:24 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +                                                                : '',
Можно убрать falsy-часть, `cx` проглотит undefined.

2024-03-17 23:24 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +                        {hasQuickJump && <PaginationQuickJumpToPage onChangeValue={(event) => setPage(event)} />}
А зачем? Давай просто оставим его таким: `onChangeValue={setPage}`

2024-03-17 23:24 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +                                onChangeValue={(event) => setPerPage(event)}
Также как и сверху

2024-03-17 23:24 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Pagination/Pagination.types.ts
> +     * Функция которая исполнятеся при изменении
```suggestion
     * Функция которая исполняется при изменении
```

2024-03-17 23:24 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tokens.ts
> +    selectWrapper: 'pagination-selectWrapper',
Давай тут тоже писать в стиле кебаб

2024-03-17 23:24 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Pagination/ui/PaginationSelectPerPage/PaginationSelectPerPage.tsx
> +        (newValue: SelectPrimitiveValue | undefined) => {
Тут может прийти невалидный стринг или булеан, обретка Number выдаст NaN или 0 или 1. Это корректный сценарий?

2024-03-17 23:29 UTC, shuga2704 commented on cypress/snapshots/b2c/components/Pagination/Pagination.component-test.tsx/plasma-new-hope Pagination Content -- clickOnContent.snap.png
Если в поле Go to ввести цифру, и сделать клик где-нибудь на странице (по сути onBlur на инпуте), то страница не поменяется, а цифра в инпуте останется. Это валидное поведение?

2024-03-18 10:08 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +                        {hasQuickJump && <PaginationQuickJumpToPage onChangeValue={(event) => setPage(event)} />}
ну просто всё, что начинается с set, обычно называют реактовским колбэкбом на изменение стейта. А тут кастомный обработчик, который принимает event в качестве аргумента

2024-03-19 16:42 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1107/

2024-03-19 16:59 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1107/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1107/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1107/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1107/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1107/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1107/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1107/caldera-online-storybook/
sdds-serv storybook: http://plasma.sberdevices.ru/pr/pr-1107/sdds-serv-storybook/

2024-03-20 07:53 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1107/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1107/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1107/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1107/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1107/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1107/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1107/caldera-online-storybook/
sdds-serv storybook: http://plasma.sberdevices.ru/pr/pr-1107/sdds-serv-storybook/

2024-03-20 16:01 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/ui/PaginationQuickJumpToPage/PaginationQuickJumpToPage.styles.ts
> +export const QuickJumpToPageInput = styled.input`
решили пока оставить так. @iljs добавь плс [issue](https://github.com/salute-developers/plasma/issues) с сообщением "перевести на TextField, когда появится возможность стилизовать", а тут TODO в формате 
// TODO: #номер_ишью

2024-03-20 16:05 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/plasma_web/components/Pagination/Pagination.stories.tsx
> +};
<img width="833" alt="image" src="https://github.com/salute-developers/plasma/assets/26903236/b7eb97b4-fcd3-42ec-a052-1bf66ec8b932">

у нас не должны совпадать скругления для textField и button? @simashova

2024-03-20 16:09 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/plasma_web/components/Pagination/Pagination.stories.tsx
> +        slots: 9,
<img width="582" alt="image" src="https://github.com/salute-developers/plasma/assets/26903236/22690e76-d2ee-42ec-9e32-f6a0aebbbaae">

<img width="1255" alt="image" src="https://github.com/salute-developers/plasma/assets/26903236/cade40fd-d389-4df0-9bab-86a8799a32ff">

может как-то нужно указать, что минимальное значение 5? И почему именно это число?

2024-03-20 16:39 UTC, iljs commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +                                                                : '',
+

2024-03-20 16:39 UTC, iljs commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +                                                        pin={pilled ? 'circle-circle' : 'square-square'}
+

2024-03-20 16:39 UTC, iljs commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +                        {hasQuickJump && <PaginationQuickJumpToPage onChangeValue={(event) => setPage(event)} />}
+

2024-03-20 16:40 UTC, iljs commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +                                onChangeValue={(event) => setPerPage(event)}
+

2024-03-20 16:41 UTC, iljs commented on packages/plasma-new-hope/src/components/Pagination/ui/PaginationQuickJumpToPage/PaginationQuickJumpToPage.tsx
> +            <QuickJumpToPageInput type="number" placeholder="#" onKeyUp={handleKeyPress} onChange={handleChangeInput} />
Теперь есть

2024-03-20 16:41 UTC, iljs commented on packages/plasma-new-hope/src/components/Pagination/ui/PaginationSelectPerPage/PaginationSelectPerPage.tsx
> +            <SelectPerPageTypography>Show</SelectPerPageTypography>
Сделал как пропс

2024-03-20 16:53 UTC, iljs commented on packages/plasma-new-hope/src/examples/plasma_web/components/Pagination/Pagination.stories.tsx
> +};
fixed

2024-03-20 16:55 UTC, iljs commented on packages/plasma-new-hope/src/examples/plasma_web/components/Pagination/Pagination.stories.tsx
> +        slots: 9,
сегодня обсудили, что дипозон будет от 7 до 15 с Настей

2024-03-20 16:56 UTC, iljs commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tokens.ts
> +    selectWrapper: 'pagination-selectWrapper',
fixed

2024-03-20 16:56 UTC, iljs commented on packages/plasma-new-hope/src/components/Pagination/utils/index.ts
> +export const defaultValues = {
yes

2024-03-20 16:56 UTC, iljs commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +            type = defaultValues.type,
fixed

2024-03-20 16:56 UTC, iljs commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +        }, [value, setPageValue]);
fixed

2024-03-20 16:57 UTC, iljs commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +        }, [page, slots, pages, perPageValue, setSections, getSections]);
fixed

2024-03-20 16:57 UTC, iljs commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +            stretching = defaultValues.stretching,
fixed

2024-03-20 16:57 UTC, iljs commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +                <PaginationRoot className={cx(typeClass)}>
fixed

2024-03-20 16:57 UTC, iljs commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +                                                return (
fixed

2024-03-20 16:57 UTC, iljs commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +                                                        key={indexPage}
fixed

2024-03-20 16:57 UTC, iljs commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +                                                                : '',
fixed

2024-03-20 16:58 UTC, iljs commented on cypress/snapshots/b2c/components/Pagination/Pagination.component-test.tsx/plasma-new-hope Pagination Content -- clickOnContent.snap.png
я думаю да,бывают мисклики

2024-03-20 17:04 UTC, iljs commented on packages/plasma-new-hope/src/components/Pagination/utils/index.ts
> +const generateSectiion = (length: number, add: number) => {
fixed

2024-03-20 17:06 UTC, iljs commented on packages/plasma-new-hope/src/components/Pagination/Pagination.types.ts
> +    stretching?: boolean;
fixed

2024-03-20 17:07 UTC, iljs commented on packages/plasma-new-hope/src/components/Pagination/Pagination.types.ts
> +     * Выбренное количество результатов на странице
fixed

2024-03-20 17:07 UTC, iljs commented on packages/plasma-new-hope/src/components/Pagination/Pagination.styles.ts
> +        flex-direction: row !important;
fixed

2024-03-20 23:16 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1107/

2024-03-20 23:27 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1107/

2024-03-20 23:43 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1107/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1107/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1107/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1107/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1107/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1107/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1107/caldera-online-storybook/
sdds-serv storybook: http://plasma.sberdevices.ru/pr/pr-1107/sdds-serv-storybook/

2024-03-21 09:32 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +                                            return (
убери пожалуйста return

2024-03-21 09:39 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.types.ts
> +    slots?: NumericRange<CreateArrayWithLengthX<7>, 15>;
добавь пожалуйста минимальное и максимально количество слотов

2024-03-21 09:42 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/utils/index.ts
> +export const defaultValues = {
да, мне кажется можно здесь хранить, т.к. у нас почти нет файлов для констант

2024-03-21 09:43 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/utils/index.ts
> +export const isNumber = (value: unknown) => !Number.isNaN(Number(value));
вынеси пожалуйста в глобальный util

2024-03-22 08:52 UTC, Yakutoc commented on website/sdds-serv-docs/docs/components/Pagination.mdx
> +import { PropsTable, Description, StorybookLink } from '@site/src/components';
@iljs 

StorybookLink - не нужен здесь. Посмотри как у остальных компонентов документации это сделано

2024-03-22 11:52 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.types.ts
> +    disabled?: string[];
договаривались, что лучше будет переименовать пропс для большей читаемости. Типа disabledPages или вроде того

2024-03-22 11:56 UTC, neretin-trike commented on website/plasma-web-docs/docs/components/Pagination.mdx
> +<StorybookLink name="Chip" />
Pagination

2024-03-22 11:57 UTC, neretin-trike commented on website/plasma-web-docs/docs/components/Pagination.mdx
> +Chips могут отображаться в нескольких размерах и цветах, могут содержать текст и/или иконку.
здесь нужно корректное описание

2024-03-22 11:57 UTC, neretin-trike commented on website/sdds-serv-docs/docs/components/Pagination.mdx
> +Chips могут отображаться в нескольких размерах и цветах, могут содержать текст и/или иконку.
здесь нужно корректное описание

2024-03-22 11:59 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tokens.ts
> +    selectTargetPadding: '--plasma-pagination-select-target-padding',
не уверен, что прям все токены нужны, но оставим выпил не нужного на потом

2024-03-22 13:10 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Pagination/utils/index.ts
> +    disabled: [],
нужно переименовать

2024-03-22 14:39 UTC, shuga2704 requested changes

2024-03-22 14:39 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Pagination/ui/PaginationSelectPerPage/PaginationSelectPerPage.tsx
> +    };
```suggestion
    const handleSelectChange = (newValue?: SelectPrimitiveValue) => {
        if (newValue) {
            setSelectedValue(Number(newValue));
            onChangeValue?.(Number(newValue));
        }
    };
```

2024-03-22 14:39 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +        }, [count, perPage, hasPerPage, setPagesValue]);
Наведи красоту)

2024-03-22 14:39 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tokens.ts
> +    perPage: 'pagination-perpage-select',
```suggestion
    perPage: 'pagination-per-page-select',
```

2024-03-22 14:39 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +        } = props;
Давай деструктуризируем на 25 строке, т.к. нам не нужна переменная `props`

2024-03-22 14:39 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +        const handlerSetPages = (newPerPage: number | undefined) => {
```suggestion
        const handlerSetPages = (newPerPage?: number) => {
```

2024-03-22 14:39 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Pagination/Pagination.tsx
> +        const handlerSetPage = (newPageValue: number | null | undefined) => {
тут также с undefined

2024-03-25 07:48 UTC, neretin-trike approved these changes

2024-03-26 19:18 UTC, merged