feat: Progress redesign refactor
salute-developers/plasma pull request #1126
Opened 2024-03-18 14:46 UTC by TitanKuzmich

### Progress

- добавлен компонент Progress в new-hope
- добавлен в поставку в пакеты b2c, web, sdds-serv
- написаны тесты и документация

### What/why changed

Рефакторинг и редизайн компонента Progress.

2024-03-18 14:49 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-1126/

2024-03-18 15:10 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-1126/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-1126/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-1126/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-1126/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-1126/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-1126/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-1126/caldera-online-storybook/
sdds-serv storybook: http://plasma.sberdevices.ru/pr/pr-1126/sdds-serv-storybook/

2024-03-20 08:08 UTC, Irinkv approved these changes

2024-03-21 11:04 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Progress/Progress.config.ts
> +                ${progressTokens.valueColor}: var(--plasma-colors-tertiary);
используй пожалуйста новые токены

2024-03-21 12:13 UTC, neretin-trike approved these changes

2024-03-21 18:26 UTC, shuga2704 requested changes

2024-03-21 18:26 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Progress/Progress.tsx
> +        const { view, status, value, displayValue = true, ...rest } = props;
Думаю лучше сделать деструктуризацию на 11 строке, т.к. отдельно `props` нам больше нигде не нужен

2024-03-22 08:06 UTC, shuga2704 approved these changes

2024-03-22 09:28 UTC, merged