feat(plasma-new-hope): tooltip old api fallback
salute-developers/plasma pull request #1140
Opened 2024-03-21 11:12 UTC by TitanKuzmich

### Tooltip

-  добавлены фалбэки на следующие свойства: isVisible, arrow, animated

### What/why changed

При рефакторинге тултипа потерялись некоторые пропсы из-за чего пропала обратная совместимость.

2024-03-21 12:09 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Tooltip/Tooltip.types.ts
> +     * @deprecated
кста мож не делать deprecated? Чтобы при желании у пользователя была возможность включить дефолтную анимацию одним флагом

2024-03-21 12:10 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Tooltip/Tooltip.types.ts
> +     * @deprecated
Да, могу убрать deprecate

2024-03-21 12:10 UTC, neretin-trike commented on packages/sdds-serv/src/components/Tooltip/Tooltip.config.ts
> +                ${tooltipTokens.boxShadow}: 0px 4px 12px 0px rgba(0, 0, 0, 0.16),0px 1px 4px 0px rgba(0, 0, 0, 0.08);
давай TODO добавим ссылкой на этот issue https://github.com/salute-developers/plasma/issues/1131

2024-03-21 12:11 UTC, neretin-trike approved these changes

2024-03-22 07:54 UTC, shuga2704 commented
Раз уж мы дошли до рефакторинга тултипа, может еще и это профиксим? https://github.com/salute-developers/plasma/issues/1121

2024-03-25 07:47 UTC, shuga2704 requested changes

2024-03-25 08:34 UTC, shuga2704 approved these changes

2024-03-26 10:55 UTC, merged