feat(new-hope): Add cell
salute-developers/plasma pull request #1148
Opened 2024-03-26 08:59 UTC by iljs

### Cell

Компонент Cell

### What/why changed

Добавил компонент Cell, который также включает компоненты Textbox, TextTitle, TextSubtitle, TextLabel

2024-03-26 15:05 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Cell/Cell.config.ts
> +            filled: css``,
fixed тоже нужно указать

2024-03-26 15:05 UTC, TitanKuzmich commented
Добавь еще тесты на alignment, без контента справа/слева. Глянь, какие тесты есть в plasma-ui

2024-03-27 07:23 UTC, Yakutoc commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Cell/Cell.config.ts
> +                ${cellTokens.cellPadding}: 0rem;
[Уточнение]

@iljs Для этих значений токены не нужны?

2024-03-27 07:45 UTC, TitanKuzmich commented on packages/plasma-b2c/src/components/Cell/Cell.stories.tsx
> +type sizesAvatar = 'l' | 'm' | 's';
Типы с большой буквы

2024-03-27 07:45 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Cell/Cell.tokens.ts
> +    cellPaddingContent: '--plasma-cell-padding',
--plasma-cell-content-padding

2024-03-27 07:45 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Cell/Cell.tokens.ts
> +    cellStretch: 'cell-stretch',
Этот класс не нужен

2024-03-27 07:45 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Cell/Cell.types.ts
> +    size: Sizes;
Сделай size необязательным параметром и поставь его тип string, движок сам распарсит типы

2024-03-27 07:45 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Cell/Textbox/Textbox.types.ts
> +export type AlignRightProp = 'center' | 'top';
у Right нет bottom?

2024-03-27 07:45 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Cell/Cell.stories.tsx
> +type sizesAvatar = 'l' | 'm' | 's';
Типы с большой буквы

2024-03-27 07:49 UTC, iljs commented on packages/plasma-new-hope/src/components/Cell/Textbox/Textbox.types.ts
> +export type AlignRightProp = 'center' | 'top';
да, делал по аналогии с ui

2024-03-27 08:46 UTC, iljs commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Cell/Cell.config.ts
> +                ${cellTokens.cellPadding}: 0rem;
Мне кажется нужны, вдруг потребуется ширину поменять у определенного размера или отступы решим добавить.

2024-03-27 08:51 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Cell/Textbox/Textbox.types.ts
> +export type AlignRightProp = 'center' | 'top';
Но а в принципе в дизайне есть такой вариант?

2024-03-27 09:37 UTC, simashova approved these changes

2024-03-27 11:17 UTC, shuga2704 requested changes

2024-03-27 11:17 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Cell/Cell.tsx
> +                            )}
Не забывает про DRY

```suggestion
                            <Textbox label={label} title={title} subtitle={subtitle}>
                                {children}
                            </Textbox>
```

2024-03-27 11:17 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Cell/Textbox/Textbox.tsx
> +    const { label, title, subtitle, children } = props;
Не забываем, что если мы не используем props где-либо ниже, то дестриктуризируем сразу в параметрах функции.

2024-03-27 11:17 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Cell/Cell.types.ts
> +    label?: ReactNode;
Давай заэкстендимся из Textbox props

2024-03-27 11:17 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Cell/Cell.types.ts
> +export type AlignRightProp = 'center' | 'top';
И кстати типы повторяются и в Textbox

2024-03-27 11:17 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Cell/Textbox/ui/TextLabel.tsx
> +};
Для чего этот тип нужен, если в пропах только чилдрен? Точно также и в TextSubtitle и TextTitle

2024-03-27 11:17 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Cell/Cell.tokens.ts
Давай писать так, чтобы кебаб-кейс был точной копией верблюда с припиской --plasma в начале?

2024-03-27 11:17 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Cell/index.ts
> +export type { TextboxProps } from './Textbox/Textbox.types';
А зачем отдавать консумеру Textbox, если он по дефолту применится. А если консумер хочет просунуть свой чилдрен, значит его не устраивает чем-то Textbox.

2024-03-27 11:17 UTC, shuga2704 commented on packages/plasma-b2c/src/components/Cell/Cell.stories.tsx
> +};
Думаю можем удалить эту сторю, т.к. визуал одинаковый с default

2024-03-27 11:17 UTC, shuga2704 commented on packages/plasma-b2c/src/components/Cell/Cell.stories.tsx
> +};
Тоже самое, ремув

2024-03-27 11:17 UTC, shuga2704 commented on packages/plasma-b2c/src/components/Cell/Cell.stories.tsx
Многих пропсов не хватает в default, добавишь?

2024-03-27 11:24 UTC, iljs commented on packages/plasma-b2c/src/components/Cell/Cell.stories.tsx
yes

2024-03-27 11:25 UTC, iljs commented on packages/plasma-new-hope/src/components/Cell/Cell.types.ts
> +    stretching?: 'fixed' | 'filled' | 'auto';
Это из дизайна, поэтому я думаю это лучше оставить

2024-03-27 11:26 UTC, iljs commented on packages/plasma-new-hope/src/components/Cell/Cell.tsx
> +        },
По дизайну я так понимаю потом будет еще разные view, потому лучше сразу заложить так и после добавить еще. Тоже на стороне дизайна попросили

2024-03-27 11:28 UTC, iljs commented on packages/plasma-new-hope/src/components/Cell/Cell.types.ts
> +export type AlignRightProp = 'center' | 'top';
Сделано по аналогии с UI, там этого нет, поэтому и тут нет

2024-03-27 11:48 UTC, iljs commented on packages/plasma-new-hope/src/components/Cell/Cell.tsx
> +                </CellRoot>
Общую структуру брал из UI, избавился от CellRoot, Wrapper нужен

2024-03-27 12:41 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Cell/index.ts
> +export type { TextboxProps } from './Textbox/Textbox.types';
@neretin-trike

2024-03-27 12:45 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Cell/Cell.types.ts
> +    stretching?: 'fixed' | 'filled' | 'auto';
@neretin-trike

2024-03-27 13:25 UTC, iljs commented on packages/plasma-new-hope/src/components/Cell/Cell.types.ts
> +export type AlignRightProp = 'center' | 'top';
complite

2024-03-28 06:58 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Cell/Cell.config.ts
> +        },
а может есть возможность убрать stretching из конфигов? Поскольку во всех компонентах поведения для этого пропса у нас определяется на уровне ядра компонента

2024-03-28 07:04 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Cell/Textbox/Textbox.types.ts
> +export type AlignRightProp = 'center' | 'top';
а что тут решили в итоге? Кажется странным, что правый контент по bottom нельзя уровнять

2024-03-28 07:05 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Cell/Textbox/Textbox.types.ts
> +export type AlignLeftProp = 'center' | 'top' | 'bottom';
вообще судя по ко коду это нигде не используется, оно точно нужно?

2024-03-28 07:06 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Cell/Cell.types.ts
> +    alignLeft?: AlignProp;
предлагаю назвать alignContentLeft / alignContentRight. Потому что я по-началу совсем не понял на что влияет изменение этих пропсов

2024-03-28 07:08 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Cell/Textbox/Textbox.tsx
> +export const Textbox: React.FC<HTMLAttributes<HTMLDivElement> & TextboxProps> = ({
может рассмотрим вариант вынести TextBox из Cell на уровень выше и держать его как отдельный компонент? По аналогии с тем же Cell. Или не может быть кейсов, когда TextBox используется отдельно от Cell? 

@simashova @Yeti-or

2024-03-28 07:29 UTC, iljs commented on packages/plasma-new-hope/src/components/Cell/Cell.types.ts
> +    alignLeft?: AlignProp;
Там в подзадаче сказали использовать API из ui. Там сделаны именно такие параметры, как у меня

2024-03-28 07:29 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Cell/Textbox/Textbox.types.ts
> +export type AlignRightProp = 'center' | 'top';
Решили добавить bottom и сделать один AlignProp

2024-03-28 07:30 UTC, iljs commented on packages/plasma-new-hope/src/components/Cell/Textbox/Textbox.tsx
> +export const Textbox: React.FC<HTMLAttributes<HTMLDivElement> & TextboxProps> = ({
Мне кажется не имеет смысла

2024-03-28 12:20 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Cell/Cell.types.ts
> +    alignLeft?: AlignProp;
ну возможно имелось ввиду взять похожий подход. Но зачем нам полностью копировать этот API? Тем более, что сами пропсы кажется требуют уточнения в семантике

2024-03-28 12:25 UTC, neretin-trike commented on packages/plasma-b2c/src/components/Cell/Cell.component-test.tsx
> -../../../../plasma-web/src/components/Cell/Cell.component-test.tsx
давай сохраним symlink, который указывает на web файл тестов

2024-03-28 12:26 UTC, neretin-trike commented on packages/plasma-b2c/src/components/Cell/Cell.config.ts
> +        stretching: 'filled',
отсюда можно удалить

2024-03-28 12:28 UTC, neretin-trike commented on packages/plasma-b2c/src/components/Cell/Cell.stories.tsx
>          );
у нас сильно изменился API по сравнению с текущим (мастеровым) Cell - разве нам не надо прослойку для b2c/web в таком случае сделать? 

@Yeti-or @TitanKuzmich @shuga2704

2024-03-28 12:29 UTC, neretin-trike commented on packages/plasma-b2c/src/components/Cell/Cell.stories.tsx
> +        const MyStyledText = styled.div`
<img width="932" alt="image" src="https://github.com/salute-developers/plasma/assets/26903236/834c3bad-044a-4f89-825f-1bdfb132b39b">

почему-то типы сильно разломаны. У тебя в IDE нет ошибок?

2024-03-28 12:31 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Cell/Cell.stories.tsx
> +            <Cell
<img width="932" alt="image" src="https://github.com/salute-developers/plasma/assets/26903236/b42f4bcb-9c00-4d64-b663-25be6c62c0c4">

почини пожалуйста. Скорее всего нужно rest оператор убрать, и явно прокинуть все пропсы

2024-03-28 12:35 UTC, neretin-trike commented on website/plasma-web-docs/docs/components/Cell.mdx
> +### Базовое использование с использованием своих стилей или встроеных компонентов
"С использованием своих стилей или встроеных компонентов"

2024-03-28 12:37 UTC, neretin-trike commented on packages/plasma-b2c/src/components/Cell/Cell.stories.tsx
>          );
хотя в данном случае можно обойтись директивой deprecated: 
- старый `content` => новый `contentLeft` 
- старый `description` => новый `title`

2024-03-28 12:38 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Cell/Cell.tsx
> +                stretching,
тут тогда нужно значение по дефолту добавить

2024-03-28 12:42 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Cell/Cell.types.ts
> +    stretching?: 'fixed' | 'filled' | 'auto';
считаю, что если по макетам есть определенная ширина для этого компонента, то можно оставить это fixed, и указать нужное значение в конфигах

2024-03-28 12:43 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Cell/Cell.config.ts
> +        stretching: 'filled',
тоже можно убрать

2024-03-28 12:44 UTC, neretin-trike commented on packages/plasma-web/src/components/Cell/Cell.component-test.tsx
> +describe('plasma-new-hope: Cell Styled', () => {
а точно надо на new-hope переделывать? 🤔

2024-03-28 12:45 UTC, neretin-trike commented on packages/plasma-web/src/components/Cell/Cell.config.ts
> +        stretching: 'filled',
отсюда тож

2024-03-28 12:48 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Cell/index.ts
> +export type { TextboxProps } from './Textbox/Textbox.types';
просто таким образом облегчим жизнь пользователю. Например ему захотелось caption четвертой строкой. И вместо того, чтобы для всех 4ых писать самостоятельно стили, ему достаточно будет забрать всё, мы отдаём (TextBox / TextBoxLabel / TextBoxTittle / TextBoxSubTittle), собрать воедино и добавить один свой дивчик (или спан)

2024-03-28 12:51 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Cell/Textbox/Textbox.tsx
> +export const Textbox: React.FC<HTMLAttributes<HTMLDivElement> & TextboxProps> = ({
если не имеет, тогда предлагаю обозвать CellTextBox, для того, чтобы обозначить его как часть этого компонента и засунуть в ui директорию (на уровень с TextBoxLabel и т.д.). Сейчас по такому же принципу сделаны компоненты с API композицией (Select / Combobox /  Segment / Tabs)

2024-03-28 13:57 UTC, Yeti-or commented
у меня в этом пр частично сломан сторибук https://plasma.sberdevices.ru/pr/pr-1148/b2c-storybook/?path=/story/controls-button--default

2024-03-29 09:00 UTC, iljs commented on packages/plasma-new-hope/src/components/Cell/Cell.tsx
> +                        {contentRight && <CellRight align={alignRight}>{contentRight}</CellRight>}
Это обсуждали. При выравнивании по top / bottom он должен быть отнoсительно textbox. Это все уточнили у дизайнеров и все согласовано

2024-03-29 13:54 UTC, iljs commented on packages/plasma-b2c/src/components/Cell/Cell.component-test.tsx
> -../../../../plasma-web/src/components/Cell/Cell.component-test.tsx
А что ты тут имел ввиду, не очень понял

2024-04-01 13:33 UTC, neretin-trike commented
дока поломалась

<img width="836" alt="image" src="https://github.com/salute-developers/plasma/assets/26903236/9a57ac5d-7b8a-44c8-b164-83dbb8572f76">

и описание странное сгенерилось

<img width="904" alt="image" src="https://github.com/salute-developers/plasma/assets/26903236/889079d5-2ccd-422c-ba6b-72887bf42a39">

2024-04-01 13:34 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Cell/Cell.tsx
> +                                    description={description}
дак в макетах вроде нет этого свойства?

2024-04-01 13:38 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Cell/CellTextbox/ui/CellTextLabel.tsx
> +};
может это и оверхед, но хочется такую структуру во всех компонентах видеть

<img width="262" alt="image" src="https://github.com/salute-developers/plasma/assets/26903236/fa759c09-6bff-445b-8c63-13813a8b6680">

2024-04-01 13:38 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Cell/CellTextbox/CellTextbox.tsx
> +};
давай поместим этот компонент на уровень папки ui, чтобы было вот так:

<img width="262" alt="image" src="https://github.com/salute-developers/plasma/assets/26903236/08f81afb-8000-4bb1-9b92-2ab33497e423">

2024-04-03 06:32 UTC, neretin-trike approved these changes

2024-04-03 13:13 UTC, shuga2704 approved these changes

2024-04-03 13:39 UTC, merged