a11y(avatar): Refactoring a11y
salute-developers/plasma pull request #1180
Opened 2024-04-15 09:08 UTC by Yakutoc

### Avatar

- добавлен `aria-label`

### What/why changed

2024-04-16 14:35 UTC, Yeti-or reviewed
про мертвый код тоже в релиз ноутс пойдет ?

2024-04-16 14:35 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/Avatar/Avatar.tsx
> +    inactive: 'Неактивен',
меня смущает тут что мы будем делать когда придут ребята и попросят тут английский язык ? мы можем это вынести наружу ?

2024-04-17 06:19 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Avatar/Avatar.tsx
> +    inactive: 'Неактивен',
@Yeti-or хороший point. Исправлю

2024-04-18 06:14 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/Avatar/Avatar.template-doc.mdx
> +            <Avatar role="button" tabIndex={0} name="Иван Фадеев" url="https://avatars.githubusercontent.com/u/1813468?v=4" />
не совсем тут понимаю, мы не можем сами навесить role button ? tabIndex=0 ?  по умолчанию?

2024-04-18 06:14 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/Avatar/Avatar.template-doc.mdx
> +По-умолчанию стоит значение для русскоговорящих `{ active: 'Активен', inactive: 'Неактивен' }`.
может его назвать statusLabels ?

2024-04-18 06:35 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Avatar/Avatar.template-doc.mdx
> +По-умолчанию стоит значение для русскоговорящих `{ active: 'Активен', inactive: 'Неактивен' }`.
@neretin-trike @shuga2704 Парни что думаете?

2024-04-18 07:54 UTC, Yeti-or approved these changes

2024-04-18 08:03 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Avatar/Avatar.tsx
> +const StatusDictDefault = {
давай тут экспорт сделаем

2024-04-18 08:05 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Avatar/Avatar.types.ts
> +export type StatusDict = Record<'active' | 'inactive', string>;
и здесь `Record<keyof StatusDictDefault, string>`

2024-04-18 08:06 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Avatar/Avatar.tsx
> +};
давай сюда ещё тип поясняющий добавим:

`const StatusLabelsDefault: StatusLabels = {....}`

2024-04-18 08:06 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Avatar/Avatar.template-doc.mdx
> +По-умолчанию стоит значение для русскоговорящих `{ active: 'Активен', inactive: 'Неактивен' }`.
да, я тоже за statusLabels

2024-04-18 11:34 UTC, shuga2704 requested changes

2024-04-18 11:34 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Avatar/Avatar.tsx
> +    if (url && role && role === 'button') {
```suggestion
    if (url && role === 'button') {
```

2024-04-18 11:34 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Avatar/Avatar.tsx
> +    const { url, name, status, 'aria-label': ariaLabelProp, role, statusLabels } = props;
Давай деструктуризируем сразу в параметрах

2024-04-18 11:34 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Avatar/Avatar.tsx
> +    return undefined;
можем удалить строку, она по дефолту вернет undefined

2024-04-18 11:34 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Avatar/Avatar.tsx
> +        const ariaLabel = useMemo(
Думаю лучше отказаться тут от useMemo, т.к. непонятно что лежит в props на 85, да и в целом смысла в этом немного

2024-04-18 11:34 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Avatar/Avatar.tsx
> +                        <StyledIndicator aria-label={statusLabels[status]} status={status} />
Нам точно нужен aria-label в индикаторе? На нем же нет фокуса, а статус будет читаться на рутовом aria-label

2024-04-18 11:34 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Avatar/Avatar.types.ts
> +    // Увеличение при наведении
А если будет уменьшение?)

2024-04-19 03:35 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Avatar/Avatar.types.ts
> +    // Увеличение при наведении
@shuga2704 Согласен ) сам себя перемудрил. -10 очков Пуффендую )

2024-04-19 03:42 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Avatar/Avatar.tsx
> +                        <StyledIndicator aria-label={statusLabels[status]} status={status} />
@shuga2704 Нужен. 
Когда у нас нет изображения или мы указали custom text верхнего aria-label не будет. 

И поэтому нам нужно статус озвучить как есть.

2024-04-19 07:50 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Avatar/Avatar.tsx
> +                        <StyledIndicator aria-label={statusLabels[status]} status={status} />
А это точно так должно быть? Когда юзер не передал юрл, но передал aria-label, он же думает что все будет работать, а мы ему это запретим. 
От customText эта логика не зависит же?

2024-04-19 08:17 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Avatar/Avatar.tsx
> +                        <StyledIndicator aria-label={statusLabels[status]} status={status} />
@shuga2704 Я как считал. 

Вот мы передали изображение. Незрячий как то должен понять что там мы изобразили - `aria-label` решает эту проблему.

Во всех остальных случаях screen reader прочтет что лежит в node, будет то инициалы или custom text. 

Тут `aria-label` совершенно ни к чему. 

Комментарий от спец ребят 

> Мы руководствуемся принципом универсального дизайна, т.е. незрячий должен получить ту же информацию, что и зрячий. Если зрячий видит только первые буквы, то незрячий тоже должен увидеть только первые буквы, но если зрячий видит только первые буквы, но у него есть еще визуальные подсказки какие-то, к примеру, фотка или аватарка, то незрячему нужно больше инфы, тогда aria-label с полным name оправдан. Другими словами, если в случае текста отображается просто первые буквы и никаких визуальных подсказок, то в этом случае можно и aria-lanbel не использовать.
Статус визуально что-то сообщает, поэтому это нужно и текстом сообщить. Нужно текстом передать смысл, к примеру, онлайн или недоступен или еще что-то такое.

2024-04-19 08:47 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Avatar/Avatar.tsx
> +                        <StyledIndicator aria-label={statusLabels[status]} status={status} />
1. Окей, просто юзер может не понять, почему он прокинул aria-label, а его в дом нет. Мне всегда казалось, что это юзеры сами должны настраивать такие моменты, нам лишь надо предоставлять возможность. Лично я не против твоего подхода)
2. А не будет коллизии когда есть aria-label у аватара, и также у фокуса? Ридер прочтет статус дважды получается?

2024-04-19 09:04 UTC, shuga2704 approved these changes

2024-04-19 09:08 UTC, neretin-trike approved these changes

2024-04-19 09:22 UTC, merged