feat(plasma-new-hope): add slider component
salute-developers/plasma pull request #1194
Opened 2024-04-23 14:40 UTC by TitanKuzmich

### Slider

- добавлен компонент Slider

### What/why changed

 Добавлен компонент Slider

2024-05-02 14:38 UTC, Irinkv approved these changes

2024-05-03 08:18 UTC, TitanKuzmich commented on packages/plasma-b2c/src/components/Slider/Slider.tsx
> + * Кнопка.
Поправь коммент

2024-05-03 08:20 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Slider/components/Double/Double.types.ts
> +    // onChange?: (value: number) => void;
Вот это нужно для обратной совместимости сохранить

2024-05-03 08:22 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Slider/components/Single/Single.types.ts
> +    // onChange?: (value: number) => void;
Нужно в типах поправить для обратной совместимости
И в самом коде юзать этот onChange

2024-05-03 12:34 UTC, neretin-trike commented
кажется что-то с тестами, 2 и 3 слайдер одинакового размера 


<img width="531" alt="image" src="https://github.com/salute-developers/plasma/assets/26903236/dd5491d9-8017-486b-9cb9-0b4f1e8057c9">

2024-05-03 12:43 UTC, neretin-trike commented on packages/plasma-new-hope/package.json
> +    "react-draggable": "4.4.3",
из dev зависимости нужно удалить

2024-05-03 13:06 UTC, neretin-trike commented on packages/plasma-web/src/components/Slider/Slider.stories.tsx
> +import { Slider } from './Slider';
не уверен, но кажется при состоянии disabled и при наведении курсором на кружок, он должен становиться not-allowed (как и в остальных компонентах)

2024-05-03 13:07 UTC, neretin-trike commented on packages/plasma-new-hope/src/utils/canUseDOM.ts
> +export const canUseDOM = !!(
давай это явно в Boolean обернём

2024-05-03 13:12 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Slider/Slider.tsx
> +/**
кажется, что этот комментарий лучше добавлять в место, где компонент собирается, то есть

```ts
...
const mergedConfig = mergeConfig(slideConfig, config);
export const Slider = component(mergedConfig);
...
```

2024-05-03 13:12 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Slider/Slider.tsx
> +const isSingleValueProps = (props: SliderProps): props is SingleSliderProps => typeof props.value === 'number';
*минор*

добавь пожалуйста разделяющую пустую строку

2024-05-03 13:17 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Slider/ui/Thumb/Thumb.styles.ts
> +        margin: -2px;
давай везде в этом файле на ремы перделаем

2024-05-03 13:18 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Slider/ui/Thumb/Thumb.styles.ts
> +        left: 0;
*минор*

можно использовать inset: 0 вместо этих четырёх свойств

2024-05-03 13:25 UTC, neretin-trike commented on packages/plasma-web/src/components/Slider/Slider.stories.tsx
> +const meta: Meta<typeof Slider> = {
так же нет никакой индикации, что пользователь сфокусировался на компоненте.

При этом в [мастере](https://plasma.sberdevices.ru/b2c-storybook/?path=/story/controls-slider--default) при фокусе бордер кружка окрашивается

2024-05-03 13:26 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Slider/components/Single/Single.types.ts
> +    // onChange?: (value: number) => void;
нужно удалить?

2024-05-03 13:27 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Slider/components/Single/Single.types.ts
> +    size?: 'm' | 'l' | 's';
*минор*

надо превратить в string

2024-05-03 13:28 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Slider/components/Double/Double.types.ts
> +    inputPlaceholder?: string[];
не нашёл, как используется это свойство в компоненте, оно точно нужно?

2024-05-03 13:29 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Slider/ui/Thumb/Thumb.styles.ts
> +        background: var(${tokens.thumbFocusBorderColor});
кажется фокус не работает

2024-05-03 13:29 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Slider/ui/Thumb/Thumb.styles.ts
> +    }
вместо этого нужно использовать миксин addFocus

2024-05-03 13:30 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Slider/ui/Handle/Handle.styles.ts
> +    margin-left: -2px;
в rem

2024-05-03 13:33 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Slider/components/Double/Double.tsx
> +                        onSearch={(e) => onSecondTextfieldEnter(e)}
тут и выше можно упростить   
```diff
- onChange={(e) => onSecondTextfieldChange(e)}
+ onChange={onSecondTextfieldChange}
```

2024-05-03 13:34 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Slider/components/Double/Double.tsx
> +                        onChange={(e) => onFirstTextfieldChange(e)}
считаю, что нужно доработать пример в сторибуке и документации, чтобы при изменении числа в этих инпутах, значение слайдера тоже обновлялось (то есть кружок перерисовывался на новом месте)

2024-05-03 13:35 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Slider/components/Double/Double.tsx
> +            if (!isNumber(event.target.value)) return;
перенести плс в развернутый вариант. Мы не используем if в одну строку

2024-05-03 13:35 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Slider/components/Double/Double.tsx
> +            if (!isNumber(newValue)) return;
и тут

2024-05-03 13:36 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Slider/components/Double/Double.tsx
> +            if (firstHandleRef?.current) {
тут можно сделать инверсию чтобы избавиться от вложенности

2024-05-03 13:36 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Slider/components/Double/Double.tsx
> +            if (secondHandleRef?.current) {
тут можно сделать инверсию чтобы избавиться от вложенности

2024-05-03 13:57 UTC, neretin-trike commented on packages/plasma-new-hope/src/engines/common.tsx
> +        | undefined = undefined
блин, не очень нравится, как это выглядит :С По сути ядро не должно знать про какие-то специфичные кейсы.

Но пока тоже не могу придумать, как сделать лучше, поэтому давай где-нибудь тут повесим жирный INFO с описанием, для чего это нужно, ну и собственно выделим `Omit<React.HTMLAttributes<HTMLElement>, 'onChange'>` в отдельный тип и заменим по всех местах (в том числе Single.types.ts и Double.types.ts)

2024-05-03 13:59 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Slider/components/SliderBase/SliderBase.types.ts
> +    settings?: SliderSettings;
а это свойство всё ещё валидно, или для него нужно сделать fallback и поменить как deprecated?

2024-05-06 10:04 UTC, iljs commented on packages/plasma-new-hope/src/components/Slider/components/SliderBase/SliderBase.types.ts
> +    settings?: SliderSettings;
валидно

2024-05-06 11:58 UTC, iljs commented on packages/plasma-new-hope/src/components/Slider/components/Double/Double.tsx
> +                        onChange={(e) => onFirstTextfieldChange(e)}
срабатывает при нажатии на enter

2024-05-12 19:39 UTC, iljs approved these changes

2024-05-13 09:17 UTC, Yakutoc commented on packages/sdds-serv/api/sdds-serv.api.md
> +contentLeft?: string | number | boolean | ReactFragment | ReactPortal | ReactElement<any, string | JSXElementConstructor<any>> | FunctionComponent<any> | ComponentClass<any, any> | null | undefined;
@iljs 

А где import cамого компонента для этого пакета?

2024-05-13 09:20 UTC, iljs commented on packages/sdds-serv/api/sdds-serv.api.md
> +contentLeft?: string | number | boolean | ReactFragment | ReactPortal | ReactElement<any, string | JSXElementConstructor<any>> | FunctionComponent<any> | ComponentClass<any, any> | null | undefined;
в sdds serv не было слайдера, поэтому туда не добавил. Его надо туда?

2024-05-13 10:16 UTC, Yakutoc commented on packages/sdds-serv/api/sdds-serv.api.md
> +contentLeft?: string | number | boolean | ReactFragment | ReactPortal | ReactElement<any, string | JSXElementConstructor<any>> | FunctionComponent<any> | ComponentClass<any, any> | null | undefined;
@iljs 

Тут надо узнать у дизайн ребят как он должен выглядеть? И нужен ли в этом пакете )

2024-05-13 13:59 UTC, iljs commented on packages/sdds-serv/api/sdds-serv.api.md
> +contentLeft?: string | number | boolean | ReactFragment | ReactPortal | ReactElement<any, string | JSXElementConstructor<any>> | FunctionComponent<any> | ComponentClass<any, any> | null | undefined;
fixed

2024-05-14 09:51 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/TextField/TextField.tsx
> +            const handleOnKeyDown = (event: ChangeEvent<HTMLInputElement> & KeyboardEvent<HTMLInputElement>) => {
@iljs 

А почему в этой прки изменения по textfield?

2024-05-14 09:54 UTC, Yakutoc commented on cypress/snapshots/b2c/components/Slider/Slider.component-test.tsx/plasma-web Slider -- _disabled.snap.png
<img width="514" alt="Screenshot 2024-05-14 at 16 53 19" src="https://github.com/salute-developers/plasma/assets/2895992/4b9115ed-2082-4bec-8863-31d16ad4ed43">

А такой кейс будет в новой версии?

2024-05-14 10:29 UTC, iljs commented on cypress/snapshots/b2c/components/Slider/Slider.component-test.tsx/plasma-web Slider -- _disabled.snap.png
не понял

2024-05-14 11:26 UTC, shuga2704 requested changes

2024-05-14 17:34 UTC, iljs commented on packages/plasma-new-hope/src/components/Slider/components/Single/Single.types.ts
No

2024-05-14 19:42 UTC, iljs commented on packages/plasma-new-hope/src/components/Slider/components/Double/Double.types.ts
> +    ariaLabel?: string[];
Да, все верно

2024-05-14 19:42 UTC, iljs commented on packages/plasma-new-hope/src/components/Slider/components/Double/Double.types.ts
> +    ariaLabel?: string[];
Ярлык для левого и правого ползунка

2024-05-14 19:43 UTC, iljs commented on packages/plasma-new-hope/src/components/Slider/ui/Handle/Handle.tsx
> +        const lastOnChangeValue = useRef<number>();
нет смысла делать его изначально, а в событии inDrag оно поменяется

2024-05-16 05:21 UTC, Yakutoc commented on packages/plasma-b2c/src/components/Slider/Slider.component-test.tsx
> +../../../../plasma-web/src/components/Slider/Slider.component-test.tsx
а почему на web ссылается?

@neretin-trike @iljs может сделаем чтобы тест для b2c был свой?

2024-05-16 07:12 UTC, Yakutoc approved these changes

2024-05-16 09:49 UTC, shuga2704 approved these changes

2024-05-20 07:06 UTC, neretin-trike commented on packages/plasma-b2c/src/components/Slider/Slider.component-test.tsx
> +../../../../plasma-web/src/components/Slider/Slider.component-test.tsx
да пока можно так оставить я считаю.  Но вообще уже надо определиться, как и где мы храним тесты

2024-05-20 07:23 UTC, neretin-trike approved these changes

2024-05-23 19:52 UTC, merged