Accordion Component
salute-developers/plasma pull request #1223
Opened 2024-05-29 12:55 UTC by iljs

### Поставка компонента Accordion

Новый компонент Accordion поставляется в web/b2c

### What/why changed

Новый компонент Accordion поставляется в web/b2c

2024-05-30 12:59 UTC, luizasok approved these changes

2024-05-31 12:08 UTC, TitanKuzmich commented
pin с  circle не работает почему-то
![image](https://github.com/salute-developers/plasma/assets/40370966/ef37e576-0978-4273-b7fd-c253afa1f8a2)
Посмотри пожалуйста

2024-05-31 12:09 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.styles.ts
> +    padding-left: var(${tokens.accordionItemPaddingLeft});
Можем это объединить в один padding?

2024-05-31 12:39 UTC, iljs commented on packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.styles.ts
> +    padding-left: var(${tokens.accordionItemPaddingLeft});
Тут нет, там в view:clear эти левые и правые паддинги убираются

2024-05-31 13:35 UTC, TitanKuzmich commented on packages/plasma-b2c/src/components/Accordion/Accordion.config.ts
> +                ${accordionTokens.accordionItemPaddingLeft}: 0rem !important;
Можем избавиться от important
Навешивай на рут класс (например "clear-view") а затем в файлике сайза добавь стили в этот класс с обнулением паддингов. В целом можно сделать и через два токена 
```
accordionItemPadding: 1.0625rem 1.25rem;
accordionItemPaddingClear: 1.0625rem 0;
```

2024-05-31 13:36 UTC, TitanKuzmich commented on packages/plasma-b2c/src/components/Accordion/Accordion.config.ts
> +                ${accordionTokens.accordionItemPaddingLeft}: 0rem !important;
Тогда эти токены уйдут из view

2024-06-04 07:14 UTC, Yeti-or commented
в сторибке не очень

Давайте добавим зачем нужен этот компонент
и скриншот с ним

<img width="555" alt="Screenshot 2024-06-04 at 10 03 22" src="https://github.com/salute-developers/plasma/assets/1813468/b104108e-5ce6-4295-a92c-fe7fb4389d3c">



<img width="235" alt="Screenshot 2024-06-04 at 10 03 03" src="https://github.com/salute-developers/plasma/assets/1813468/2c85418c-805d-4aba-aae9-50868a128092">

2024-06-04 07:16 UTC, Yeti-or reviewed
Еще вопрос мы не хотим чтобы аккордеон умел иметь только одну открытую секцию? типа одну открыли остальные закрылись?


И Еще вопрос мы пока добавляем только в web/b2c?
Или оно уже может ехать в caldera-online / sdds-serv? 

сс @luizasok

2024-06-04 07:16 UTC, Yeti-or commented on packages/plasma-b2c/src/components/Accordion/Accordion.config.ts
> +                ${accordionTokens.accordionItemPaddingLeft}: 0rem !important;
Мне кажется нам такие кейсы нужно учитывать в ядре =/
https://github.com/salute-developers/plasma/issues/1230

И по мойму я пытался обойти похожую проблему:
https://github.com/salute-developers/plasma/blob/dev/packages/plasma-b2c/src/components/TextField/TextField.config.ts#L322

и возможно это все про отсутствие intersections в конфиге
сс @neretin-trike @shuga2704

2024-06-04 07:16 UTC, Yeti-or commented on packages/plasma-b2c/src/components/Accordion/Accordion.stories.tsx
> +            options: ['arrow', 'sign', 'clear'],
А у нас по дизайну не может быть такого что тут будет кастомная иконка ?
и второй вопрос а не может ли быть она слева а не справа?

2024-06-04 07:16 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/Accordion/Accordion.types.ts
> +     * Тип аккардиона
Оно по русски точно так пишется? =)

2024-06-04 07:19 UTC, iljs commented on packages/plasma-b2c/src/components/Accordion/Accordion.stories.tsx
> +            options: ['arrow', 'sign', 'clear'],
Если тип clear, то в left и right content можешь добавить любую кнопку какую хочешь

2024-06-04 07:21 UTC, iljs commented on packages/plasma-new-hope/src/components/Accordion/Accordion.types.ts
> +     * Тип аккардиона
Ups

2024-06-05 09:08 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.types.ts
> +    updateValue?: (index?: number, value?: boolean) => void;
Добавь комменты, что это за свойства

2024-06-05 09:10 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Accordion/utils/index.ts
> +};
Мы точно не хотим options-like апи как в дропдауне
Потому что ничего комплексного в item не идет, по сути текст

2024-06-05 09:11 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Accordion/variations/_size/tokens.json
> +    { "name": "typography", "type": "enum", "value": "typo:body" }
Точно эти токены идут?

2024-06-05 09:13 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Accordion/Accordion.config.ts
> +                ${accordionTokens.accordionWidth}: 20rem;
Этот токен не должен в size лежать?

2024-06-05 09:14 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Accordion/Accordion.stories.tsx
> +    argTypes: { ...disableProps(['text']) },
Сторя одна, можно наверх вынести

2024-06-05 11:19 UTC, TitanKuzmich approved these changes

2024-06-05 12:04 UTC, shuga2704 requested changes

2024-06-05 14:01 UTC, iljs commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Accordion/Accordion.config.ts
> +                ${accordionTokens.accordionItemTextLineHeight}: var(--plasma-typo-body-xs-line-height);
они одинаковые

2024-06-05 14:02 UTC, iljs commented on packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.types.ts
> +    pin?: Pin;
Аналогия из Button

2024-06-05 14:03 UTC, iljs commented on packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.tsx
> +        setShow(value);
если пропс обновляется из вне

2024-06-05 14:03 UTC, iljs commented on packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.tsx
> +    const [leftPadding, setLeftPadding] = useState<string | number | null>();
В теории ширина left content может меняться

2024-06-05 14:05 UTC, iljs commented on packages/plasma-new-hope/src/components/Accordion/Accordion.tsx
> +            const [activeIndex, setActiveIndex] = useState<number | undefined>();
В любом случае undefined нужен, так как defaultActiveIndex не обязательный и может быть undefined. Незачем все усложнять )

2024-06-06 07:41 UTC, neretin-trike commented on packages/plasma-b2c/src/components/Accordion/Accordion.tsx
> + * Cell
а описание релеватное?

2024-06-06 07:42 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Accordion/Accordion.tokens.ts
> +    accordionDisabled: '--plasma-accordion-disabled',
кажется префикс `--plasma-` не нужен

2024-06-06 07:44 UTC, neretin-trike commented on packages/plasma-web/src/components/Accordion/Accordion.stories.tsx
> +        pin: {
нужно здесь и в остальных сторях этот пропс выпилить

2024-06-10 17:10 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.tsx
> +    const [isOpen, setShow] = useState(value);
setShow тож поменяй

2024-06-10 17:12 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Accordion/Accordion.types.ts
> +     * Функция при открытии или закрытии элемента аккордеона
```suggestion
     * Коллбэк при открытии или закрытии элемента аккордеона
```

2024-06-10 17:13 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Accordion/ui/AccordionItem/AccordionItem.tsx
> +    const showedBody = isOpen ? classes.accordionItemShowBody : undefined;
`const openedBodyClass`

2024-06-11 14:01 UTC, shuga2704 approved these changes

2024-06-17 08:24 UTC, closed without merging