feat(website): add page colors
salute-developers/plasma pull request #1266
Opened 2024-06-26 05:03 UTC by iljs

### Страница с палитрой

2024-07-01 16:47 UTC, shuga2704 requested changes

2024-07-01 16:47 UTC, shuga2704 commented on website/plasma-website/components/colors/Pallete.tsx
> +    useLayoutEffect(() => {
useLayoutEffect не работает на сервере, консолька ругается

2024-07-05 15:29 UTC, shuga2704 requested changes

2024-07-05 15:29 UTC, shuga2704 commented on website/plasma-website/components/palette/PaletteColorPage.tsx
Нужно выносить хендлеры в тело компонента, это касается не только текущего компонента

2024-07-05 15:29 UTC, shuga2704 commented on website/plasma-website/components/palette/PaletteColorPage.tsx
> +const checkColor = (color: string, colorCode: string) => {
Давай вынесем в утилиту отдельную

2024-07-08 05:45 UTC, Yakutoc commented
@iljs Добавь пожалуйста в описание было/стало скриншоты. В твоем случае только стало )

2024-07-08 07:52 UTC, iljs commented on website/plasma-website/components/palette/PaletteColorPage.tsx
> +    query: string | string[] | undefined;
Нужен, он из роутера идет с такими типами

2024-07-08 07:58 UTC, iljs commented on website/plasma-website/components/palette/GradientScroll.tsx
> +                scrollRef.current && scrollRef.current.removeEventListener('scroll', handlerScroll, false);
ts ругается, хз почему

2024-07-08 08:36 UTC, iljs commented on website/plasma-website/components/palette/GradientScroll.tsx
> +    const [scrollPosition, setScrollPosition] = useState({ scrollTop: 0, scrollHeight: 0, clientHeight: 0 });
ну а вдруг поменятеся размер экрана и чтобы ничего не плыло в это время

Кол-во рендеров в любом случае не меняется так как изменятся 1 стейт

2024-07-08 20:36 UTC, shuga2704 commented on website/plasma-website/components/palette/GradientScroll.tsx
> +    const heightAllScroll = scrollPosition.clientHeight - 212;
Значение 212 давай вынесем наверх в константы

2024-07-08 20:38 UTC, shuga2704 commented on website/plasma-website/components/palette/GradientScroll.tsx
> +                scrollRef.current && scrollRef.current.removeEventListener('scroll', handlerScroll);
Тернарники только в jsx, не забывай)

2024-07-08 20:40 UTC, shuga2704 commented on website/plasma-website/components/palette/GradientScroll.tsx
> +    const [scrollPosition, setScrollPosition] = useState({ scrollTop: 0, scrollHeight: 0, clientHeight: 0 });
Если поменяется размер экрана, то ничего не произойдет, т.к. нету обработчика на изменение экрана (да и не нужен он тут).
`scrollHeight` и `clientHeight` не нужны в стейте потому, что это обычные значения, которые лежат в `scrollRef.current`. Ты их можешь просто оставить в теле компонента и все.

2024-07-09 04:28 UTC, Yakutoc commented on website/plasma-website/components/palette/GradientScroll.tsx
> +    height: calc(100vh - 208px);
@iljs 
px to rem
почему именно 208? Может вынесем в константу или переменную?

2024-07-09 04:33 UTC, Yakutoc commented on website/plasma-website/components/palette/PaletteItem.tsx
> +    h: number;
@iljs 
что такое `h`?

2024-07-09 04:38 UTC, Yakutoc commented on website/plasma-website/package.json
> +    "@salutejs/plasma-colors": "0.13.0",
@iljs 

А за чем и в `dependencies`, и `devDependencies` ставить пакет `@salutejs/plasma-colors`?

2024-07-09 04:40 UTC, Yakutoc commented on website/plasma-website/utils/hexToHSL.ts
> +export const hexToHSL = (hex: string): number[] => {
@iljs Тут явно нужны комментарии что/зачем/почему

Можно как отдельной задачей.

2024-07-09 10:12 UTC, iljs commented on website/plasma-website/components/palette/PaletteItem.tsx
> +    h: number;
Значение H из цветового диапозона HSL

2024-07-09 10:20 UTC, Yakutoc commented on website/plasma-website/components/palette/Header.tsx
> +            <HeaderText className="hoverHeader">←</HeaderText>
@iljs Для иконки использовать 

`import { IconArrowLeft, IconArrowUp } from '@salutejs/plasma-icons';`

2024-07-09 11:05 UTC, shuga2704 commented on website/plasma-website/components/palette/GradientScroll.tsx
> +    const fixPadding = 212;
Подобные константы лучше выносить за пределы компонента наружу, и писать их апперкейсом

2024-07-09 11:05 UTC, shuga2704 commented on website/plasma-website/components/palette/GradientScroll.tsx
> +            return () => {
Давай перед ретурном пустую строчку вставим чтобы читабельнее было

2024-07-09 11:11 UTC, shuga2704 commented on website/plasma-website/components/palette/PaletteColorPage.tsx
> +    const widthText = 570;
Тож самое про вынос констант

2024-07-09 11:14 UTC, Yakutoc commented on website/plasma-website/pages/palette/[...query].tsx
> +                    {router.query.query?.[1]} {router.query.query?.[3]}
@iljs Во что это превратиться? Может сделаем именованными? я про `router.query.query?.[1]`

2024-07-09 11:14 UTC, Yakutoc approved these changes

2024-07-09 14:14 UTC, shuga2704 approved these changes

2024-07-09 19:56 UTC, merged