plasma-*: add `Price` component
salute-developers/plasma pull request #1307
Opened 2024-07-17 08:45 UTC by denivladislav

### Price, Portal

- компонент `Price` добавлен в `plasma-new-hope`, портирован в `plasma-{web, b2c}`, `sdds-{serv, dfa}`
- для `Price` обновлены тесты и документация
- исправлена ошибка отсутствующего `PropsTable` в документации `Portal`

### What/why changed
- В компонент `Price` добавлено свойство `locale`. Добавлена индийская рупия `inr`. Также в связи с новым именованием, было добавлено свойство `stroked`, а старое свойство `stroke` помечено как `deprecated`. В остальном компонент перенесен без изменений. 

### Before / After (Portal)

До:
<img width="1723" alt="example" src="https://github.com/user-attachments/assets/4eb8b5ba-cc0e-46be-908c-263352a23cb8">

После:
<img width="1595" alt="after" src="https://github.com/user-attachments/assets/1ec5e175-f6dd-4aac-a48d-908dc3488279">

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/caldera-online@0.70.0-canary.1307.10059399396.0
  npm install @salutejs/plasma-asdk@0.113.0-canary.1307.10059399396.0
  npm install @salutejs/plasma-b2c@1.355.0-canary.1307.10059399396.0
  npm install @salutejs/plasma-new-hope@0.110.0-canary.1307.10059399396.0
  npm install @salutejs/plasma-ui@1.260.0-canary.1307.10059399396.0
  npm install @salutejs/plasma-web@1.356.0-canary.1307.10059399396.0
  npm install @salutejs/sdds-dfa@0.83.0-canary.1307.10059399396.0
  npm install @salutejs/sdds-serv@0.84.0-canary.1307.10059399396.0
  # or 
  yarn add @salutejs/caldera-online@0.70.0-canary.1307.10059399396.0
  yarn add @salutejs/plasma-asdk@0.113.0-canary.1307.10059399396.0
  yarn add @salutejs/plasma-b2c@1.355.0-canary.1307.10059399396.0
  yarn add @salutejs/plasma-new-hope@0.110.0-canary.1307.10059399396.0
  yarn add @salutejs/plasma-ui@1.260.0-canary.1307.10059399396.0
  yarn add @salutejs/plasma-web@1.356.0-canary.1307.10059399396.0
  yarn add @salutejs/sdds-dfa@0.83.0-canary.1307.10059399396.0
  yarn add @salutejs/sdds-serv@0.84.0-canary.1307.10059399396.0
  ```
</details>

2024-07-18 14:08 UTC, denivladislav commented on packages/plasma-new-hope/src/components/Price/index.ts
> +export { priceRoot, priceConfig } from './Price';
Не отдавал пропсы наружу:
https://mm.sberdevices.ru/sberdevices/pl/9ku4wxxnhtbetyht6ohm4bzsjr

2024-07-19 09:56 UTC, shuga2704 requested changes

2024-07-19 09:56 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Price/Price.types.ts
Давай депрекейтед пропс оставлять в самом низу, чтобы не путались с обычными пропсами

2024-07-19 09:56 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Price/Price.types.ts
> +    periodicity?: '/ день' | '/ неделя' | '/ месяц' | '/ год' | React.ReactElement;
Может лучше сделать periodicity?: React.ReactNode? Раз уж мы им позволяем это делать и сейчас

2024-07-19 11:49 UTC, denivladislav commented on packages/plasma-new-hope/src/components/Price/Price.tsx
> +                <Root view={view} ref={outerRootRef} className={cx(strokedClass, className)} {...rest}>
здесь сделал без лишней обёртки `StyledPrice`

2024-07-19 12:19 UTC, denivladislav commented on packages/plasma-new-hope/src/components/Price/Price.types.ts
ок, подвинул вниз

2024-07-19 12:19 UTC, denivladislav commented on packages/plasma-new-hope/src/components/Price/Price.types.ts
> +    periodicity?: '/ день' | '/ неделя' | '/ месяц' | '/ год' | React.ReactElement;
сделал

2024-07-19 12:23 UTC, shuga2704 approved these changes

2024-07-22 04:57 UTC, Yakutoc commented on cypress/snapshots/b2c/components/Price/Price.component-test.tsx/plasma-b2c Price -- _currency.snap.png
@denivladislav Добавь пожалуйста с индийской рупией пример

2024-07-22 05:02 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Price/Price.types.ts
> +    currency?: 'rub' | 'usd' | 'eur';
@denivladislav А мы можем добавить рупии?

2024-07-22 05:04 UTC, Yakutoc approved these changes

2024-07-22 07:19 UTC, denivladislav commented on packages/plasma-new-hope/src/components/Price/Price.types.ts
> +    currency?: 'rub' | 'usd' | 'eur';
Добавил

2024-07-22 07:19 UTC, denivladislav commented on cypress/snapshots/b2c/components/Price/Price.component-test.tsx/plasma-b2c Price -- _currency.snap.png
Добавил

2024-07-23 13:49 UTC, merged