plasma-*: Add Component Breadcrumbs
salute-developers/plasma pull request #1310
Opened 2024-07-18 10:16 UTC by iljs

### Add Component Breadcrumbs

Компонент хлебных крошек

### What/why changed

-

2024-07-18 11:51 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Breadcrumbs/Breadcrumbs.types.ts
> +    wrap?: boolean;
@iljs Как будет обработан длинный текст и максимальная ширина?

2024-07-25 11:36 UTC, luizasok approved these changes

2024-07-26 08:13 UTC, denivladislav commented
В `sdds-dfa` не нужно добавлять в итоге?

2024-07-26 08:37 UTC, denivladislav commented on packages/plasma-new-hope/src/components/Breadcrumbs/Breadcrumbs.tsx
> +                        return item;
Предлагаю тут просто распакоуку: {...itemsWithSeparator}

2024-07-26 09:31 UTC, denivladislav commented on packages/plasma-b2c/src/components/Breadcrumbs/Breadcrumbs.tsx
> + * Accordion
Не то название компонента

2024-07-26 09:33 UTC, denivladislav commented on packages/plasma-new-hope/src/components/Breadcrumbs/utils/index.tsx
> +    switch (size) {
подскажи плиз, получается, что 
когда  `size=s`, то иконка размера `xs`,
а когда  `size=xs`, то иконка будет размера `s`?

и в целом тут тогда можно обработать только кейсы, где нужен `xs`, а остальное попадает в `default`

2024-07-26 09:36 UTC, denivladislav commented on packages/plasma-new-hope/src/components/Breadcrumbs/Breadcrumbs.types.ts
> +    showItems?: number;
можно дефолтное значение указать

2024-07-26 09:39 UTC, denivladislav commented on packages/plasma-new-hope/src/components/Breadcrumbs/Breadcrumbs.tsx
> +        ({ view, size, separator, items, showItems = items.length, className }, outerRootRef) => {
тут получается `restProps` никуда не прокидываются?

2024-07-26 09:43 UTC, iljs commented on packages/plasma-new-hope/src/components/Breadcrumbs/utils/index.tsx
> +    switch (size) {
да, все в соответсвии с дизайном, а дефолт для ts.нужен

2024-07-26 09:44 UTC, iljs commented on packages/plasma-new-hope/src/components/Breadcrumbs/Breadcrumbs.types.ts
> +    showItems?: number;
по дефолту просто выводятся все, без шортера

2024-07-26 09:47 UTC, iljs commented on packages/plasma-new-hope/src/components/Breadcrumbs/Breadcrumbs.tsx
> +        ({ view, size, separator, items, showItems = items.length, className }, outerRootRef) => {
yes

2024-07-26 11:58 UTC, denivladislav approved these changes

2024-07-29 05:59 UTC, Yakutoc commented
@iljs 

Давай сразу добавим пожалуйста `Breadcrumbs.template-doc.mdx` для документации на уровне new-hope

2024-07-29 06:05 UTC, Yakutoc commented on packages/plasma-b2c/src/components/Breadcrumbs/Breadcrumbs.stories.tsx
> +        return <Breadcrumbs {...args} />;
@iljs А зачем такая запись? заводить `args` и потом `spread`?  

```tsx
    render: (props: BreadcrumbsProps) => < Breadcrumbs {...props} />,
```

2024-07-29 06:29 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Breadcrumbs/Breadcrumbs.types.ts
> +           * Элемент крошки
@iljs 

Элемент или заголовок?

2024-07-29 06:29 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Breadcrumbs/Breadcrumbs.types.ts
> +           * Функция рендера элемента)
Лишняя скобка после слова элемента

2024-07-29 06:30 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Breadcrumbs/Breadcrumbs.types.ts
> +     * Стандартный размер текста элементов
> Стандартный размер текста элементов  

или в > Стандартный размер текста в элементе ? 

Какой смысл хотим передать?

2024-07-29 06:32 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Breadcrumbs/Breadcrumbs.types.ts
> +     * Элементы крошек
ИМХО тут как раз тот случай, когда лучше использовать английский термин `Breadcrumbs`

2024-07-29 06:33 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Breadcrumbs/Breadcrumbs.types.ts
> +     * Количество показываемых элементов - все оставльные сокращаются
очепятка 

`оставльные` -> остальные

2024-07-29 06:34 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Breadcrumbs/README.md
> +ТАКЖЕ: Можно указать кол-во видимых элементов через параметр showItems. ShowItems: если указано четное число, напрмер 2 - то распределяется навномерно по 1 с каждой стороны. Если нечетное, напрмер 3
навномерно -> равномерно

2024-07-29 06:39 UTC, Yakutoc commented on website/plasma-web-docs/docs/components/Breadcrumbs.mdx
> +<StorybookLink name="Breadcrumbs" />
Давай уберем пожалуйста - не используем сейчас этот функционал.

2024-07-29 06:40 UTC, Yakutoc commented on website/plasma-web-docs/docs/components/Breadcrumbs.mdx
> +# Использование с укоротителем
Давай заменим на английский вариант )

2024-07-29 06:45 UTC, Yakutoc commented on website/plasma-web-docs/docs/components/Breadcrumbs.mdx
> +# Использование с укоротителем
Или как сократить текст, или как кастомизировать элемент компонента

2024-07-29 06:47 UTC, Yakutoc commented
@iljs Ты проверял в codesandbox canary версию?)

2024-07-30 07:21 UTC, Yakutoc commented on website/plasma-web-docs/docs/components/Breadcrumbs.mdx
> +import { PropsTable, Description } from '@site/src/components';
`Description` - не увидел где используется?

2024-07-30 07:26 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Breadcrumbs/utils/index.tsx
> +                <StyledLink tabIndex={0} href={item.href} isHref={!!item.href}>
Давай пожалуйста через `Boolean(item.href)` - в проекте стараемся каст делать через обертку.

2024-07-31 08:47 UTC, Yakutoc requested changes

2024-07-31 08:47 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Breadcrumbs/Breadcrumbs.template-doc.mdx
> +import { Breadcrumbs } from '@salutejs/plasma-web';
@iljs Посмотри пожалуйста как правильно делается template 

- нужно использовать placeholder
- нужно ставить экранирование

2024-07-31 08:47 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Breadcrumbs/Breadcrumbs.template-doc.mdx
> +        <div style={{"flexDirection": 'column'}}>
@iljs Здесь должно быть экранирование `\{"flexDirection": 'column'}}`

2024-07-31 08:47 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Breadcrumbs/Breadcrumbs.template-doc.mdx
> +import { Breadcrumbs, Dropdown } from '@salutejs/plasma-web';
нужен placeholder - `@salutejs/{{ package }}`

2024-08-05 10:21 UTC, neretin-trike commented on packages/sdds-serv/src/components/Breadcrumbs/Breadcrumbs.config.ts
> +                ${breadcrumbsTokens.breadcrumbsOpacity}: 0.4;
обычно мы такой токен выделяем в пропс disabled

2024-08-05 11:01 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Breadcrumbs/utils/index.tsx
> +        items.map((item: BreadcrumbsItem) => {
давай для чуть лучшей читаемости в отдельную переменную выделим

2024-08-05 11:02 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Breadcrumbs/README.md
> +Структура файлов:
а этот файл здесь нужен?

2024-08-05 11:20 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Breadcrumbs/Breadcrumbs.types.ts
> +    size?: 'xs' | 's' | 'm' | 'l';
тут string должен быть

2024-08-05 11:20 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Breadcrumbs/ui/BreadcrumbShorter/BreadcrumbShorter.tsx
> +        if (event.keyCode === 13) {
у нас нет еманов для этого?

2024-08-05 11:21 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Breadcrumbs/Breadcrumbs.tsx
> +                    })}
можно чуть упростить:

```ts
  {itemsWithSeparator.map((item) => item)}
``

2024-08-05 11:22 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Breadcrumbs/ui/BreadcrumbShorter/BreadcrumbShorter.tsx
> +                    })}
тут можно немного упростить

2024-08-05 20:23 UTC, iljs commented on packages/plasma-new-hope/src/components/Breadcrumbs/ui/BreadcrumbShorter/BreadcrumbShorter.tsx
> +        if (event.keyCode === 13) {
вроде нет

2024-08-06 08:18 UTC, neretin-trike approved these changes

2024-08-06 21:25 UTC, merged