feat(plasma-{web,b2c,new-hope}, sdds-{serv,dfa}): add required variation to TextArea & TextField
salute-developers/plasma pull request #1352
Opened 2024-08-12 20:37 UTC by vadim-kudr

### Новые пропсы required & requiredAlign в TextArea & TextField

так же обновлены:
* скриншоты
* документация

2024-08-20 09:23 UTC, iljs commented on cypress/snapshots/b2c/components/TextArea/TextArea.component-test.tsx/plasma-b2c TextArea -- _size empty.snap.png
А почему поменялась заливка и правильное ли это поведение?

2024-08-20 09:35 UTC, iljs commented on packages/plasma-new-hope/src/components/TextField/TextField.tsx
> +                            {required && <StyledIndicator className={cx('placement-outer', requiredAlignClass)} />}
Давай классы будем прописывать в файле TextField.tokens.ts

2024-08-20 09:35 UTC, iljs commented on packages/plasma-new-hope/src/components/TextField/TextField.tsx
> +                            <StyledIndicator className={cx('placement-inner', requiredAlignClass)} />
Тут тоже

2024-09-03 06:38 UTC, shuga2704 commented
Нужно обновить дискрипшин прки (заменить `requiredAlign` на `requiredPlacement`).

2024-09-03 06:49 UTC, shuga2704 requested changes

2024-09-03 06:49 UTC, shuga2704 commented on cypress/snapshots/b2c/components/Autocomplete/Autocomplete.component-test.tsx/plasma-b2c Autocomplete -- prop size.snap.png
Появился отступ у лейбла, так и надо?

2024-09-03 06:49 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
Мы вроде решили делать это через union?

2024-09-03 06:49 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/TextField/TextField.styles.ts
> +    &.placement-outer {
Класснеймы нужно выносить в `classes` в файле `.tokens`

2024-09-03 06:49 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/TextField/TextField.template-doc.mdx
> +С помощью свойства `enumarationType` можно вводить элементы как теги.
```suggestion
С помощью свойства `enumerationType` можно вводить элементы как теги.
```

2024-09-04 02:07 UTC, vadim-kudr commented on cypress/snapshots/b2c/components/Autocomplete/Autocomplete.component-test.tsx/plasma-b2c Autocomplete -- prop size.snap.png
скорее всего сильно старые правки были, я когда-то левые ключи скопировал

2024-09-04 02:51 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
обновил

2024-09-04 02:51 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/TextField/TextField.styles.ts
> +    &.placement-outer {
обновлено

2024-09-04 02:52 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/TextField/TextField.template-doc.mdx
> +С помощью свойства `enumarationType` можно вводить элементы как теги.
не понял, поправил нейминг

2024-09-04 08:30 UTC, shuga2704 approved these changes

2024-09-04 08:34 UTC, iljs approved these changes

2024-09-04 09:28 UTC, merged