Form story
salute-developers/plasma pull request #1421
Opened 2024-09-05 10:22 UTC by iljs

### Form story

- Добавлена Form Story

### What/why changed

2024-09-09 07:24 UTC, Yakutoc commented on packages/plasma-new-hope/src/utils/setRefList.ts
> +export function setRef<T>(val: T, ...refs: MutableRefList<T>): void {
@iljs У нас что-то подобное было в `packages/plasma-core/src/utils/setRef.ts` 

Посмотри в эту сторону пожалуйста

2024-09-09 07:42 UTC, iljs commented on packages/plasma-new-hope/src/utils/setRefList.ts
> +export function setRef<T>(val: T, ...refs: MutableRefList<T>): void {
Там чуть другое, по-другому сейчас назову

2024-09-16 07:58 UTC, neretin-trike commented on packages/plasma-new-hope/src/hooks/useForm.ts
> +        initData(formRef, defaultValues);
на каждый рендер должен вызываться?

2024-09-16 07:58 UTC, neretin-trike commented on packages/plasma-new-hope/src/hooks/useForm.ts
> +        for (let i = 0; i < items.length; i++) {
мб items.foreach?

2024-09-16 08:02 UTC, neretin-trike commented on packages/plasma-new-hope/src/hooks/useForm.ts
> +    if (ref.current) {
тут можно инверсию сделать !ref.current

2024-09-16 08:10 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Form/Form.stories.tsx
> +import { TextArea } from '../TextArea/TextArea'; // TextArea.tsx 120 строка, не работает из-за некорректного ref
ещё нужен?

2024-09-16 08:16 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Slider/components/Single/Single.tsx
> +    value = min,
нужно будет убрать

2024-09-16 08:16 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Form/Form.stories.tsx
> +        <form onSubmit={handleSubmit(onSubmit)} style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
нужно будет добавить пример с нативным примером без нашего хука

2024-09-16 08:26 UTC, neretin-trike commented on packages/plasma-web/api/plasma-web.api.md
> +}> & ((SingleSliderProps & RefAttributes<HTMLDivElement>) | (Omit<DoubleSliderProps, "value"> & {
добавить доку с описанием примеров работы с хуками и без

2024-09-16 08:31 UTC, neretin-trike commented on packages/plasma-new-hope/src/hooks/useForm.ts
> +export const useFormPlasma = (onSubmit: (data: DataType) => void, defaultValues: DataType) => {
кажется не надо использовать в названии Plasma

2024-09-16 08:36 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Slider/components/Double/Double.tsx
> +    }, [innerRefSecond]);
=> [ ]

2024-09-17 08:45 UTC, TitanKuzmich commented on packages/plasma-b2c/src/components/DatePicker/DatePicker.component-test.tsx
> +        cy.get('#demo input').first().realClick();
Для чего добавлен first?

2024-09-17 08:50 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/DatePicker/RangeDate/RangeDate.tsx
> +                    innerRefSecond.current.addEventListener('setInitValue', (e: Event) => {
Можем вынести в функцию куда-нибудь выше и в return делать removeEventListener

2024-09-17 08:53 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Slider/components/Double/Double.tsx
> +            innerRefSecond.current.addEventListener('setInitValue', (e: Event) => {
Так же как и в DataPicker вынеси в функцию

2024-09-17 08:55 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Slider/components/Single/Single.tsx
> +            }
Для чего тут повторно тот же коллбек привязывать к событию?

2024-09-18 05:18 UTC, Yakutoc commented on packages/plasma-new-hope/package.json
> +    "react-hook-form": "7.52.1",
А за чем нам это зависимость?

2024-09-18 05:19 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Slider/components/Single/Single.styles.ts
> +export const InputHidden = styled.input`
Может вынесем в корневой utils чтобы везде использовать и не дублировать в каждом компоненте?

2024-09-18 05:21 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Slider/components/Single/Single.tsx
>      onChange,
@iljs @neretin-trike Если я правильно понял, мы хотели внутри onChange сделать проверку на value чтобы изменить payload события?

2024-09-18 05:22 UTC, Yakutoc commented on packages/plasma-new-hope/src/hooks/useForm.ts
> +            if ((type === 'text' || type === 'textarea') && valideParams(name)) {
Договорились что перепишем блок или Switch case или плоский if

2024-09-18 05:23 UTC, Yakutoc commented on packages/plasma-new-hope/src/utils/setRefList.ts
> +export function mergeRefs<T>(...refs: MutableRefList<T>): RefCallback<T> {
у нас есть `packages/plasma-core/src/utils/setRef.ts` 

одинаковый фунционал или нет?

2024-09-18 05:28 UTC, Yakutoc commented
@iljs Короткое резюме что нужно добавить

### Документация c примерами

- [ ] использование с `form` без доп оберток и libs
- [ ] использование с нашим hook useFormPlasma (переименовать и убрать слово Plasma)
- [ ] использование в связке с `useForm (react-hook-form)` 
-----------
- [ ] в консоли не должно быть warn errors

2024-09-19 12:56 UTC, iljs commented on packages/plasma-new-hope/src/hooks/useForm.ts
> +        for (let i = 0; i < items.length; i++) {
теряется контекст result и типы

2024-09-19 13:12 UTC, iljs commented on packages/plasma-new-hope/src/utils/setRefList.ts
> +export function mergeRefs<T>(...refs: MutableRefList<T>): RefCallback<T> {
Разные, multiRef может принимать несколько рефок, там setRef просто исполняет рефку, если там функция

2024-09-19 13:17 UTC, iljs commented on packages/plasma-new-hope/package.json
> +    "react-hook-form": "7.52.1",
для примера работы

2024-09-27 11:41 UTC, Yakutoc commented on website/sdds-cs-docs/docs/form/UseForm.mdx
> +Для работы с формами в Plasma есть хук useForm, для инициализации стартоввых значений и сбора формы. Работает он на ref формы
@iljs 
> Для работы с формами в Plasma есть хук useForm, 

давай заменим на 

> Для работы с формами используйте hook useForm, 
потому что sdds != Plasma

2024-09-27 11:42 UTC, Yakutoc commented on website/sdds-cs-docs/docs/form/UseForm.mdx
> +Для работы с формами в Plasma есть хук useForm, для инициализации стартоввых значений и сбора формы. Работает он на ref формы
> стартоввых 

очепятка

2024-09-27 11:42 UTC, Yakutoc commented on website/sdds-cs-docs/docs/form/UseForm.mdx
> +1. Ref, которую надо встаавить в форму
@iljs 
> встаавить 

очепятка

2024-09-27 11:45 UTC, Yakutoc commented on website/sdds-dfa-docs/docs/form/NativeForm.mdx
> +Для работы с обычными формами можно использовать нативную реализацию.
@iljs 
> Для работы с обычными формами можно использовать нативную реализацию.

давай перепишем на 

> Для работы с простой формой( имеется ввиду html тег `<form>`) можно использовать следующий подход.

2024-09-27 11:48 UTC, Yakutoc commented on website/sdds-cs-docs/docs/form/UseForm.mdx
> +# Use Form
@iljs 

тогда уже `Hook useForm`

2024-09-27 11:52 UTC, Yakutoc commented on website/sdds-cs-docs/docs/form/UseForm.mdx
> +# Use Form
@iljs 

Для всех 3 сценариев один и тот же набор поддерживаемых компонентов? 

Если да то давай тогда сделаем страницу - "Поддерживаемые компоненты" и вынесем эту информацию туда  

И структура страниц будет такой

Работа с формой:   
-  Поддерживаемые компоненты
-  Html form
-  Hook useForm 
-  React hook form

2024-09-27 11:56 UTC, Yakutoc commented on packages/plasma-new-hope/package.json
> +    "react-hook-form": "7.52.1",
@iljs Но мы же это не будем поставлять? )

2024-09-27 12:29 UTC, vadim-kudr commented on packages/plasma-b2c/src/hooks/useForm.stories.tsx
> +const itemsRadiobox = [
radioboxItems, но не критично

2024-09-27 12:54 UTC, iljs commented on website/sdds-cs-docs/docs/form/UseForm.mdx
> +# Use Form
у нативки отсутсвует double slider и datepicker range

2024-09-27 13:35 UTC, vadim-kudr commented on packages/plasma-new-hope/package.json
> +    "react-hook-form": "7.52.1",
peerDeps?

2024-09-27 13:35 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/DatePicker/RangeDate/RangeDate.tsx
> +                        onChange={() => {}}
из lodash можно empty взять или вынести в переменную за компонентом `const empty = () => {};`

2024-09-27 13:35 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/DatePicker/SingleDate/SingleDate.tsx
> +            }, [innerRef]);
useEffect у другие хуки не работают с ref в deps 🤔

2024-09-27 13:35 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Slider/components/Double/Double.tsx
> +    }, [innerRefSecond]);
имхо, можно `[]` оставить

2024-09-27 13:35 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Slider/components/Double/Double.tsx
> +                onChange={() => {}}
аналогично выше

2024-09-27 13:35 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Slider/components/DoubleUncontrolled/DoubleUncontrolled.tsx
> +    const sortValues = (values: number[]) => {
я бы вынес выше и добавил пропсы min/max, чтобы отвязаться от props

2024-09-27 13:35 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Slider/components/DoubleUncontrolled/DoubleUncontrolled.tsx
> +    const onChangeHandle = (values: number[]) => {
тут почти все без useCallback и передается дальше в компоненты 🤔

2024-09-27 13:35 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Slider/components/DoubleUncontrolled/DoubleUncontrolled.tsx
> +    return value ? (
имхо 

```
if (value) {
  return (...);
}

return (
  ...
)
```

2024-09-27 13:35 UTC, vadim-kudr commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Form/Form.stories.tsx
> +        checkbox: 'checkobox',
checkobox

2024-09-27 13:35 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/DatePicker/RangeDate/RangeDate.tsx
> +            const innerRefFirst = useRef<HTMLInputElement>(null);
может и лично, но я бы так называл firstInnerRef, secondInnerRef

2024-09-27 13:35 UTC, vadim-kudr commented on packages/plasma-new-hope/src/hooks/useForm.ts
> +                const event = new Event('setInitValue');
к чему сокращения? `setInitialValue `

2024-09-27 13:35 UTC, vadim-kudr commented on packages/plasma-new-hope/src/hooks/useForm.ts
> +                if (item.checked) {
а если checked = false?

2024-09-27 13:35 UTC, vadim-kudr commented on website/plasma-web-docs/docs/form/ReactHookForm.mdx
> +    const datepickerrange = register('datepickerrange');
datepicker`R`ange

2024-09-29 20:02 UTC, iljs commented on packages/plasma-new-hope/src/components/Slider/components/DoubleUncontrolled/DoubleUncontrolled.tsx
> +    const sortValues = (values: number[]) => {
Там так не получиться

2024-09-29 20:05 UTC, iljs commented on packages/plasma-new-hope/src/hooks/useForm.ts
> +                if (item.checked) {
то пропускает, это же группа радиобоксов

2024-09-29 20:05 UTC, iljs commented on packages/plasma-new-hope/src/components/DatePicker/RangeDate/RangeDate.tsx
> +            const innerRefFirst = useRef<HTMLInputElement>(null);
-

2024-09-29 20:24 UTC, iljs commented on packages/plasma-new-hope/src/components/DatePicker/RangeDate/RangeDate.tsx
> +                        onChange={() => {}}
а смысл, так больше строк получается все равно )

2024-09-29 20:24 UTC, iljs commented on packages/plasma-new-hope/src/components/Slider/components/DoubleUncontrolled/DoubleUncontrolled.tsx
> +    const sortValues = (values: number[]) => {
Сами переменных не будет уже в props, а их надо вставить дальше, если это controlled вариант

2024-09-30 06:20 UTC, Yakutoc commented on website/plasma-b2c-docs/docs/form/ReactHookForm.mdx
> +Также мы поддерживаем работу с ReactHookForm
@iljs 

> Также мы поддерживаем работу с ReactHookForm

на 

> Компоненты поддерживают работу с библиотекой `react-hook-form`

2024-09-30 06:24 UTC, Yakutoc commented on website/plasma-b2c-docs/docs/form/ReactHookForm.mdx
> +В DatePicker и в DatePickerRange лучше напрямую передавать `name` и `onChange`, так как типы передаваемые из register в параметрах `min` и `max` несовместимы.
@iljs > В DatePicker и в DatePickerRange  <--- уберем и так есть заголовок 

Свойство `name` и `onChange` лучше передавать напрямую, так как типы передаваемые из register в параметрах `min` и `max` несовместимы.

2024-09-30 07:37 UTC, vadim-kudr approved these changes

2024-09-30 07:39 UTC, neretin-trike commented on packages/plasma-b2c/src/hooks/index.ts
> +export { useFormState } from '@salutejs/plasma-new-hope/styled-components';
а почему именно из styled-components импорты?

2024-09-30 07:41 UTC, neretin-trike commented
кажется нужны отступы

<img width="754" alt="image" src="https://github.com/user-attachments/assets/b79ede70-24c7-4a64-984a-3280a2a000c9">

2024-09-30 07:43 UTC, neretin-trike commented on packages/plasma-b2c/src/hooks/useForm.stories.tsx
> +};
@Yakutoc @shuga2704 а мы же вроде проговаривали, что должны добавить пример с `react-hook-form`?

2024-09-30 07:45 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/DatePicker/RangeDate/RangeDate.tsx
> +                onChange?.({
у нас принято вместо тернарников использовать `if` в таких случаях

2024-09-30 07:47 UTC, neretin-trike commented on website/sdds-serv-docs/package.json
> +    "react-hook-form": "7.53.0",
это точно должно быть dependencies, а не в devDependencies?

2024-09-30 08:50 UTC, neretin-trike commented
пример не работает

<img width="754" alt="image" src="https://github.com/user-attachments/assets/15075661-a5c2-4853-ae0e-aa879b945124">

2024-09-30 08:53 UTC, neretin-trike commented on packages/plasma-b2c/src/hooks/useForm.stories.tsx
> +        console.log(data);
мб имеет смысл это в story-action добавить?

2024-09-30 08:53 UTC, neretin-trike commented on packages/sdds-dfa/src/hooks/index.ts
> +export { useFormState } from '@salutejs/plasma-new-hope/styled-components';
здесь и в других библиотеках тот же вопрос - обязательно из styled-component импортировать?

2024-09-30 09:02 UTC, neretin-trike commented on website/sdds-serv-docs/docs/form/_category_.json
> +}
кажется, что весь этот раздел с формами надо добавить в scaffold

2024-09-30 09:03 UTC, neretin-trike commented on website/sdds-serv-docs/docs/form/UseForm.mdx
> +Для работы с формами используйте hook useForm, для инициализации стартовых значений и сбора формы. Работает он на ref формы
useForm => useFormState?

2024-09-30 09:05 UTC, neretin-trike commented
как-то странно выглядят textField и textArea в https://plasma.sberdevices.ru/pr/pr-1421/b2c/form/use-form/

<img width="583" alt="image" src="https://github.com/user-attachments/assets/a337411a-7e01-40f3-a40a-26d4e58d5839">

2024-09-30 09:05 UTC, neretin-trike commented on website/sdds-serv-docs/docs/form/UseForm.mdx
> +Для работы с формами используйте hook useForm, для инициализации стартовых значений и сбора формы. Работает он на ref формы
мб если это название используется, тогда везде нужно переименовать? В том числе и файлы

2024-09-30 09:15 UTC, iljs commented on packages/sdds-dfa/src/hooks/index.ts
> +export { useFormState } from '@salutejs/plasma-new-hope/styled-components';
Это только из new-hope

2024-09-30 09:15 UTC, iljs commented on packages/plasma-b2c/src/hooks/useForm.stories.tsx
> +};
он в доке
а тут чисто сторя с хуком

2024-09-30 09:16 UTC, iljs commented on packages/plasma-b2c/src/hooks/index.ts
> +export { useFormState } from '@salutejs/plasma-new-hope/styled-components';
Иначе возникает ошибка при тестах. Это только в new-hope

2024-09-30 09:27 UTC, neretin-trike commented on website/sdds-serv-docs/docs/form/UseForm.mdx
> +Для работы с формами используйте hook useForm, для инициализации стартовых значений и сбора формы. Работает он на ref формы
кстати а точно такое название хотим? Мб useFormData?

@shuga2704 @Yakutoc

2024-09-30 09:28 UTC, neretin-trike commented on website/sdds-serv-docs/docs/form/ReactHookForm.mdx
> +Также мы поддерживаем работу с ReactHookForm
тут бы я добавил ссылку на документацию этой либы

2024-09-30 09:33 UTC, neretin-trike commented on packages/plasma-b2c/src/hooks/useForm.stories.tsx
> +import { Button } from '../components/Button/Button';
а разве вот так импорты не будут работать? 🤔 
import { Button } from '../Button';

2024-09-30 09:40 UTC, neretin-trike commented on packages/plasma-new-hope/src/utils/inputHidden.ts
> +import styled from 'styled-components';
тут нельзя использовать styled-components, переделай пожалуйста на linaria

2024-09-30 09:46 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/TextArea/TextArea.tsx
> +                            ref={mergeRefs(outerRef, innerRef)}
а не лучше ли использовать `useForkRef` в даном случае?

2024-09-30 09:46 UTC, neretin-trike commented on packages/plasma-new-hope/src/utils/setRefList.ts
> +        } else if (ref != null) {
давай пожалуйста без else if тут обойдемся

2024-09-30 09:47 UTC, iljs commented on packages/plasma-new-hope/src/components/TextArea/TextArea.tsx
> +                            ref={mergeRefs(outerRef, innerRef)}
не работает с ним, тестил

2024-09-30 17:12 UTC, shuga2704 requested changes

2024-09-30 17:12 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Slider/components/DoubleUncontrolled/DoubleUncontrolled.tsx
> +    const sortValues = (values: number[]) => {
Правильно ли я понял, что `values` - это массив из строго 2 чисел?

2024-09-30 17:12 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/DatePicker/SingleDate/SingleDate.tsx
> +                        onChange={() => {}}
=(

2024-09-30 17:12 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/DatePicker/SingleDate/SingleDate.tsx
> +import { InputHidden } from '../../TextField/TextField.styles';
Лучше не плодить лишний раз зависимости между компонентами. Это может негативно сказаться в будущем. Давай просто продублируем код, тем более что его там всего 9 строчек.

2024-09-30 17:12 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/DatePicker/SingleDate/SingleDate.tsx
> +                        datatype="datepicker-single"
А где в дальнейшем используется атрибут `datatype`?

2024-09-30 17:12 UTC, shuga2704 commented on packages/plasma-new-hope/src/types/FormType.ts
Это используется только в слайдере. Может не будет выносить в общие типы?

2024-09-30 19:44 UTC, iljs commented on website/plasma-b2c-docs/docs/form/UseForm.mdx
их дока обрезает. Я думаю это касается всей доки и надо делать сразу все

2024-09-30 19:51 UTC, iljs commented on packages/plasma-new-hope/src/components/DatePicker/DatePickerBase.types.ts
> +    onChange?: (event: { target: { value?: string; name?: string } }) => void;
onChangeValue - старое api. Менять нельзя никак 
onChange - React Hook Form воспринимает только onChange в определенном формате и для его поддержки он нужен

2024-09-30 19:54 UTC, iljs commented on packages/plasma-new-hope/src/components/Slider/components/DoubleUncontrolled/DoubleUncontrolled.tsx
> +    const sortValues = (values: number[]) => {
Строго и никак иначе

2024-09-30 19:54 UTC, iljs commented on packages/plasma-new-hope/src/components/DatePicker/SingleDate/SingleDate.tsx
> +                        onChange={() => {}}
=(

2024-09-30 19:54 UTC, iljs commented on packages/plasma-new-hope/src/components/DatePicker/SingleDate/SingleDate.tsx
> +                        onChange={() => {}}
Иначе ошибка в консоли =(

2024-09-30 19:55 UTC, iljs commented on packages/plasma-new-hope/src/components/DatePicker/SingleDate/SingleDate.tsx
> +import { InputHidden } from '../../TextField/TextField.styles';
Меня попросили вынести это до этого =(

2024-09-30 19:55 UTC, iljs commented on packages/plasma-new-hope/src/components/DatePicker/SingleDate/SingleDate.tsx
> +                        datatype="datepicker-single"
в нашем хуке

2024-09-30 19:56 UTC, iljs commented on packages/plasma-new-hope/src/types/FormType.ts
возможно оно еще потом потребуется где=нибудь

2024-10-02 13:59 UTC, closed without merging