feat: Steps API review
salute-developers/plasma pull request #1443
Opened 2024-09-18 13:40 UTC by vadim-kudr

### Реализация компонента Steps [Heading 3]

2024-09-19 11:04 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +  indicator?: number | string | ReactNode;
мы можем вынести в отдельный type общие свойства? 
 
```tsx
  indicator?: number | string | ReactNode;
  progress?: "notStarted" | "completed" | "inProgress";
  disabled?: boolean;
```

2024-09-19 11:05 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +   * @default 'left' */
тут наверное очепятка? Значение boolean а по-умолчанию `left` ?

2024-09-20 07:34 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +   * @default 'left' */
очепятка

2024-09-20 07:42 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +  indicator?: number | string | ReactNode;
имхо, не обязательно. по коду зачастую общие пропсы дублируются

2024-09-20 07:43 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +  indicator?: number | string | ReactNode;
так быстрее общую картину видно, а когда все разбито на мелкие части, то при код ревью приходится код в голове выполнять, чтоб представить что там есть. плюс пропсов всего 3, если больше, то можно задуматься

2024-09-20 08:26 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +  onClick={(item, index) => {
Не очень понимаю, зачем тут onClick? Судя по макетам это же просто статика, которая управляется извне.

2024-09-20 08:27 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +const [exampleItems, setExampleItems] = useState(() =>
Не понимаю, какой тип лежит в `exampleItems`

2024-09-20 08:29 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +  onClick={(item, index) => {
пока дизайн не начал отображать hover,active элементы, все на словах передают

тут логика, что при onClick можно весь step кликать, а без него можно в content положить кнопку и по ней переходить между шагами

если есть onClick и disabled в item, то кнопка не кликабельна

2024-09-20 08:32 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +type StepItemType = StepItemSimple | StepItem;
`title + content`

2024-09-20 08:36 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +  onClick={(item, index) => {
Ок, кликать по ней можно. И тогда получается, что компонент использует только свой внутренний стейт, и как тогда повлиять на него снаружи? Не получится ли ситуации, когда переходы по шагам нужно будет делать снаружи? Без тз сложновато чето проектировать, много непонятных вещей.

2024-09-20 08:39 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +  onClick={(item, index) => {
сейчас снаружи через useState, можно еще шаги пропускать, все на совести пользователя

2024-09-20 08:41 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +  onClick={(item, index) => {
Разработчикам нужно перебирать весь массив, менять значение у ключа progress по нужному индексу и потом снова это отправлять в стейт.
Не проще ли передавать просто items, без progress. И прокинуть `currentStep` (или еще както), чтобы он уже определял какой шаг выбран.

2024-09-20 08:42 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +  onClick={(item, index) => {
в анте чуть изощреннее https://ant.design/components/steps#api

там еще current есть, который может быть перекрыт пропсом из item. и поле status в Steps есть, отображающий статус текущего степа

вот там запутанно

2024-09-20 08:44 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +  onClick={(item, index) => {
> Не проще ли передавать просто items, без progress. И прокинуть currentStep (или еще както), чтобы он уже определял какой шаг выбран.

это ближе к ant. а чтоб не перебирать массив, добавил index в onClick,

2024-09-20 08:47 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +  onClick={(item, index) => {
Не смотрел как там. Изучу и вернусь

2024-09-20 10:53 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +  onClick={(item, index) => {
В общем я во всем разобрался. В анте есть `current` (это для внешнего стейта) и `status` (в рамках конкретного степа). Они так сделали, чтобы поддержать controlled и uncontrolled варианты. Чтобы можно было работать через current снаружи, но также без него, прокидывая в конкретно взятый степ значение статуса. 
Честно говоря, я не вижу причин делать у нас тоже самое. Бездумно копировать не хочется. Что если мы всегда будем завязаны `current`, который будет обычным индексом. И если человек прокидывает еще и `onChange`, то он может менять степы. Если не прокинул `onChange` - то не может по клику менять выбранный степ. Хочет с первого рендера выбрать 5 степ из 10 - пусть прокидывает в current индекс 6 и все. Если извне изменяется этот стейт - то и компонент перерисовывается согласно текущему стейту. Вроде понятно изъяснился. Че думаете?

2024-09-20 11:28 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +  onClick={(item, index) => {
если current === 5, то в 4 элементах должен быть status: completed
или должен болжен игнорироваться и мнимо представляться в completed

2024-09-20 11:29 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +  onClick={(item, index) => {
onChange почти тот же самый onClick

2024-09-20 11:38 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +  onClick={(item, index) => {
uncontrolled вариант можно поддержать, onClick(item, index), currentIndex, stepStatus. клонировать items к себе в innerState и там варить его. еще пользователь может через шаг кликнуть или предыдущий шаг нажать

2024-09-20 11:48 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +  onClick={(item, index) => {
Ты не понял) Статуса в аайтеме не будет от слова совсем. Как и onClick. зачем что-то клонировать в айтес если можно просто хранить индексы.

2024-09-23 06:41 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +  indicator?: number | string | ReactNode;
мы вроде значение "енамов" через camel-case обычно называем (`textfield-like`, `bottom-right` и т.д.):

2024-09-23 06:54 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +id: steps
за это отвечает `hasLine`? Просто видимо сендбокс как обычно кучу ошибок насыпал и не отображает изменения в коде

2024-09-23 06:55 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +  indicatorSize?: 8 | 16 | 24 | 36;
а это не должно быть в конфиге? Ну то есть, пользователь должен мочь выставить size="l" у Steps и size="8" у индикатора?

2024-09-23 06:58 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +type StepItemType = StepItemSimple | StepItem;
соглашусь, union кажется не сильно нужен, к тому же ты потом внутри проверяешь, какой тип отображать

2024-09-23 07:02 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +export const fullItems = [
а может быть больше 99 шагов? Если да, то как тогда должен выглядеть кружок (поместится ли туда число 100)

2024-09-23 07:53 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +export const fullItems = [
хороший вопрос, каунтеры в овал превращаются, тут уточню у дизайна

2024-09-26 11:39 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +  onClick={(item, index) => {
добавил current и status, для uncontrolled варианта можно не хранить статусы в items

2024-09-26 11:39 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +  indicatorSize?: 8 | 16 | 24 | 36;
добавил в типы

2024-10-01 14:01 UTC, Yakutoc commented on website/plasma-b2c-docs/docs/components/Steps.mdx
> +<StorybookLink name="Steps" />
<StorybookLink name="Steps" />, StorybookLink можно удалить

2024-10-01 14:01 UTC, Yakutoc commented on website/plasma-b2c-docs/docs/components/Steps.mdx
> +import { SegmentGroup, SegmentItem, SegmentProvider, useSegment } from '@salutejs/plasma-b2c';
почему Segment???

2024-10-01 14:01 UTC, Yakutoc commented on website/sdds-cs-docs/docs/components/Steps.mdx
> +<StorybookLink name="Steps" />
<StorybookLink name="Steps" />, StorybookLink - не нужно

2024-10-01 14:03 UTC, neretin-trike commented
кажется дока по степсам  сломана

<img width="1389" alt="image" src="https://github.com/user-attachments/assets/231441b8-066a-4485-98ce-4342df5aeedf">

2024-10-01 14:16 UTC, vadim-kudr commented
> кажется дока по степсам сломана
> 
> <img alt="image" width="1389" src="https://private-user-images.githubusercontent.com/26903236/372500342-231441b8-066a-4485-98ce-4342df5aeedf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3OTE3MzEsIm5iZiI6MTcyNzc5MTQzMSwicGF0aCI6Ii8yNjkwMzIzNi8zNzI1MDAzNDItMjMxNDQxYjgtMDY2YS00NDg1LTk4Y2UtNDM0MmRmNWFlZWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDE0MDM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkM2RjYWYzNDNhYmIzZTllZDVhMzFjMDVhNDAwNzY0NDM2NWZiNTdiNzM2OTA3ZmQ3ZDczNWE1MTY1NzZhZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4pSRLsiansQJIVP3e_5gwP1HD31-HvILrdY6cQz8RhA">

да, тренировался в документация. сейчас обновил

2024-10-01 14:40 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +            <Steps items={}
items не хватает

2024-10-01 16:05 UTC, neretin-trike commented
всё-равно поломано :(


<img width="1172" alt="image" src="https://github.com/user-attachments/assets/086d700d-efee-4462-a51e-792bb262c251">

2024-10-01 16:06 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Steps/Steps.review-doc.mdx
> +---
а этот файл в итоге должен в мастер попасть?

2024-10-01 16:12 UTC, Yakutoc commented on packages/plasma-web/src/components/Steps/Steps.stories.tsx
> +import type { StepItemProps } from '../../../../components/Steps/ui';
@vadim-kudr Явно путь не тот что нам нужен. наверное ошибка копи-пасты

2024-10-01 16:13 UTC, shuga2704 requested changes

2024-10-01 16:13 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.tsx
> +            : undefined;
Выглядит не оч, может перепишем чтобы это был всегда коллбэк, просто по условию будем ретурнить?

2024-10-01 16:13 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.tsx
> +    useEffect(() => {
Не критично, но полагаю такие штуки лучше юзать через `useDidMountEffect`.

2024-10-01 16:13 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Steps/Steps.tsx
Пока решили не делать доступность и клавиатурную навигацию?

2024-10-01 16:13 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.styles.ts
> +        // padding-top: calc((var(${tokens.activeBulletSize}) - var(${tokens.bulletSize})) / 2);
Коммент?

2024-10-01 16:13 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.tsx
> +                    onFocus={onMouseOver}
`onFocus` и `onBlur` на div? Для чего?

2024-10-01 16:13 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.tsx
> +                            }}
Почему стили вынесены здесь?

2024-10-01 16:13 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.tsx
> +import cls from 'classnames';
Кажется я понял, у `cls` чуть другая логика работы.

2024-10-01 16:13 UTC, Yakutoc commented on packages/plasma-b2c/src/components/Steps/index.ts
> +export { Steps } from './Steps';
@vadim-kudr Нужно еще в `packages/plasma-b2c/src/index.ts` указать и так во всех пакетах

```
export * from './components/Steps';
```

2024-10-01 16:15 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Steps/Steps.review-doc.mdx
> +---
@vadim-kudr @neretin-trike 
нет, не должен

2024-10-01 16:16 UTC, vadim-kudr commented on packages/plasma-b2c/src/components/Steps/index.ts
> +export { Steps } from './Steps';
точняк

2024-10-01 16:16 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Steps/Steps.tsx
@shuga2704 Отдельной задачей давайте

2024-10-01 16:20 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/Steps.types.ts
> +    onChange?: (item: StepItemProps, index: number, prevIndex?: number) => void;
чтобы было проще стейт менять, у прошлого элемента ставить completed, у нового active

2024-10-01 16:25 UTC, Yakutoc commented on website/plasma-web-docs/docs/components/Steps.mdx
> +const items = [{
@vadim-kudr Это перенеси внутрь `export function App() {`

2024-10-01 16:26 UTC, Yakutoc commented on packages/plasma-b2c/src/components/Steps/Steps.ts
> +const SliderComponent = component(mergedConfig);
@vadim-kudr Переименовать в `const Steps = component(mergedConfig);`

2024-10-01 16:28 UTC, Yakutoc commented on packages/plasma-new-hope/package-lock.json
@vadim-kudr почему lock файл изменился?

2024-10-01 16:33 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.types.ts
> +        | (({ status, item, size }: { status: StepStatus; item: StepItemProps; size: StepsSize }) => ReactNode | null);
логично, еще ReactNode в себе null содержит

2024-10-01 16:34 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/Steps.tsx
да, на дизайн ревью сегодня заметили

2024-10-01 16:35 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.tsx
> +                    onFocus={onMouseOver}
ts ругается, это уменьшает доступность

2024-10-01 16:37 UTC, vadim-kudr commented on packages/plasma-new-hope/package-lock.json
уберу его, случайно попал

2024-10-01 16:39 UTC, vadim-kudr commented on packages/plasma-b2c/src/components/Steps/Steps.ts
> +const SliderComponent = component(mergedConfig);
точно

2024-10-01 16:43 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Steps/Steps.template-doc.mdx
> +const initialItems = [{
@vadim-kudr Перенести в блок `export function App() {`

2024-10-01 16:45 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.styles.ts
> +        // padding-top: calc((var(${tokens.activeIndicatorSize}) - var(${tokens.indicatorSize})) / 2);
@vadim-kudr Живой код? или комментарий?

2024-10-01 16:45 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.styles.ts
> +                // top: calc((var(${tokens.activeBulletSize}) - var(${tokens.bulletSize})));
@vadim-kudr 
???? почему комментарий

2024-10-01 16:49 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.tsx
> +import cls from 'classnames';
@vadim-kudr А откуда она берется? В корне new-hope этой зависимости нет

2024-10-01 16:50 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Steps/Steps.ts
> +// @ts-ignore todo
а есть примерное понимание, почему ломается?

2024-10-01 16:50 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Steps/index.ts
> +export type { StepsProps } from './Steps.types';
у нас есть не гласное правило не отдавать типы наружу для новых компонент

2024-10-01 16:50 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Steps/Steps.types.ts
> +export type StepsSize = 'xs' | 's' | 'm' | 'l';
заранее эти значения не нужно определять, т.к. они генерируются автоматически в зависимости от конфигов

2024-10-01 16:50 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Steps/Steps.tsx
> +
поясни пожалуйста логику работы сторевого пропса simple? Я не очень её понял, почему в одном случае компонент на всю ширину, а в другом на фиксированную

<img width="1681" alt="Screenshot 2024-10-01 at 21 15 18" src="https://github.com/user-attachments/assets/2e2deaf8-e527-416e-88cb-d7920259a7da">

<img width="1607" alt="Screenshot 2024-10-01 at 21 15 08" src="https://github.com/user-attachments/assets/05a99f83-6e8c-4978-a049-1d36b37161f7">

2024-10-01 16:50 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Steps/Steps.stories.tsx
> +};
мне кажется всё-таки пора убирать в tsconfig сторисы из экслюда, потому что я так понимаю у тех, кто пишет в вебшторме, типы не проверяются

<img width="924" alt="image" src="https://github.com/user-attachments/assets/fd006a65-353d-404c-8700-d9539bd7cf1e">

2024-10-01 16:50 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.types.ts
> +        | (({ status, item, size }: { status: StepStatus; item: StepItemProps; size: StepsSize }) => ReactNode | null);
давай для большей наглядности вынесем этот колбэк в отдельный тип

2024-10-01 16:50 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.tsx
> +import cls from 'classnames';
а это будет корректно работать в других библиотеках? Я просто не вижу, чтобы мы где-то явно указывали её как зависимость

2024-10-01 16:50 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Steps/Steps.tokens.ts
> +    transparentDivider: '--plasma-steps-transparent-divider',
убери пожалуйста префикс --plasma-steps, он добавляется только в токены

2024-10-01 16:50 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Steps/Steps.tsx
> +                view="default"
тут это значение нужно забирать из пропсов

2024-10-01 16:50 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Steps/Steps.tsx
> +                        content = '';
может вынесем эту часть кода в семантическую функцию? Чтобы jsx почище выглядел

2024-10-01 16:50 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Steps/Steps.tsx
> +                            itemStatus = status || 'active';
давай попробуем без вложенных else if пожалуйста

2024-10-01 16:50 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Steps/Steps.tsx
> +                            onClick={onChange ? () => onChange(item, index, prevIndex) : undefined}
*минор*

опять таки для чистоты предлагаю вынести в хендлер

2024-10-01 16:50 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.tsx
> +        hasContent?: 'all' | 'active' | 'none';
StepsContent

2024-10-01 16:51 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.tsx
> +        orientation?: 'horizontal' | 'vertical';
возможно это тоже имеет смысл вынести в отдельные типы, т.к. они переиспользуются

2024-10-01 16:51 UTC, vadim-kudr commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Steps/Steps.ts
> +// @ts-ignore todo
onChange конфликтует с html div

2024-10-01 16:52 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.tsx
> +} as const;
а вот эти значения гвоздями прибиты и не могут быть никак переопределены? И соотвествуют ли они размеру самого Steps?

2024-10-01 16:53 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/Steps.tsx
> +
https://www.figma.com/design/k9cPALEfxAm5wvr3k6SYBe/SDDS-Base-%7C-Documentation?node-id=5372-7353&node-type=canvas&t=dJDZEcBvEITuGiF7-0

это по доке решили сделать для Simple отображения. Там только индикаторы без title и content. Они уже тянутся

2024-10-01 16:55 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.tsx
> +} as const;
пока прибыти, вытаскивал из дизайна. в идеале там попробовать центрирование по baseline сделать, но нужно отдельно смотреть. ждал ответов по другим вопросам по дизайну

2024-10-01 16:56 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.styles.ts
> +                // top: calc((var(${tokens.activeBulletSize}) - var(${tokens.bulletSize})));
нужно себе сохнарить, может еще понадобиться, а это удалю

2024-10-01 16:56 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.styles.ts
> +        // padding-top: calc((var(${tokens.activeIndicatorSize}) - var(${tokens.indicatorSize})) / 2);
удалю

2024-10-01 16:57 UTC, neretin-trike commented on packages/sdds-dfa/src/components/Steps/Steps.config.ts
> +        size: 's',
а в сторибук по умолчанию m размер, дак какой должен быть на самом деле? 🤔

2024-10-01 17:00 UTC, neretin-trike commented on packages/sdds-finportal/src/components/Steps/index.ts
> +export type { StepsProps } from '@salutejs/plasma-new-hope/styled-components';
не нужно внаружу отдавать типы

2024-10-01 17:05 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Steps/Steps.ts
> +// @ts-ignore todo
у нас бывает такая проблема, посмотри пожалуйста как в Accordion например сделано, там тоже есть onChange

2024-10-01 18:00 UTC, vadim-kudr commented on packages/sdds-dfa/src/components/Steps/Steps.config.ts
> +        size: 's',
это я с CS копировал, оставлю m везде

2024-10-01 20:35 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/Steps.types.ts
> +export type StepsSize = 'xs' | 's' | 'm' | 'l';
жаль, autocomplete тогда отваливается

2024-10-01 21:03 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/Steps.tsx
вообще, это бы в дизайне / доку указывать

2024-10-01 21:18 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/Steps.tsx
> +        const [prevIndex, setPrevIndex] = useState<number | undefined>();
тут `undefined`, как и current по умолчанию `undefined`.

2024-10-01 21:40 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.tsx
> +import cls from 'classnames';
кто-то тянет из дочерних зависимостей. добавил явно

2024-10-01 21:41 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.tsx
> +                </BulletIndicatorWrapper>
🤔 имхо, отступы не очень распространены в html, добавил, но стало не привычно

2024-10-01 21:46 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/Steps.tsx
> +                        content = '';
эту часть заменил на тернарник, другую вынес в функцию

имхо, map в jxs тоже выступает как часть смысловой группировки и изоляции кода

2024-10-01 22:45 UTC, vadim-kudr commented on packages/sdds-finportal/src/components/Steps/index.ts
> +export type { StepsProps } from '@salutejs/plasma-new-hope/styled-components';
cтранно, оставил только StepItemProps

2024-10-02 05:59 UTC, Yakutoc commented on packages/sdds-finportal/src/components/Steps/index.ts
> +export type { StepsProps } from '@salutejs/plasma-new-hope/styled-components';
@vadim-kudr Мы предлагаем нашим пользователям использовать - `type AttachComponentsProps = ComponentProps<typeof Attach>` такую запись. Это надежней

2024-10-02 06:06 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Steps/Steps.tsx
@vadim-kudr добавлю такой пункт в чек лист для прки

2024-10-02 07:19 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.tsx
> +    const [isHovered, setIsHovered] = useState(false);
ховер есть на 2 элемента, они в разных блоках пока

2024-10-02 07:22 UTC, neretin-trike commented
вопрос по логике компонента. Такое, когда у тебя активный шаг идёт перед завершенными?

<img width="593" alt="image" src="https://github.com/user-attachments/assets/ab45e87a-51d5-4795-be74-de4a44f1c277">

(если это баг, то сейчас фиксить не предлагаю)

2024-10-02 07:24 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Steps/Steps.tsx
> +
оке, спасиб

2024-10-02 07:27 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.tsx
> +            : undefined;
добавил коммент с todo, сейчас стремно менять

2024-10-02 07:27 UTC, neretin-trike commented on packages/plasma-b2c/src/components/Steps/index.ts
> +export type { StepItemProps } from '@salutejs/plasma-new-hope/styled-components';
нужно убрать типы

2024-10-02 07:28 UTC, vadim-kudr commented on packages/plasma-b2c/src/components/Steps/index.ts
> +export type { StepItemProps } from '@salutejs/plasma-new-hope/styled-components';
а как в сторибуке доставить? StepsProps убрал

2024-10-02 07:31 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Steps/ui/StepItem/StepItem.tsx
> +            : undefined;
а где именно добавил? Пока не видно

2024-10-02 07:33 UTC, shuga2704 commented on packages/plasma-b2c/src/components/Steps/index.ts
> +export type { StepItemProps } from '@salutejs/plasma-new-hope/styled-components';
В сторибуке через `Component<typeof Steps>`

2024-10-02 07:41 UTC, shuga2704 commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Steps/Steps.stories.tsx
> +};
А ты не разобрался почему вс код так себя ведет? Видимо какие то настройки оверрайдят тсконфиг?

2024-10-02 07:42 UTC, vadim-kudr commented on packages/plasma-b2c/src/components/Steps/index.ts
> +export type { StepItemProps } from '@salutejs/plasma-new-hope/styled-components';
не Steps нужен, а с StepItemProps. доставить тип из массива Steps::items ?

2024-10-02 08:13 UTC, neretin-trike approved these changes

2024-10-02 08:19 UTC, Yakutoc approved these changes

2024-10-02 12:26 UTC, Irinkv approved these changes

2024-10-02 13:25 UTC, shuga2704 approved these changes

2024-10-02 13:31 UTC, merged