fix: focus TextArea by click inside
salute-developers/plasma pull request #1444
Opened 2024-09-19 10:05 UTC by vadim-kudr

### [TextArea] Фокусировка TextArea по клику на дочерние элементы

### What/why changed

По клина на helpers / icons будет появляться курсор на TextArea

2024-09-19 11:57 UTC, shuga2704 requested changes

2024-09-19 11:57 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/TextArea/TextArea.tsx
Принудительный скролл при фокусе? Не думаю, что надо нужно это добавлять.

2024-09-19 12:01 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/TextArea/TextArea.tsx
в TextField так сделано из-за необходимости скроллить при чипах. Так понял, что в TextArea тоже чипы будят и сейчас там нечему скроллится

2024-09-19 15:22 UTC, shuga2704 approved these changes

2024-09-20 12:50 UTC, denivladislav approved these changes

2024-10-15 15:23 UTC, merged