feat: add Badge & Tabs truncate props
salute-developers/plasma pull request #1500
Opened 2024-10-22 08:22 UTC by vadim-kudr

### Badge, Tabs

Здесь описываем резюме вносимых изменений.

В формате списка, например

-   добавили новый api
-   изменили свойство size

Пример такого описания, см. ниже

```md
### Raised hand

-   добавлена новая иконка

<img width="48" alt="raisedHand" src="https://github.com/salute-developers/plasma/assets/46107741/212dbd44-1739-456e-83c3-e4362a2a10fd">
```

Примечания:

-   По возможности приложите скриншоты решенной проблемы в формате "до/после" или скриншоты нового компонента.
-   Обязательно укажите соответствующий **label**. Это нужно для определения правильной категории вносимых изменений.

### What/why changed (Это обязательный заголовок)

Более подробное описание решаемой проблемы.

### Labels

Это то, что **решает** ваш pull request. Label может быть только один.

Список доступных labels:

-   Components (задача добавить новый компонент)
-   Infra (поправили CI/CD, обновили зависимости, etc)
-   Tokens (поправили в plasma-tokens, theme-builder)
-   Icons (добавили новые иконки)
-   Docs (задачи связанные с документацией)

Все что не попадает в вышеперечисленное, попадет в категорию Misc.

### Прежде чем перевести в статус "requested a review" убедитесь

-   Добавлен номер issue (если есть);
-   Добавлены/обновлены **cypress тесты** если PR касается визуальной составляющей;

2024-10-31 11:19 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Badge/Badge.tsx
> +export const badgeRoot = (Root: RootProps<HTMLDivElement, BadgeRootProps & { truncate: boolean }>) =>
Давай занесем `truncate: boolean` в `BadgeRootProps`

2024-10-31 11:26 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Badge/Badge.tsx
>                  view={view}
Вынеси `truncate && classes.badgeTruncate` в переменную наверх

2024-10-31 11:26 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Badge/variations/_truncate/base.ts
Кажется, стили можно перенести во view или size. Тут по сути нет токенов специфичных

2024-10-31 11:26 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/components/Tabs/ui/horizontal/HorizontalTabItem/HorizontalTabItem.tsx
> +                className={cx(pilledClass, selectedClass, animatedClass, truncate && classes.tabsTruncate, className)}
Так же, вынеси в переменную

2024-10-31 11:26 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Badge/Badge.stories.tsx
> +        text: 'Hello Kitty',
😺

2024-10-31 11:27 UTC, TitanKuzmich commented
Добавь пожалуйста тест на truncate. И сейчас почему-то обновленные тесты только для plasma-web

2024-11-01 06:49 UTC, shuga2704 requested changes

2024-11-01 06:49 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Tabs/TabItem.types.ts
> +    maxItemWidth?: string;
```suggestion
    maxItemWidth?: CSSProperties['width'];
```
Как насчет такого?

2024-11-01 06:49 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Tabs/TabItem.types.ts
> +     * @default 'auto'
Не увидел, где задается что по умолчанию это `auto`?

2024-11-01 06:49 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Tabs/ui/horizontal/HorizontalTabItem/HorizontalTabItem.tsx
> +        const truncate = maxWidth !== 'auto';
А когда юзер не прокидывает `maxItemWidth`, мы получаем `undefined`, и `truncate` становится true. Это валидно?

2024-11-01 06:49 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Tabs/ui/horizontal/HorizontalTabItem/HorizontalTabItem.tsx
> +    Root: RootProps<HTMLDivElement, HorizontalTabItemProps & { truncate: boolean }>,
Не понял, тут добавился тип для `truncate`, а внизу ты объявляем переменную. Это как?

2024-11-08 07:06 UTC, shuga2704 approved these changes

2024-11-08 07:25 UTC, TitanKuzmich approved these changes

2024-11-08 08:00 UTC, merged