feat(plasma-new-hope): Dropzone
salute-developers/plasma pull request #1534
Opened 2024-11-05 07:42 UTC by TitanKuzmich

### Dropzone

- добавлен черновик компонента Dropzone

### What/why changed

2024-11-07 08:24 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Dropzone/Dropzone.types.ts
> +    onDropFiles?: FileProcessHandler;
а зачем отдельный колбэк? Не получится использовать onDrop?

2024-11-07 08:26 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Dropzone/Dropzone.types.ts
> +    onDragOver?: () => void;
пока из описания не очень понял разницу между этим методом и onDragEnter

2024-11-07 08:34 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Dropzone/Dropzone.types.ts
> +    onDragOver?: () => void;
onDragEnter срабатывает один раз, когда курсор с файлами пересек границу Dropzone. onDragOver срабатывает при любом движении курсора с файлами внутри области Dropzone. Расширю описание

2024-11-07 08:36 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Dropzone/Dropzone.types.ts
> +    onDropFiles?: FileProcessHandler;
Мне показалось, что нужен безусловный вызов callback onDrop, до onDropFiles. Но сейчас, он действительно избыточен. Уберу onDropFiles

2024-11-07 08:42 UTC, vadim-kudr commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Dropzone/Dropzone.template-docs.mdx
> +    onDragEnter?: () => void;
`(event: SomeEvent) => void`?

2024-11-07 08:43 UTC, vadim-kudr commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Dropzone/Dropzone.template-docs.mdx
> +    onDropFiles?: FileProcessHandler;
имхо, название немного конфликтует с `onDrop`, особенно с описанием onDrop

2024-11-07 08:45 UTC, vadim-kudr commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Dropzone/Dropzone.template-docs.mdx
> +    onChoseFiles?: FileProcessHandler;
а после onChoseFiles не нужна валидация?

2024-11-07 08:59 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Dropzone/Dropzone.template-docs.mdx
> +    onChoseFiles?: FileProcessHandler;
Она происходит до вызова этого коллбека. Сейчас он аналогичен onDropFiles. Этот cb вызывается при onChange на инпуте

2024-11-08 16:03 UTC, shuga2704 commented
Мы не хотим title и description обернуть в `user-select: none`? А для курсора поставить pointer?

2024-11-08 16:20 UTC, shuga2704 requested changes

2024-11-08 16:20 UTC, shuga2704 commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Dropzone/Dropzone.tsx
> +                    } as CSSProperties
А почему мы не можем передать стили рестом, а ширину явно через пропс, минуя токены?

2024-11-08 16:20 UTC, shuga2704 commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Dropzone/Dropzone.tsx
> +                console.log(res);
```suggestion
```

2024-11-08 16:20 UTC, shuga2704 commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Dropzone/Dropzone.tsx
> +            if (rawFiles && rawFiles.length > 0) {
Можем давай инвертируем и сразу выйдем из функции если нет файлов, чтобы не оборачивать весь кусок целиком?

2024-11-08 16:20 UTC, shuga2704 commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Dropzone/Dropzone.tsx
> +        const handleChange = async (event: ChangeEvent<HTMLInputElement>) => {
Здесь не нужен персист?

2024-11-11 11:17 UTC, TitanKuzmich commented on packages/plasma-new-hope/src/examples/plasma_b2c/components/Dropzone/Dropzone.tsx
> +        const handleChange = async (event: ChangeEvent<HTMLInputElement>) => {
Нет, тут нам не нужно как в onDrop очищать dataTransfer

2024-11-12 08:51 UTC, iljs approved these changes

2024-11-26 11:53 UTC, merged