feat: add hasInnerLabelPlaceholder prop to TextField
salute-developers/plasma pull request #1556
Opened 2024-11-12 07:16 UTC by vadim-kudr

### TextField

Здесь описываем резюме вносимых изменений.

В формате списка, например

-   добавили новый api
-   изменили свойство size

Пример такого описания, см. ниже

```md
### Raised hand

-   добавлена новая иконка

<img width="48" alt="raisedHand" src="https://github.com/salute-developers/plasma/assets/46107741/212dbd44-1739-456e-83c3-e4362a2a10fd">
```

Примечания:

-   По возможности приложите скриншоты решенной проблемы в формате "до/после" или скриншоты нового компонента.
-   Обязательно укажите соответствующий **label**. Это нужно для определения правильной категории вносимых изменений.

### What/why changed (Это обязательный заголовок)

Более подробное описание решаемой проблемы.

### Labels

Это то, что **решает** ваш pull request. Label может быть только один.

Список доступных labels:

-   Components (задача добавить новый компонент)
-   Infra (поправили CI/CD, обновили зависимости, etc)
-   Tokens (поправили в plasma-tokens, theme-builder)
-   Icons (добавили новые иконки)
-   Docs (задачи связанные с документацией)

Все что не попадает в вышеперечисленное, попадет в категорию Misc.

### Прежде чем перевести в статус "requested a review" убедитесь

-   Добавлен номер issue (если есть);
-   Добавлены/обновлены **cypress тесты** если PR касается визуальной составляющей;

2024-11-12 13:45 UTC, denivladislav commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> -} & (
Можешь подсказать, для чего перенёс внутрь каждого из объектов юниона?

2024-11-12 13:59 UTC, denivladislav commented on cypress/snapshots/b2c/components/TextField/TextField.component-test.tsx/plasma-b2c TextField -- content hasInnerLabelPlaceholder, size l.snap.png
Сорри, я что-то не разобрался с тестами 😕

Судя по снэпшотам получается, что у нас сейчас нет проверки ситуации, когда есть и плейсхолдер вместе со включеным `hasInnerLabelPlaceholder`, и лейбл с `labelPlacement=inner`. Т.е. нет снэпшота с ситуацией как на прикрепленной картинке

<img width="307" alt="example" src="https://github.com/user-attachments/assets/2e4be473-98a3-4cfe-9d30-3258a2d1a03a">

2024-11-12 14:03 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> -} & (
чтоб в одном месте про label и было и с типами эксперементировал

2024-11-12 14:03 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> -} & (
Autocomplete что-то ругается :( на типы, добавил `ts-ignore`

2024-11-12 14:23 UTC, vadim-kudr commented on cypress/snapshots/b2c/components/TextField/TextField.component-test.tsx/plasma-b2c TextField -- content hasInnerLabelPlaceholder, size l.snap.png
ща, гляну. но не факт, что этот скрин можно получить на plasma-web и plasma-b2c, там кастомная есть и поле animatedHint. в отдельной задаче это будет правиться

2024-11-13 08:32 UTC, denivladislav commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> +          labelPlacement?: 'inner' | 'outer';
нужен ли здесь 'inner'?

2024-11-13 08:33 UTC, denivladislav commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> -} & (
обсудили лично, что можно попробовать не гасить проверку типов

2024-11-13 09:18 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> +          hasInnerLabelPlaceholder?: boolean;
тогда здесь нужно true?

2024-11-13 09:19 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> +          hasInnerLabelPlaceholder?: boolean;
почему?

2024-11-13 09:26 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> +          hasInnerLabelPlaceholder?: never | false;
кажется, что false в этой итерации не нужен

2024-11-13 09:30 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> +          requiredPlacement?: 'left' | 'right';
Давай это вынесем за рамки юнион-типа? Оно ведь повторяется

2024-11-13 09:30 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> +          label?: string;
И это тоже, label ведь одинаковый

2024-11-13 10:03 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> +          label?: string;
да, но все в одном месте

2024-11-13 10:04 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> +          requiredPlacement?: 'left' | 'right';
имхо, норм. там иначе трудно читаемое получается

2024-11-13 10:04 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> +          hasInnerLabelPlaceholder?: never | false;
имхо, hasInnerLabelPlaceholder может быть, но с false

2024-11-13 10:04 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> +          labelPlacement?: 'inner' | 'outer';
еще never добавил, без всего этого ts начинает ругаться

2024-11-13 10:06 UTC, denivladislav commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> +          labelPlacement?: 'inner' | 'outer';
можешь, пожалуйста, объяснить, почему такой странный юнион тип вместе с never нужен?

2024-11-20 15:08 UTC, Irinkv approved these changes

2024-11-21 14:50 UTC, denivladislav commented on packages/plasma-new-hope/src/components/DatePicker/SingleDate/SingleDate.types.ts
> +          labelPlacement?: never | 'outer';
Можешь подсказать, зачем тут `never` в union?

2024-11-21 14:52 UTC, denivladislav commented on packages/plasma-new-hope/src/components/DatePicker/SingleDate/SingleDate.tsx
> +                    labelPlacement={labelPlacement}
Вроде как можно удалить, поскольку далее всё равно задаём `labelPlacement`:

`'labelPlacement' is specified more than once, so this usage will be overwritten.`

2024-11-21 14:53 UTC, denivladislav commented on packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.types.ts
> +          labelPlacement?: never | 'outer';
тоже вопрос про `never`

2024-11-21 15:03 UTC, denivladislav commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> +          clear: never | false;
тут тоже не совсем понял, для чего правка

2024-11-21 15:05 UTC, denivladislav commented on packages/plasma-web/src/components/TextField/TextField.tsx
> +          labelPlacement?: 'inner' | 'outer';
и тут тоже вопрос про юнион, почему 'inner' | 'outer'

2024-11-22 08:24 UTC, iljs approved these changes

2024-11-22 08:26 UTC, denivladislav approved these changes

2024-11-25 08:57 UTC, Yakutoc commented on cypress/snapshots/b2c/components/Autocomplete/Autocomplete.component-test.tsx/plasma-b2c Autocomplete -- prop disabled.snap.png
@vadim-kudr Мне кажется Label и его размеры не должны быть такими. Нужно уточнить у дизайна

2024-11-25 10:24 UTC, vadim-kudr commented on cypress/snapshots/b2c/components/Autocomplete/Autocomplete.component-test.tsx/plasma-b2c Autocomplete -- prop disabled.snap.png
это я свежий dev подтянул, чекну

2024-11-25 10:39 UTC, shuga2704 commented
Добавь плз описание в сам пр, чтобы инфа попала в ченжлог.

2024-11-25 10:59 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> +
Давай комментарии писать только в одном из юнионов, т.к. текст дублируется

2024-11-25 11:46 UTC, shuga2704 requested changes

2024-11-25 11:46 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> +
Мне не нравится название `hasPlaceholder`. Не отражает суть этого свойства. Предлагаю такое: `showPlaceholder`, `revealPlaceholder`, `visiblePlaceholder`, `placeholderIsVisible` etc.

2024-11-25 11:46 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Autocomplete/Autocomplete.tsx
> +                    labelPlacement={labelPlacement ? undefined : labelPlacement}
Для чего это изменение?

2024-11-25 11:46 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Autocomplete/Autocomplete.tsx
> +                                    : { labelPlacement })}
Выше на 140 строке тогда нужно удалить labelPlacement

2024-11-25 11:46 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> +
В связи с появившимися обстоятельствами я бы отказался от использования юниона в данном случае, т.к. он не сильно на что-то влияет, но усложняет код в компонентах, которые наследуют типы отсюда. 
cc: @neretin-trike

2024-11-25 11:46 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.types.ts
> +
Может лучше экспортируем это из текстфилда?

2024-11-25 11:46 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Combobox/ComboboxNew/Combobox.types.ts
> -    labelPlacement?: 'outer' | 'inner';
Почему мы тут вырезали, а из автокомплита нет? Оно вроде не должно ничего ломать, если это оставить, только тип должен быть string, т.к. движок сам создаст тип на основе конфигов.

2024-11-25 11:46 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/DatePicker/SingleDate/SingleDate.types.ts
> +
Тот же вопрос, что и в комбобоксе

2024-11-25 11:46 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Select/Select.types.ts
> +
Также, го импортировать

2024-11-25 11:46 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Select/Select.types.ts
> +    LabelProps &
Отсюда это убрать

2024-11-25 11:46 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/Select/Select.types.ts
Добавить LabelProps внутрь типа Target в самом начале файла, т.к. он дальше используется как в `SelectProps` так и в `MergedSelectProps`.

2024-11-25 13:58 UTC, vadim-kudr commented on packages/plasma-new-hope/src/components/Autocomplete/Autocomplete.tsx
> +                    labelPlacement={labelPlacement ? undefined : labelPlacement}
это косяк, на типы ругался и я ночью правил )

2024-11-26 13:15 UTC, merged