feat(plasma-core/plasma-ui): processing price periodicity
salute-developers/plasma pull request #220
Opened 2022-11-15 10:00 UTC by Yakutoc

Добавить возможность указывать в цене регулярность платежа.

2022-11-15 10:11 UTC, Yakutoc commented
После того как это PR вольем.

Мне останется всего лишь подлить мастер в свою ветку где уже реализована поддержка **Periodicity** для компонента **ProductCart**.

2022-11-15 10:13 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-220/

2022-11-15 10:22 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-220/
  ui storybook: http://plasma.sberdevices.ru/pr-220/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-220/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-220/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-220/temple-storybook/

2022-11-15 10:52 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-220/

2022-11-15 11:07 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-220/
  ui storybook: http://plasma.sberdevices.ru/pr-220/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-220/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-220/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-220/temple-storybook/

2022-11-17 06:54 UTC, neretin-trike commented on packages/plasma-core/src/components/Price/Price.component-test.tsx
> +                        font-family: "SB Sans Text", sans-serif;
а для чего здесь добавлять font-family?

2022-11-17 06:56 UTC, neretin-trike commented on packages/plasma-core/src/components/Price/Price.tsx
> +        {formatCurrency(children, currency, minimumFractionDigits)} {periodicity || null}
*минор*

а почему не просто {periodicity}?

2022-11-17 07:08 UTC, Yakutoc commented on packages/plasma-core/src/components/Price/Price.tsx
> +        {formatCurrency(children, currency, minimumFractionDigits)} {periodicity || null}
Тоже верно. Сначала сделал как защита от дурака, а сейчас думаю что можно и проще )

Спасибо.

2022-11-17 07:14 UTC, Yakutoc commented on packages/plasma-core/src/components/Price/Price.component-test.tsx
> +                        font-family: "SB Sans Text", sans-serif;
@neretin-trike Тут сделал по аналогии с остальными тестами.  Суть проблемы со стилями не изучал еще.

2022-11-17 07:16 UTC, neretin-trike commented on packages/plasma-core/src/components/Price/Price.component-test.tsx
> +                        font-family: "SB Sans Text", sans-serif;
а, окей 👌

2022-11-17 07:16 UTC, neretin-trike approved these changes

2022-11-17 07:31 UTC, Yeti-or commented on packages/plasma-core/src/components/Price/Price.component-test.tsx
> +                        font-family: "SB Sans Text", sans-serif;
а завели задачку

2022-11-17 07:31 UTC, Yeti-or commented on packages/plasma-core/src/components/Price/Price.component-test.tsx
> +enum Periodicity {
а почему его не импортировать из самого компонента?

2022-11-17 07:31 UTC, Yeti-or commented on packages/plasma-core/src/components/Price/types.ts
> +    periodicity?: Periodicity | ReactElement;
чет печально это конечно в доке выглядит 
<img width="1015" alt="Screenshot 2022-11-17 at 10 24 26" src="https://user-images.githubusercontent.com/1813468/202382469-7444484d-f041-40f2-9274-1037c30155b0.png">

2022-11-17 07:31 UTC, Yeti-or commented on packages/plasma-ui/src/components/Price/Price.stories.tsx
> +    default = '',
а это типа не заданное значение?

2022-11-17 07:36 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-220/
  <details>
    <summary>New documentation</summary>
    <br />

    http://plasma.fine.sberdevices.ru/pr/demo-canvas-app-pr-220/

  </details>

2022-11-17 07:57 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-220/
  ui storybook: http://plasma.sberdevices.ru/pr-220/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-220/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-220/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-220/temple-storybook/
  <details>
    <summary>New documentation</summary>
    <br />

    website: http://plasma.fine.sberdevices.ru/pr/pr-220/
    ui storybook: http://plasma.fine.sberdevices.ru/pr/pr-220/ui-storybook/
    web storybook: http://plasma.fine.sberdevices.ru/pr/pr-220/web-storybook/
    b2c storybook: http://plasma.fine.sberdevices.ru/pr/pr-220/b2c-storybook/
    temple storybook: http://plasma.fine.sberdevices.ru/pr/pr-220/temple-storybook/

  </details>

2022-11-17 08:41 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-220/
  <details>
    <summary>New documentation</summary>
    <br />

    http://plasma.fine.sberdevices.ru/pr/demo-canvas-app-pr-220/

  </details>

2022-11-17 08:55 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-220/
  ui storybook: http://plasma.sberdevices.ru/pr-220/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-220/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-220/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-220/temple-storybook/
  <details>
    <summary>New documentation</summary>
    <br />

    website: http://plasma.fine.sberdevices.ru/pr/pr-220/
    ui storybook: http://plasma.fine.sberdevices.ru/pr/pr-220/ui-storybook/
    web storybook: http://plasma.fine.sberdevices.ru/pr/pr-220/web-storybook/
    b2c storybook: http://plasma.fine.sberdevices.ru/pr/pr-220/b2c-storybook/
    temple storybook: http://plasma.fine.sberdevices.ru/pr/pr-220/temple-storybook/

  </details>

2022-11-17 11:27 UTC, Yeti-or requested changes
<img width="1111" alt="Screenshot 2022-11-17 at 14 26 52" src="https://user-images.githubusercontent.com/1813468/202434375-ff6da8f9-8ce3-4de2-93ad-b78f4a029cc7.png">

Это не выглядит как плавающий тест

2022-11-17 11:33 UTC, Yakutoc commented
> <img alt="Screenshot 2022-11-17 at 14 26 52" width="1111" src="https://user-images.githubusercontent.com/1813468/202434375-ff6da8f9-8ce3-4de2-93ad-b78f4a029cc7.png">
> 
> Это не выглядит как плавающий тест
Уже разобрались в чем проблема.

2022-11-17 11:36 UTC, Yeti-or commented
@Yakutoc и в чем ?

2022-11-17 11:51 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-220/
  <details>
    <summary>New documentation</summary>
    <br />

    http://plasma.fine.sberdevices.ru/pr/demo-canvas-app-pr-220/

  </details>

2022-11-17 12:07 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-220/
  ui storybook: http://plasma.sberdevices.ru/pr-220/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-220/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-220/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-220/temple-storybook/
  <details>
    <summary>New documentation</summary>
    <br />

    website: http://plasma.fine.sberdevices.ru/pr/pr-220/
    ui storybook: http://plasma.fine.sberdevices.ru/pr/pr-220/ui-storybook/
    web storybook: http://plasma.fine.sberdevices.ru/pr/pr-220/web-storybook/
    b2c storybook: http://plasma.fine.sberdevices.ru/pr/pr-220/b2c-storybook/
    temple storybook: http://plasma.fine.sberdevices.ru/pr/pr-220/temple-storybook/

  </details>

2022-11-17 12:16 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-220/
  <details>
    <summary>New documentation</summary>
    <br />

    http://plasma.fine.sberdevices.ru/pr/demo-canvas-app-pr-220/

  </details>

2022-11-17 12:24 UTC, Yeti-or approved these changes

2022-11-17 12:24 UTC, Yeti-or commented on packages/plasma-core/src/components/Price/Price.component-test.tsx
> +                        font-family: "SB Sans Text", sans-serif;
TODO: github issue плиз

2022-11-17 12:24 UTC, Yeti-or commented on packages/plasma-ui/src/components/Price/Price.stories.tsx
> +                options: ['/ день', '/ неделя', '/ месяц', '/ год', ''],
пустая строка выглядит как хак конечно, я правильно понял что оно не умеет быть не выбраным?

2022-11-17 12:24 UTC, Yeti-or commented on packages/plasma-core/src/components/Price/types.ts
> +    periodicity?: '/ день' | '/ неделя' | '/ месяц' | '/ год' | React.ReactElement;
<img width="909" alt="Screenshot 2022-11-17 at 15 24 01" src="https://user-images.githubusercontent.com/1813468/202445580-4a6469f2-04e8-484a-90c1-1117885f6d00.png">
вот же 💩

2022-11-17 12:24 UTC, Yeti-or commented on packages/plasma-core/src/components/Price/types.ts
> +    periodicity?: '/ день' | '/ неделя' | '/ месяц' | '/ год' | React.ReactElement;
ладно видимо забьем на это

2022-11-17 12:28 UTC, Yakutoc commented on packages/plasma-core/src/components/Price/types.ts
> +    periodicity?: '/ день' | '/ неделя' | '/ месяц' | '/ год' | React.ReactElement;
@Yeti-or Давай пока так. И я поищу способ как это упростить.

2022-11-17 12:30 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-220/
  ui storybook: http://plasma.sberdevices.ru/pr-220/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-220/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-220/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-220/temple-storybook/
  <details>
    <summary>New documentation</summary>
    <br />

    website: http://plasma.fine.sberdevices.ru/pr/pr-220/
    ui storybook: http://plasma.fine.sberdevices.ru/pr/pr-220/ui-storybook/
    web storybook: http://plasma.fine.sberdevices.ru/pr/pr-220/web-storybook/
    b2c storybook: http://plasma.fine.sberdevices.ru/pr/pr-220/b2c-storybook/
    temple storybook: http://plasma.fine.sberdevices.ru/pr/pr-220/temple-storybook/

  </details>

2022-11-17 13:05 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-220/
  <details>
    <summary>New documentation</summary>
    <br />

    http://plasma.fine.sberdevices.ru/pr/demo-canvas-app-pr-220/

  </details>

2022-11-17 13:19 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-220/
  ui storybook: http://plasma.sberdevices.ru/pr-220/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-220/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-220/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-220/temple-storybook/
  <details>
    <summary>New documentation</summary>
    <br />

    website: http://plasma.fine.sberdevices.ru/pr/pr-220/
    ui storybook: http://plasma.fine.sberdevices.ru/pr/pr-220/ui-storybook/
    web storybook: http://plasma.fine.sberdevices.ru/pr/pr-220/web-storybook/
    b2c storybook: http://plasma.fine.sberdevices.ru/pr/pr-220/b2c-storybook/
    temple storybook: http://plasma.fine.sberdevices.ru/pr/pr-220/temple-storybook/

  </details>

2022-11-17 13:39 UTC, Yeti-or commented
:shipit:

2022-11-17 13:40 UTC, merged