feat: Add Plasma Theme Builder
salute-developers/plasma pull request #254
Opened 2022-11-30 07:14 UTC by neretin-trike

2022-11-30 08:28 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-254/
  <details>
    <summary>New documentation</summary>
    <br />

    http://plasma.fine.sberdevices.ru/pr/demo-canvas-app-pr-254/

  </details>

2022-11-30 08:41 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-254/
  ui storybook: http://plasma.sberdevices.ru/pr-254/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-254/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-254/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-254/temple-storybook/
  <details>
    <summary>New documentation</summary>
    <br />

    website: http://plasma.fine.sberdevices.ru/pr/pr-254/
    ui storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/ui-storybook/
    web storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/web-storybook/
    b2c storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/b2c-storybook/
    temple storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/temple-storybook/

  </details>

2022-11-30 09:29 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-254/
  <details>
    <summary>New documentation</summary>
    <br />

    http://plasma.fine.sberdevices.ru/pr/demo-canvas-app-pr-254/

  </details>

2022-11-30 09:43 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-254/
  ui storybook: http://plasma.sberdevices.ru/pr-254/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-254/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-254/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-254/temple-storybook/
  <details>
    <summary>New documentation</summary>
    <br />

    website: http://plasma.fine.sberdevices.ru/pr/pr-254/
    ui storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/ui-storybook/
    web storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/web-storybook/
    b2c storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/b2c-storybook/
    temple storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/temple-storybook/

  </details>

2022-11-30 12:40 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/plasma-theme-builder-pr-254/

2022-11-30 12:58 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-254/
  ui storybook: http://plasma.sberdevices.ru/pr-254/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-254/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-254/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-254/temple-storybook/
  <details>
    <summary>New documentation</summary>
    <br />

    website: http://plasma.fine.sberdevices.ru/pr/pr-254/
    ui storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/ui-storybook/
    web storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/web-storybook/
    b2c storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/b2c-storybook/
    temple storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/temple-storybook/

  </details>

2022-11-30 13:08 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-254/
  <details>
    <summary>New documentation</summary>
    <br />

    http://plasma.fine.sberdevices.ru/pr/demo-canvas-app-pr-254/

  </details>

2022-11-30 13:15 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-254/
  ui storybook: http://plasma.sberdevices.ru/pr-254/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-254/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-254/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-254/temple-storybook/
  <details>
    <summary>New documentation</summary>
    <br />

    website: http://plasma.fine.sberdevices.ru/pr/pr-254/
    ui storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/ui-storybook/
    web storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/web-storybook/
    b2c storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/b2c-storybook/
    temple storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/temple-storybook/

  </details>

2022-11-30 13:27 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/plasma-theme-builder-pr-254/

2022-11-30 13:28 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-254/
  <details>
    <summary>New documentation</summary>
    <br />

    http://plasma.fine.sberdevices.ru/pr/demo-canvas-app-pr-254/

  </details>

2022-11-30 13:42 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-254/
  ui storybook: http://plasma.sberdevices.ru/pr-254/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-254/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-254/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-254/temple-storybook/
  <details>
    <summary>New documentation</summary>
    <br />

    website: http://plasma.fine.sberdevices.ru/pr/pr-254/
    ui storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/ui-storybook/
    web storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/web-storybook/
    b2c storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/b2c-storybook/
    temple storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/temple-storybook/

  </details>

2022-12-01 07:14 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-254/
  <details>
    <summary>New documentation</summary>
    <br />

    http://plasma.fine.sberdevices.ru/pr/demo-canvas-app-pr-254/

  </details>

2022-12-01 07:18 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/plasma-theme-builder-pr-254/
  <details>
    <summary>New theme builder</summary>
    <br />

    http://plasma.fine.sberdevices.ru/pr/plasma-theme-builder-pr-254/

  </details>

2022-12-01 07:29 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-254/
  ui storybook: http://plasma.sberdevices.ru/pr-254/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-254/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-254/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-254/temple-storybook/
  <details>
    <summary>New documentation</summary>
    <br />

    website: http://plasma.fine.sberdevices.ru/pr/pr-254/
    ui storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/ui-storybook/
    web storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/web-storybook/
    b2c storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/b2c-storybook/
    temple storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/temple-storybook/

  </details>

2022-12-01 10:43 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-254/
  <details>
    <summary>New documentation</summary>
    <br />

    http://plasma.fine.sberdevices.ru/pr/demo-canvas-app-pr-254/

  </details>

2022-12-01 10:46 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-254/
  <details>
    <summary>New documentation</summary>
    <br />

    http://plasma.fine.sberdevices.ru/pr/demo-canvas-app-pr-254/

  </details>

2022-12-01 10:54 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-254/
  ui storybook: http://plasma.sberdevices.ru/pr-254/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-254/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-254/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-254/temple-storybook/
  <details>
    <summary>New documentation</summary>
    <br />

    website: http://plasma.fine.sberdevices.ru/pr/pr-254/
    ui storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/ui-storybook/
    web storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/web-storybook/
    b2c storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/b2c-storybook/
    temple storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/temple-storybook/

  </details>

2022-12-01 10:58 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/plasma-theme-builder-pr-254/
  <details>
    <summary>New theme builder</summary>
    <br />

    http://plasma.fine.sberdevices.ru/pr/plasma-theme-builder-pr-254/

  </details>

2022-12-01 11:04 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-254/
  ui storybook: http://plasma.sberdevices.ru/pr-254/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-254/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-254/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-254/temple-storybook/
  <details>
    <summary>New documentation</summary>
    <br />

    website: http://plasma.fine.sberdevices.ru/pr/pr-254/
    ui storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/ui-storybook/
    web storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/web-storybook/
    b2c storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/b2c-storybook/
    temple storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/temple-storybook/

  </details>

2022-12-01 11:08 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-254/
  <details>
    <summary>New documentation</summary>
    <br />

    http://plasma.fine.sberdevices.ru/pr/demo-canvas-app-pr-254/

  </details>

2022-12-01 11:17 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/plasma-theme-builder-pr-254/
  <details>
    <summary>New theme builder</summary>
    <br />

    http://plasma.fine.sberdevices.ru/pr/plasma-theme-builder-pr-254/

  </details>

2022-12-01 11:19 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-254/
  <details>
    <summary>New documentation</summary>
    <br />

    http://plasma.fine.sberdevices.ru/pr/demo-canvas-app-pr-254/

  </details>

2022-12-01 11:31 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-254/
  ui storybook: http://plasma.sberdevices.ru/pr-254/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-254/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-254/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-254/temple-storybook/
  <details>
    <summary>New documentation</summary>
    <br />

    website: http://plasma.fine.sberdevices.ru/pr/pr-254/
    ui storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/ui-storybook/
    web storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/web-storybook/
    b2c storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/b2c-storybook/
    temple storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/temple-storybook/

  </details>

2022-12-01 11:49 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-254/
  <details>
    <summary>New documentation</summary>
    <br />

    http://plasma.fine.sberdevices.ru/pr/demo-canvas-app-pr-254/

  </details>

2022-12-01 12:14 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-254/
  ui storybook: http://plasma.sberdevices.ru/pr-254/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-254/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-254/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-254/temple-storybook/
  <details>
    <summary>New documentation</summary>
    <br />

    website: http://plasma.fine.sberdevices.ru/pr/pr-254/
    ui storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/ui-storybook/
    web storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/web-storybook/
    b2c storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/b2c-storybook/
    temple storybook: http://plasma.fine.sberdevices.ru/pr/pr-254/temple-storybook/

  </details>

2022-12-02 06:19 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/plasma-theme-builder-pr-254/
  <details>
    <summary>New theme builder</summary>
    <br />

    http://plasma.fine.sberdevices.ru/pr/plasma-theme-builder-pr-254/

  </details>

2022-12-02 08:05 UTC, Yeti-or commented on .github/workflows/theme-builder-pr.yml
> +name: PR theme-builder
cc @kayman233

2022-12-02 08:12 UTC, kayman233 requested changes

2022-12-02 08:12 UTC, kayman233 commented on .github/workflows/theme-builder-pr.yml
> +              <details>
Это уже можно убрать. Теперь, получается только остается
http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-${context.issue.number}/

2022-12-02 08:12 UTC, kayman233 commented on .github/workflows/theme-builder.yml
> +          DEST_DIR: 'plasma-theme-builder'
Лучше двойные кавычки для однообразия

2022-12-05 08:24 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-254/

2022-12-05 08:27 UTC, kayman233 approved these changes

2022-12-05 08:34 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-254/

2022-12-06 05:34 UTC, Yakutoc commented on website/plasma-theme-builder/src/components/utils.ts
> +    const sep = rgbaOrigin.indexOf(',') > -1 ? ',' : ' ';
@neretin-trike Что думаешь насчет метода **includes**?  

Уберем сравнение с `> -1`

2022-12-06 05:37 UTC, Yakutoc commented on website/plasma-theme-builder/src/components/utils.ts
> +    const rgba = rgbaOrigin.substring(5).split(')')[0].split(sep);
[Minor]
@neretin-trike может посмотрим в сторону разделения? Для улучшения читаемости.

2022-12-06 05:39 UTC, Yakutoc commented on website/plasma-theme-builder/src/components/utils.ts
> +        Number(rgba[0]).toString(16),
[Minor]

Почему не `parseInt(rgba[0], 16)`?

2022-12-06 05:55 UTC, Yakutoc commented on website/plasma-theme-builder/src/components/utils.ts
> +    if (r.length === 1) {
[Minor]

@neretin-trike Дублирование смущает. Не пробовал через **reduce** сделать **весь** метод?

2022-12-06 06:04 UTC, Yakutoc commented on website/plasma-theme-builder/src/components/types.ts
> +    value: string | Record<string, any>;
[Minor]
@neretin-trike 

> Record<string, any>

`any` OR `unknown` ? )

2022-12-06 06:05 UTC, Yakutoc commented
@neretin-trike Good job!

2023-01-09 11:37 UTC, neretin-trike commented on website/plasma-theme-builder/src/components/utils.ts
> +        Number(rgba[0]).toString(16),
прост этот метод не подходит, т.к. он возвращает целочисленное в зависимости от того какую строку и в какой системе исчисления ты ему скормишь.

т.е. parseInt('0xFF', 16) вернёт 255, а parseInt('0.96', 16) => 0

2023-01-09 12:03 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-254/

2023-01-09 12:42 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-254/

2023-01-09 12:55 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-254/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-254/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-254/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-254/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-254/temple-storybook/

2023-01-09 14:00 UTC, Yeti-or commented on website/plasma-theme-builder/src/components/FormField/FormField.tsx
> +            <Label>{label}</Label>
тут как-будто должна быть связь между label и компонентом, 
вообще странно что ты используешь готовые: Select, Switch, TextField
и тебе надо еще и обертку для label городить =/

2023-01-09 14:02 UTC, Yeti-or commented on website/plasma-theme-builder/src/components/ThemeTypeToggle/ThemeTypeToggle.tsx
> +        <StyledThemeTypeButton isSelected={selectedType === type} onClick={handleOnClick}>
кнопка ввиде span ? это что за элемент такой у нас?

2023-01-09 14:03 UTC, Yeti-or commented on website/plasma-theme-builder/src/components/ThemeTypeToggle/ThemeTypeToggle.tsx
> +        <StyledThemeToggle>
можешь дизайн показать?

2023-01-09 14:07 UTC, Yeti-or commented on website/plasma-theme-builder/src/components/EditTheme/EditTheme.tsx
> +                    <ThemeInfo label="Название темы" value={name} />
```
      <div>
           <Description>
                <div>
                    <ThemeInfo label="Название темы" value={name} />
```

ну что-то я не уверен что это сильно менее читаемое, но если это не несет лишний нагрузки на создание всякого в styled-components
то ладно

2023-01-09 14:13 UTC, Yeti-or commented on website/plasma-theme-builder/src/components/Token/Token.tsx
> +        enabled === false &&
может `<TokenName disable={!value.enabled} /> ?`

2023-01-09 14:14 UTC, Yeti-or commented on website/plasma-theme-builder/src/components/Token/Token.tsx
> +    width: 7rem;
а это прям осознанные числа? или тупо чтобы хватило?
может тут нужен inline элемент ?

2023-01-09 14:15 UTC, Yeti-or commented on website/plasma-theme-builder/src/components/Token/Token.tsx
> +    const onMouseLeave = useCallback(() => setVisible(false), []);
а зачем тут useCallback ?

2023-01-09 14:17 UTC, Yeti-or commented on website/plasma-theme-builder/src/components/TokensSubsection/TokensSubsection.tsx
> +                    <Token key={`${index}_${tokenName}`} name={name} value={value} />
tokenName не уникальный?

2023-01-10 04:21 UTC, Yakutoc commented on website/plasma-theme-builder/package.json
> +    "license": "ISC",
@Yeti-or А что твой коммент значит?)

2023-01-10 04:32 UTC, Yakutoc commented on website/plasma-theme-builder/src/components/Generator/Generator.tsx
> +            if (typeof arg === 'object' && arg.target.type === 'text') {
@neretin-trike Можешь тезисно написать, что хотел сделать? )

2023-01-10 04:32 UTC, Yakutoc commented on website/plasma-theme-builder/src/components/Generator/Generator.tsx
> +        (name: string) => (arg: any) => {
@neretin-trike Можешь тезисно написать, что хотел сделать? )

2023-01-10 04:33 UTC, Yakutoc commented on website/plasma-theme-builder/src/components/Generator/Generator.tsx
> +        (name: string) => (arg: any) => {
@neretin-trike 

`arg: any` можем типизовать?

2023-01-10 04:35 UTC, Yakutoc commented on website/plasma-theme-builder/src/components/Generator/Generator.tsx
> +const Form = styled.form``;
@neretin-trike 

Вася хороший вопрос задал выше, а нам действительно нужно создавать через **styled** теги? 

Можем ли сразу использовать form, etc?

2023-01-10 05:07 UTC, Yakutoc commented on website/plasma-theme-builder/src/index.css
> +@font-face {
@Yeti-or Куда? Не совсем понял твой комментарий.

2023-01-10 05:11 UTC, Yakutoc commented on website/plasma-theme-builder/public/index.html
> +    <link rel="stylesheet" href="https://cdn-app.sberdevices.ru/shared-static/0.0.0/styles/SBSansText.0.1.0.css" />
@neretin-trike Можно еще посмотреть в сторону `rel="preload"`

[rel="preload"](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload)

2023-01-10 09:10 UTC, neretin-trike commented on website/plasma-theme-builder/package.json
> +    "license": "ISC",
лицензия у нас не такая :D, убрал

2023-01-10 09:56 UTC, neretin-trike commented on website/plasma-theme-builder/src/GlobalStyle.tsx
> +import './index.css';
импорт font-family локальных шрифтов

2023-01-10 09:58 UTC, neretin-trike commented on website/plasma-theme-builder/src/assets/mocks.tsx
> +            // enabled: false,
это моковый файл, его уже нет в следующих прках :)

2023-01-10 09:59 UTC, neretin-trike commented on website/plasma-theme-builder/src/assets/mocks.tsx
> +import React from 'react';
я его далее удаляю, поэтому кажется особо нет значения, где он лежит

2023-01-10 09:59 UTC, neretin-trike commented on website/plasma-theme-builder/src/index.css
> +    src: url('./assets/fonts/SBSansTextMono-Regular.woff2') format('woff2'),
да, пока отсутствуют

2023-01-10 10:10 UTC, neretin-trike commented on website/plasma-theme-builder/tsconfig.json
> +        "allowJs": true,
неа

2023-01-10 10:11 UTC, neretin-trike commented on website/plasma-theme-builder/src/index.css
> +@font-face {
я предлагаю на это отдельную задачу, иначе прка проложит ещё дольше висеть

2023-01-10 10:11 UTC, neretin-trike commented on website/plasma-theme-builder/src/components/Footer/Footer.tsx
> +    &:visited {
неа, я хотел стилизовать её по-своему (т.к. дизайна не было на тот момент), поэтому так

2023-01-10 10:12 UTC, neretin-trike commented on website/plasma-theme-builder/src/components/Footer/Footer.tsx
> +        display: none;
согласен, но другой возможности кастомить нету

2023-01-10 10:18 UTC, neretin-trike commented on website/plasma-theme-builder/src/components/Footer/Footer.tsx
> +        color: ${primary};
да, у нас есть только один view, который не подходит

2023-01-10 10:21 UTC, neretin-trike commented on website/plasma-theme-builder/src/components/Main/Main.tsx
> +const Paragraph = styled.p``;
просто в наших библиотеках нигде не используются чистые тэги. С одной стороны, хотел сохранить такой подход для единообразия и некоторой консистентности, с другой - для семантики, т.к. хочется видеть для чего от или иной контейнер, даже если он не стилизован

2023-01-10 10:21 UTC, neretin-trike commented on website/plasma-theme-builder/src/components/Generator/Generator.tsx
> +            if (typeof arg === 'object' && arg.target.type === 'text') {
думаешь лучше разделить?

2023-01-10 10:22 UTC, neretin-trike commented on website/plasma-theme-builder/src/components/FormField/FormField.tsx
> +            <Label>{label}</Label>
ну да, я тоже не в восторге, но был вынужден

2023-01-10 10:22 UTC, neretin-trike commented on website/plasma-theme-builder/src/components/ThemeTypeToggle/ThemeTypeToggle.tsx
> +        <StyledThemeTypeButton isSelected={selectedType === type} onClick={handleOnClick}>
в других прках я это уже поправил, но вообще это просто переключалка режима темы

2023-01-10 10:24 UTC, neretin-trike commented on website/plasma-theme-builder/src/components/ThemeTypeToggle/ThemeTypeToggle.tsx
> +        <StyledThemeToggle>
<img width="408" alt="image" src="https://user-images.githubusercontent.com/26903236/211525801-b8eb12c5-7496-4960-b6f5-1c2e97d15bc4.png">

2023-01-10 10:29 UTC, neretin-trike commented on website/plasma-theme-builder/src/components/EditTheme/EditTheme.tsx
> +                    <ThemeInfo label="Название темы" value={name} />
на самом деле как раз название Column в случае даёт понять стиль компоновки без просмотра результата верстки на сайте (ну по крайней мере мне так хочется верить). А вообще, я посмотрел, что styled-component накидывает один класс и всё, что кажется не сильно большой нагрузкой

2023-01-10 11:09 UTC, neretin-trike commented on website/plasma-theme-builder/src/components/Token/Token.tsx
> +    const onMouseLeave = useCallback(() => setVisible(false), []);
да по инерции на самом деле, могу убрать

2023-01-10 11:11 UTC, neretin-trike commented on website/plasma-theme-builder/src/components/Generator/Generator.tsx
> +const Form = styled.form``;
ответил повыше

2023-01-10 11:14 UTC, neretin-trike commented on website/plasma-theme-builder/src/components/Generator/Generator.tsx
> +        (name: string) => (arg: any) => {
к сожалению не получится, т.к. у компонента Select такой интефрейс на onChange: ((value: any) => void), так што

2023-01-10 11:16 UTC, neretin-trike commented on website/plasma-theme-builder/src/components/Generator/Generator.tsx
> +        (name: string) => (arg: any) => {
да, а это просто универсальный хендлер для трёх типов инпутов: селект, текст и свитч

2023-01-10 13:36 UTC, Yeti-or commented on website/plasma-theme-builder/src/index.css
> +@font-face {
тут не отобразился коммент: `это сразу в <head> ?`

2023-01-10 13:37 UTC, Yeti-or commented on website/plasma-theme-builder/src/components/Footer/Footer.tsx
> +    &:visited {
это странно
давай заведем задачку про это

2023-01-10 13:37 UTC, Yeti-or commented on website/plasma-theme-builder/src/components/Footer/Footer.tsx
> +        display: none;
но почему нам надо так кастомить ссылку? ну выглядит же странно

2023-01-10 13:37 UTC, Yeti-or commented on website/plasma-theme-builder/src/components/Footer/Footer.tsx
> +        color: ${primary};
@gibushnev что за стили такие которых нет в плазме ?

2023-01-10 13:38 UTC, Yeti-or commented on website/plasma-theme-builder/src/components/Generator/Generator.tsx
> +            if (typeof arg === 'object' && arg.target.type === 'text') {
я бы разделил да

2023-01-10 13:38 UTC, Yeti-or commented on website/plasma-theme-builder/src/components/FormField/FormField.tsx
> +            <Label>{label}</Label>
надо на это тоже завести задачи

2023-01-10 13:38 UTC, Yeti-or commented on website/plasma-theme-builder/src/components/ThemeTypeToggle/ThemeTypeToggle.tsx
> +        <StyledThemeToggle>
button_type_clear не ?

2023-01-10 13:39 UTC, Yeti-or commented on website/plasma-theme-builder/src/components/Token/Token.tsx
> +    width: 7rem;
=)

2023-01-10 13:42 UTC, Yeti-or commented
вообщем давайте зафиксируем,
1) что нам нравится называть компоненты семантически через styled.div``
2) если видим что в наших же компонентах приходится костылять, то это либо надо поменять в дизайне, либо поставить задачу на доработку компонента, прям тут с // TODO: gh-issue-number
3) разобраться почему у нас нет нужных шрифтов на cdn

2023-01-10 13:42 UTC, Yeti-or approved these changes

2023-01-11 05:46 UTC, Yakutoc approved these changes

2023-01-11 07:44 UTC, Yeti-or commented on website/plasma-theme-builder/src/components/ThemeInfo/ThemeInfo.tsx
> +const ThemeLabel = styled(H4)``;
Кстати в данном случае можно и так

```
const ThemeLabel = H4;
```

2023-01-11 16:46 UTC, neretin-trike commented on website/plasma-theme-builder/src/components/ThemeTypeToggle/ThemeTypeToggle.tsx
> +        <StyledThemeToggle>
в принципе тоже практически подходит, спасиб 👌

2023-01-11 17:03 UTC, neretin-trike commented on website/plasma-theme-builder/src/index.css
> +@font-face {
через инлайн в style не получится их добавить, если ты об этом. Реакт не сможет таким образом понять и не выгрузит файлы шрифтов в сурс

2023-01-12 06:30 UTC, neretin-trike commented on website/plasma-theme-builder/src/components/FormField/FormField.tsx
> +            <Label>{label}</Label>
но вообще, если учесть, что дизайн такого вида, то может и не надо задачку заводить? Label всё-таки в данном случае совсем по-другому выглядит, и это прям кастом

<img width="692" alt="image" src="https://user-images.githubusercontent.com/26903236/211994063-e20f66af-aecd-4dcf-b0c0-e7a0527d769b.png">

2023-01-12 06:37 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-254/

2023-01-12 06:42 UTC, Salute-Eva commented
**Component performance testing**

Result: **🔴 Fail**

Check out comparison report in job artifacts!

2023-01-12 11:21 UTC, Yeti-or commented on website/plasma-theme-builder/src/index.css
> +@font-face {
я не понял, что именно реакт не может понять

2023-01-13 07:02 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-254/

2023-01-13 07:09 UTC, Salute-Eva commented
**Component performance testing**

Result: **🔴 Fail**

Check out comparison report in job artifacts!

2023-01-13 07:12 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-254/

2023-01-13 07:27 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-254/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-254/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-254/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-254/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-254/temple-storybook/

2023-01-13 07:48 UTC, merged