feat(plasma-web): processing Shift + Arrow Left\Right navigate
salute-developers/plasma pull request #273
Opened 2022-12-26 11:55 UTC by Yakutoc

Для навигации только по доступным дням необходимо использовать сочетание клавиш Shift + Arrow  Left\Right

2022-12-26 12:55 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-273/

2022-12-26 13:11 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-273/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-273/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-273/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-273/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-273/temple-storybook/

2022-12-27 06:49 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-273/

2022-12-27 07:14 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-273/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-273/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-273/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-273/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-273/temple-storybook/

2022-12-27 07:46 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-273/

2022-12-27 08:00 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-273/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-273/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-273/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-273/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-273/temple-storybook/

2023-01-16 07:25 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-273/

2023-01-16 07:32 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

2023-01-16 07:35 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-273/

2023-01-17 10:45 UTC, Yeti-or commented on packages/plasma-web/src/components/Calendar/utils.ts
> +export const createDateByDataAttrs = (item: HTMLDivElement): Date | undefined => {
а это где используется?

2023-01-17 10:45 UTC, Yeti-or commented on packages/plasma-web/src/components/Calendar/CalendarBase.tsx
> +const IsOutOfRange = styled.div`
это невидимый элемент ?

2023-01-17 10:45 UTC, Yeti-or commented on packages/plasma-web/src/components/Calendar/CalendarBase.tsx
> +    clip: rect(0 0 0 0);
видимо он не видим из-за этого
почему не visibility hidden ?

2023-01-17 11:01 UTC, Yeti-or requested changes

2023-01-17 13:29 UTC, Yakutoc commented on packages/plasma-web/src/components/Calendar/utils.ts
> +export const hasDateRestrict = (date?: Date, min?: Date, max?: Date): boolean | undefined =>
@Yeti-or Это старое. Удалил, спасибо что обратил внимание.

2023-01-17 13:30 UTC, Yakutoc commented on packages/plasma-web/src/components/Calendar/utils.ts
> +export const createDateByDataAttrs = (item: HTMLDivElement): Date | undefined => {
@Yeti-or Старое, удалил.

2023-01-17 13:31 UTC, Yakutoc commented on packages/plasma-web/src/components/Calendar/CalendarBase.tsx
> +const IsOutOfRange = styled.div`
@Yeti-or Да, это элемент который содержит в себе подсказку для screen-reader.

2023-01-17 13:32 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-273/

2023-01-17 13:32 UTC, Yakutoc commented on packages/plasma-web/src/components/Calendar/CalendarBase.tsx
> +    clip: rect(0 0 0 0);
@Yeti-or Перепроверю, я изначально сразу так сделал. Но screen-reader почему-то не прочел содержимое.

2023-01-17 13:39 UTC, Salute-Eva commented
**Component performance testing**

Result: **🔴 Fail**

Check out comparison report in job artifacts!

2023-01-17 13:42 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-273/

2023-01-17 13:45 UTC, Yeti-or commented on packages/plasma-web/src/components/Calendar/CalendarBase.tsx
> +    clip: rect(0 0 0 0);
Мы не можем поставить тупо aria-label и он будет доступен для ридера но не доступен визуально ?

2023-01-17 14:07 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-273/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-273/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-273/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-273/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-273/temple-storybook/

2023-01-18 04:21 UTC, Yakutoc commented on packages/plasma-web/src/components/Calendar/hooks/useKeyNavigation.ts
> +                        if (isDisabledArrowLeft) {
@Yeti-or Да, тест есть.

2023-01-18 04:21 UTC, Yakutoc commented on packages/plasma-web/src/components/Calendar/hooks/useKeyNavigation.ts
> +                        if (isDisabledArrowRight) {
@Yeti-or Да, тест есть.

2023-01-18 04:21 UTC, Yakutoc commented on packages/plasma-web/src/components/Calendar/hooks/useKeyNavigation.ts
> +            newRowIndex--;
@Yeti-or Да, тест есть.

2023-01-18 04:23 UTC, Yakutoc commented on packages/plasma-web/src/components/Calendar/hooks/useKeyNavigation.ts
> +    withShift = false,
@Yeti-or хм, проверю, но скорее ты прав и можно без по-умолчанию.

2023-01-18 04:39 UTC, neretin-trike commented on packages/plasma-web/src/components/Calendar/hooks/useDays.ts
> +        dayItem.isDisabledPreviousMonth = isDisabledPreviousMonth(currentDate, min);
Кажется, что можно эту логику упростить. По сути, тебе не надо столько дата атрибуттов накидывать, достаточно одного и в нем хранить логику всех этих проверок.

Имею ввиду, что у тебя будет условно "dayItem.isDisable", и в нём будет значение в зависимости от того, какой метод (isDisabledArrowLeft,Right,Up,Down,NextMonth,PrevMonth) вернул true быстрее

2023-01-18 04:44 UTC, neretin-trike commented on packages/plasma-web/src/components/Calendar/hooks/useKeyNavigation.ts
> +function isDisabledNavigateByAttr({
*minor*

Тут бы я тоже использовал стрелочную функцию для поддержания единого стиля

2023-01-18 04:47 UTC, neretin-trike commented on packages/plasma-web/src/components/Calendar/hooks/useKeyNavigation.ts
> +function getCorrectColumnIndex({
Здесь тож стрелочную нужно

2023-01-18 06:14 UTC, Yakutoc commented on packages/plasma-web/src/components/Calendar/CalendarBase.tsx
> +    clip: rect(0 0 0 0);
@Yeti-or К сожалению, нет. Это **aria-live region** элемент  

```
     aria-atomic="true"
     role="alert"
     aria-live="assertive"
     aria-relevant="additions"
```   
и он должен быть "условно виден", если мы хотим, чтобы изменения его содержимого объявлялось и озвучивалось корректно. 

[ARIA Live Regions](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions)

2023-01-18 06:36 UTC, Yakutoc commented on packages/plasma-web/src/components/Calendar/hooks/useDays.ts
> +        dayItem.isDisabledPreviousMonth = isDisabledPreviousMonth(currentDate, min);
@neretin-trike Тут немного иначе работает. 

Этими проверками я узнаю в каком направление нельзя передвигаться что бы на соотвествующие клавиши блокировать событие.         

Пример:  
**min** - апрель
**выключенные дни** в мае - с 1 по 7 число.

По **моей** логики через **(Shift + Left)** я не могу с 7 мая перейти на 6 число, потому что день выключенный. 

Так же через Shift + Up не получиться перейти на 30 апреля, потому что `isDisabledArrowUp === true` (апрель у нас min)

НО я могу с 7 мая перейти на 6 число через Left, а по твоей логики 7 число уже будет иметь `isDisable === true` потому что проверка **isDisabledArrowUp** вернула именно это.

2023-01-19 07:49 UTC, Yeti-or commented on packages/plasma-web/src/components/Calendar/Calendar.component-test.tsx
> +        it.skip("Can't jump to dates outside of min max dates", () => {
ждем тестов

2023-01-19 11:39 UTC, neretin-trike commented on packages/plasma-web/src/components/Calendar/hooks/useDays.ts
> +        dayItem.isDisabledPreviousMonth = isDisabledPreviousMonth(currentDate, min);
оке, я понял о чём ты. А что если попробовать вместо булевых значений хранить строку, в которой перечисляются направление по которым нельзя перейти? А затем при проверки их парсить и понимать, можешь перейти или нет? Если я правильно понял, то тебе только важно наличие или отсутствие этого значение, и тогда будет что-то вроде:

```ts
.... // здесь функция, которая возвращает направления, которые залочены и собирает это в строку
dayItem.isDisabledTo = 'arrowLeft, arrowRight, arrowDown, arrowUp';
```

а метод проверки похожий на:

```ts
function isDisabledNavigateByAttr({
    refs,
    payload,
    attr,
}: {
    refs: React.MutableRefObject<HTMLDivElement[][]>;
    payload: number[];
    arrow: 'arrowLeft' | 'arrowRight' | 'arrowUp' | 'arrowDown';
}) {
    const [previousRowIndex, previousColumnIndex] = payload;

    const disabledArrows = refs.current?.[previousRowIndex]?.[previousColumnIndex].dataset.isDisabledTo;

    return  disabledArrows.includes(arrow) === 'true';
}
```

2023-01-20 06:43 UTC, Yakutoc commented on packages/plasma-web/src/components/Calendar/hooks/useDays.ts
> +        dayItem.isDisabledPreviousMonth = isDisabledPreviousMonth(currentDate, min);
Я думал о чем то подобном, но через JSON. Твой вариант кажется имеет право на жизнь - сделаю.

2023-01-20 06:43 UTC, Yakutoc commented on packages/plasma-web/src/components/Calendar/Calendar.component-test.tsx
> +        it.skip("Can't jump to dates outside of min max dates", () => {
@Yeti-or Тесты которые падали поправил.

2023-01-20 06:45 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-273/

2023-01-20 06:53 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

2023-01-20 06:55 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-273/

2023-01-20 07:17 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-273/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-273/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-273/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-273/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-273/temple-storybook/

2023-01-20 08:34 UTC, Yeti-or approved these changes

2023-01-23 06:11 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-273/

2023-01-23 06:17 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

2023-01-23 06:21 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-273/

2023-01-23 06:38 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-273/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-273/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-273/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-273/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-273/temple-storybook/

2023-01-23 06:52 UTC, neretin-trike approved these changes

2023-01-23 06:54 UTC, neretin-trike commented on packages/plasma-web/src/components/Calendar/hooks/useKeyNavigation.ts
> +    return disabledArrowKey ? disabledArrowKey.includes(key) : false;
а тут точно тернарник нужен?* Почему не 
```ts
return disabledArrowKey?.includes(key)
```

2023-01-23 06:57 UTC, Yakutoc commented on packages/plasma-web/src/components/Calendar/hooks/useKeyNavigation.ts
> +    return disabledArrowKey ? disabledArrowKey.includes(key) : false;
> а тут точно тернарник нужен?* Почему не
> 
> ```ts
> return disabledArrowKey?.includes(key)
> ```

Скорее всего ты прав.

2023-01-23 08:37 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-273/

2023-01-23 08:49 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-273/

2023-01-23 08:54 UTC, Salute-Eva commented
**Component performance testing**

Result: **🔴 Fail**

Check out comparison report in job artifacts!

2023-01-23 09:03 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-273/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-273/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-273/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-273/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-273/temple-storybook/

2023-01-26 06:59 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-273/

2023-01-26 07:11 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-273/

2023-01-26 07:18 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

2023-01-26 07:22 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-273/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-273/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-273/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-273/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-273/temple-storybook/

2023-01-27 07:05 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-273/

2023-01-27 07:20 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-273/

2023-01-27 07:22 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

2023-01-27 07:42 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-273/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-273/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-273/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-273/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-273/temple-storybook/

2023-01-31 04:21 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-273/

2023-01-31 04:31 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-273/

2023-01-31 04:38 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

2023-01-31 04:43 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-273/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-273/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-273/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-273/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-273/temple-storybook/

2023-01-31 14:12 UTC, Salute-Eva commented
**Component performance testing**

Result: **🔴 Fail**

Check out comparison report in job artifacts!

2023-01-31 15:28 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-273/

2023-01-31 15:40 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-273/

2023-01-31 15:45 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

2023-01-31 15:52 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-273/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-273/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-273/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-273/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-273/temple-storybook/

2023-01-31 15:57 UTC, Yeti-or approved these changes

2023-02-02 03:50 UTC, merged