feat(plasma-ui): add support of @salutejs/spatial, fix context memoization
salute-developers/plasma pull request #285
Opened 2023-01-19 15:24 UTC by arsenykruglikov

Button
- Confirm ✅ 
- Stepper ✅ 

Input
- Checkbox общий ✅ 
- Radiobox общий ✅ 
- TextField собственный ✅ 
- Switch собственный ✅ 

TextArea ✅ 

Carousel: нет смысла делать навигацию на CarouselItem так как внутри него может лежать что угодно, в том числе что-то для навигации. И во-вторых к CarouselItem и CarouseCol можно применить className самостоятельно.

Picker: надо обсудить а на что там делать фокус, на те что в середине или только на стрелочки

PaginationDots: нет интерактива

Slider: не понятно как передвигать react-draggabe компонент с помощью стрелочек на клавиатуре

Tabs: Используется в сочетании TabItem на который класс можно проставить самостоятельно

Toast: нет интерактива

2023-01-19 15:28 UTC, Salute-Eva commented
**Component performance testing**

Result: **🌚 Missing base report**

Check out current report in job artifacts!

2023-01-19 15:28 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-285/

2023-01-20 08:16 UTC, Yeti-or reviewed
А почему классы добавляются в core а не в ui ?

2023-01-20 08:16 UTC, Yeti-or commented on packages/plasma-core/src/components/Basebox/Basebox.tsx
> +    props.className = `${props.className} sn-section-item`;
а почему тут не использовать attrs ? 

https://styled-components.com/docs/basics#attaching-additional-props

2023-01-20 08:16 UTC, Yeti-or commented on packages/plasma-core/src/components/Button/Button.tsx
> +    props.className = `${props.className} sn-section-item`;
`sn-section-item` – было бы здорово  коммент c ссылкой на доку spatnav

потому что `sn` не прям говорящее название если не знаешь про sn

2023-01-20 08:16 UTC, Yeti-or commented on packages/plasma-ui/src/components/Tabs/TabItem.tsx
> - */
👍

2023-01-20 08:17 UTC, Yeti-or commented
@arsenykruglikov что-то всё развалолось в pr

2023-01-20 10:11 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-285/

2023-01-20 10:11 UTC, Salute-Eva commented
**Component performance testing**

Result: **🌚 Missing base report**

Check out current report in job artifacts!

2023-01-20 10:39 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-285/

2023-01-20 10:46 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

2023-01-20 10:48 UTC, arsenykruglikov commented on packages/plasma-core/src/components/Basebox/Basebox.tsx
> +    props.className = `${props.className} sn-section-item`;
Мне показалось сначала, что так не очень, но я вынес колбек в отдельную функцию и получилось нормально

2023-01-20 10:49 UTC, arsenykruglikov commented on packages/plasma-core/src/components/Button/Button.tsx
> +    props.className = `${props.className} sn-section-item`;
Добавил коммент в функцию добавления className

2023-01-20 10:50 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-285/

2023-01-20 11:11 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-285/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-285/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-285/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-285/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-285/temple-storybook/

2023-01-20 12:13 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-285/

2023-01-20 12:18 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

2023-01-20 12:22 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-285/

2023-01-20 12:43 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-285/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-285/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-285/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-285/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-285/temple-storybook/

2023-01-21 04:52 UTC, Yakutoc approved these changes

2023-01-21 04:54 UTC, Yakutoc commented
@arsenykruglikov Привет, объясни пожалуйста что именно вызвало трудности? ) 
   
> Slider: не понятно как передвигать react-draggable компонент с помощью стрелочек на клавиатуре

2023-01-23 05:50 UTC, neretin-trike approved these changes

2023-01-23 08:09 UTC, Yeti-or commented
@arsenykruglikov я всё ещё не могу понять почему эти изменения в  plasma-core а не в plasma-ui ?

2023-01-23 08:10 UTC, Yeti-or requested changes

2023-01-23 08:10 UTC, Yeti-or commented on packages/plasma-ui/src/components/Tabs/TabsAnimationContext.tsx
> -    refs?: TabItemRefs;
это чтобы не создавать лишних объектов?

2023-01-23 08:10 UTC, Yeti-or requested changes
@arsenykruglikov я всё ещё не могу понять почему эти изменения в plasma-core а не в plasma-ui ?

2023-01-23 08:16 UTC, arsenykruglikov commented on packages/plasma-ui/src/components/Tabs/TabsAnimationContext.tsx
> -    refs?: TabItemRefs;
И объект не создаем и в useMemo нет нагромождения

2023-01-23 08:23 UTC, arsenykruglikov commented
@Yeti-or на счёт того, почему классы добавляются в `plasma-core`. Из-за того, что `plasma-ui` намертво завязана на оригинальные компоненты из `core`  и переиспользует в разных местах. Эти классы не влияют на стили, поэтому я не увидел препятствий, чтобы сделать именно так как сделано

2023-01-23 08:44 UTC, Yeti-or commented
@arsenykruglikov ну меня смущает что в plasma-web будет приезжать лишний код, я не совсем понял , в компонентах plasma-ui не получается докинуть классы? или что значит намертво

2023-01-23 09:09 UTC, arsenykruglikov commented
@Yeti-or 
> в компонентах plasma-ui не получается докинуть классы?

Можно, конечно, но придётся следить за тем, что в каждое использование соответствующих компонентов из `core` добавлен класс. А что если кто-то добавит новый тип кнопки и забудет проставить класс.

> или что значит намертво

Это значит, что пакет `ui` использует пакет `core` как основу и берёт базовые компоненты оттуда, иного даже просто делает реэкспорт даже не изменяя ничего

2023-01-23 10:50 UTC, arsenykruglikov commented
@Yeti-or @neretin-trike я переписал так, чтобы классы добавлялись только в plasma-ui

2023-01-23 10:54 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-285/

2023-01-23 10:55 UTC, Salute-Eva commented
**Component performance testing**

Result: **🌚 Missing base report**

Check out current report in job artifacts!

2023-01-23 11:04 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-285/

2023-01-23 11:12 UTC, neretin-trike commented
@arsenykruglikov По поводу Picker обсудили. Пришли к тому, что фокусироваться надо только на те "барабаны", что в середине

2023-01-23 11:24 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-285/

2023-01-23 11:25 UTC, Salute-Eva commented
**Component performance testing**

Result: **🔴 Fail**

Check out comparison report in job artifacts!

2023-01-23 11:42 UTC, Salute-Eva commented
**Component performance testing**

Result: **🔴 Fail**

Check out comparison report in job artifacts!

2023-01-23 15:40 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-285/

2023-01-23 15:48 UTC, Yeti-or commented on packages/plasma-ui/src/helpers/spatnavClassNameAttrs.ts
> +export const spatnavClassNameAttrs: { className?: string } = {
можешь только не в helpers а в utils положить – прости это наша не описанная папка, мы в helpers кладем все про stotybook =(

2023-01-23 15:58 UTC, Salute-Eva commented
**Component performance testing**

Result: **🔴 Fail**

Check out comparison report in job artifacts!

2023-01-23 16:05 UTC, Yeti-or commented on packages/plasma-ui/src/components/Button/Button.tsx
> +    return (
кстати тут не нужно:

```
const { className, ...res } = props;

return (
  <ButtonBase {...res} ref={ref} className={`${className} sn-section-item`} deviceScale={deviceScale} />
);
```

2023-01-23 17:48 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-285/

2023-01-23 18:05 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

2023-01-23 18:13 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-285/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-285/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-285/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-285/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-285/temple-storybook/

2023-01-24 08:15 UTC, Yeti-or commented
в Slider / Picker в итоге не нужны такие классы?

2023-01-24 23:50 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-285/

2023-01-25 00:01 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-285/

2023-01-25 00:07 UTC, Salute-Eva commented
**Component performance testing**

Result: **🔴 Fail**

Check out comparison report in job artifacts!

2023-01-25 00:13 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-285/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-285/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-285/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-285/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-285/temple-storybook/

2023-01-25 08:03 UTC, arsenykruglikov commented
@Yeti-or вроде бы всё, можно финально смотреть

2023-01-25 13:22 UTC, Yeti-or approved these changes

2023-01-25 13:30 UTC, merged