feat(plasma-tokens,plasma-tokens-utils): Add generating brand for each themes
salute-developers/plasma pull request #343
Opened 2023-02-14 14:48 UTC by neretin-trike

2023-02-14 15:01 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-343/

2023-02-14 15:05 UTC, Yeti-or approved these changes
Мне тут что то не нравится но объяснить что не могу :/

2023-02-14 15:05 UTC, Yeti-or commented on website/plasma-ui-docs/docs/design/tokens.mdx
> +    ${darkSbermarket[":root"]}
Вот это наши костыли же

2023-02-14 15:12 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

2023-02-14 15:13 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-343/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-343/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-343/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-343/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-343/temple-storybook/

2023-02-15 07:58 UTC, Yeti-or approved these changes

2023-02-15 08:10 UTC, neretin-trike commented on website/plasma-ui-docs/docs/design/tokens.mdx
> +    ${darkSbermarket[":root"]}
в итоге договорились, что разделю пример

2023-02-15 08:19 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-343/

2023-02-15 08:30 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-343/

2023-02-15 08:41 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-343/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-343/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-343/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-343/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-343/temple-storybook/

2023-02-15 08:44 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

2023-02-15 10:02 UTC, Yakutoc approved these changes

2023-02-15 10:07 UTC, Yeti-or requested changes

2023-02-15 10:07 UTC, Yeti-or commented on packages/plasma-tokens/package.json
> -        "prebuild": "rm -rf ./build ./colors ./es ./properties ./src ./themes ./themesValues ./typo ./typography ./typographyValues ./index.* ./theme.json",
А в files не надо добавить ?

2023-02-15 10:09 UTC, neretin-trike commented on packages/plasma-tokens/package.json
> -        "prebuild": "rm -rf ./build ./colors ./es ./properties ./src ./themes ./themesValues ./typo ./typography ./typographyValues ./index.* ./theme.json",
дак я files же удалил, вместо этого у нас сейчас .npmignore

2023-02-15 10:10 UTC, neretin-trike commented on packages/plasma-tokens/package.json
> -        "prebuild": "rm -rf ./build ./colors ./es ./properties ./src ./themes ./themesValues ./typo ./typography ./typographyValues ./index.* ./theme.json",
надо :/, спасибо

2023-02-15 10:13 UTC, Yeti-or approved these changes

2023-02-15 10:13 UTC, Yeti-or commented on website/plasma-ui-docs/docs/design/tokens.mdx
> +const Theme = createGlobalStyle(darkSbermarket);
👍

2023-02-15 10:16 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-343/

2023-02-15 10:25 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-343/

2023-02-15 10:35 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-343/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-343/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-343/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-343/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-343/temple-storybook/

2023-02-15 10:40 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out comparison report in job artifacts!

2023-02-15 11:02 UTC, merged