test(plasma-web):added Calendar,Dropdon,ElasticGrid,Modalf
salute-developers/plasma pull request #472
Opened 2023-04-07 09:42 UTC by Troff8

2023-04-07 09:46 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-07 12:22 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-07 12:23 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-07 12:39 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-07 12:44 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-07 13:12 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-10 09:39 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-10 14:12 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-10 14:41 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-04-10 14:42 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-04-10 15:11 UTC, akhdrv commented on packages/plasma-web/src/components/Calendar/Calendar.perftest.tsx
> +export const WithPopup = () => {
вот это целиком выпиливай, а то тестим не календарь, а обвязку

2023-04-10 15:13 UTC, akhdrv commented on packages/plasma-web/src/components/Calendar/Calendar.perftest.tsx
> +    const disabledDays = [...new Array(5)].map((_, day) => ({
это тоже вынести за компонент

2023-04-10 15:13 UTC, akhdrv commented on packages/plasma-web/src/components/Calendar/Calendar.perftest.tsx
> +    const date = {
и это

2023-04-10 15:16 UTC, akhdrv commented on packages/plasma-web/src/components/Calendar/Calendar.perftest.tsx
> +    const [value, setValue] = React.useState(new Date(2022, 5, 6));
это все нам не нужно, логика календаря не тестится. замени value на initialState который тут в скобках, а все функции которые прикидываются пропсами в Calendar замени на пустые функции и вынеси их за компонент

2023-04-10 15:17 UTC, akhdrv commented on packages/plasma-web/src/components/Calendar/Calendar.perftest.tsx
> +    const handleOnChange = React.useCallback((newValue: Date) => {
в Double и DoubleRange аналогично, все лишние колбеки и стейты заменяй на моки

2023-04-10 15:18 UTC, akhdrv commented on packages/plasma-web/src/components/Dropdown/Dropdown.perftest.tsx
> +export default {
не нужно

2023-04-10 15:21 UTC, akhdrv commented on packages/plasma-web/src/components/Dropdown/Dropdown.perftest.tsx
> +import { action } from '@storybook/addon-actions';
все что со \@storybook сразу выпиливай

2023-04-10 15:24 UTC, akhdrv commented on packages/plasma-web/src/components/Dropdown/Dropdown.perftest.tsx
> +const Styled25Rem = styled.div`
все стайлинги в этом модуле не нужны, заэкспорти один компонент, который будет рисовать Dropdown в минимальной комплектации, кажется тут нет вариантов

2023-04-10 15:25 UTC, akhdrv commented on packages/plasma-web/src/components/ElasticGrid/ElasticGrid.perftest.tsx
> +export default {
выпили все дефолтные экспорты с Meta

2023-04-10 15:29 UTC, akhdrv commented on packages/plasma-web/src/components/Modal/Modal.perftest.tsx
> +            <ModalView onClose={() => alert('Close!')}>
onClose и стили выше не нужны

2023-04-10 15:33 UTC, akhdrv commented on packages/plasma-web/src/components/Modal/Modal.perftest.tsx
> +export const LiveDemo = () => {
тут дофига логики, которая не используется. рефку можно оставить, а стейты/колбеки замокать

2023-04-10 15:34 UTC, akhdrv commented on packages/plasma-web/src/components/Tooltip/Tooltip.perfest.tsx
> +// const StyledRow = styled.div<SpacingProps>`
комменты выпилить

2023-04-10 18:39 UTC, Troff8 commented on packages/plasma-web/src/components/Dropdown/Dropdown.perftest.tsx
> +const Styled25Rem = styled.div`
Вот здесь не особо понял,просто в return все зависит от стайлингов

2023-04-10 19:49 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-10 20:00 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-04-10 20:07 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-04-10 20:20 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-04-11 06:47 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-04-11 06:51 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-04-11 07:09 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-04-11 09:21 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-11 09:31 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-04-11 09:51 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-04-11 09:53 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-04-11 10:13 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-11 10:26 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-04-11 10:32 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-04-11 10:43 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-04-12 05:20 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-12 05:46 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-04-12 05:53 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-04-12 06:05 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-12 06:15 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-04-12 06:32 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-04-12 09:49 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-12 10:17 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-04-12 10:40 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-04-12 12:48 UTC, akhdrv commented on packages/plasma-b2c/src/components/Modal/Modal.perftest.tsx
> +const isOpenA = false;
ничего не рисуется, оставь одну модалку с isOpen===true

2023-04-12 16:11 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-12 16:27 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-04-12 16:47 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-04-12 16:57 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-04-14 13:10 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-14 14:07 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-04-17 17:00 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-17 17:10 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-04-17 17:58 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-04-17 19:37 UTC, akhdrv approved these changes
нужно исправить перечисленное и ок

2023-04-17 19:37 UTC, akhdrv commented on packages/plasma-b2c/src/components/Badge/Babge.perftest.tsx
> +import React from 'react';
нейминг у файла

2023-04-17 19:37 UTC, akhdrv commented on packages/plasma-b2c/src/components/Checkbox/CheckBox.perftest.tsx
> +import React from 'react';
нейминг у файла

2023-04-17 19:37 UTC, akhdrv commented on packages/plasma-web/src/components/Badge/Babge.perftest.tsx
> +import React from 'react';
нейминг файла

2023-04-17 19:37 UTC, akhdrv commented on packages/plasma-web/src/components/Upload/Upload.perftest.tsx
> +            loader={<div style={{ color: 'green' }}>Кастомная загрузка {state.progress}%</div>}
style тут не нужен

2023-04-17 19:37 UTC, akhdrv commented on packages/plasma-web/src/components/Select/Select.perftest.tsx
> +            <Select id="example-empty-select" value={null} items={[]} placeholder="Пустой список" />
напоминаю

2023-04-17 19:37 UTC, akhdrv commented on packages/plasma-web/src/components/Select/Select.perftest.tsx
> +        <div style={{ display: 'grid', gap: '1rem', width: '20rem', gridTemplateColumns: '100%' }}>
style в константу или убери

2023-04-17 19:37 UTC, akhdrv commented on packages/plasma-web/src/components/Carousel/Carousel.perftest.tsx
> +                <CarouselItem key={item.id} style={{ width: '20rem', padding: '0 0.5rem' }}>
style в константу или убери

2023-04-17 19:37 UTC, akhdrv commented on packages/plasma-b2c/src/components/Upload/Upload.perftest.tsx
> +            loader={<div style={{ color: 'green' }}>Кастомная загрузка {state.progress}%</div>}
style

2023-04-17 19:37 UTC, akhdrv commented on packages/plasma-b2c/src/components/Select/Select.perftest.tsx
> +            <Select id="example-empty-select" value={null} items={[]} placeholder="Пустой список" />
items

2023-04-17 19:37 UTC, akhdrv commented on packages/plasma-b2c/src/components/Select/Select.perftest.tsx
> +            <Select value="test" items={items} onChange={() => {}} onFocus={func} onBlur={func} {...defaultProps} />
onchange

2023-04-17 19:37 UTC, akhdrv commented on packages/plasma-b2c/src/components/Select/Select.perftest.tsx
> +        <div style={{ display: 'grid', gap: '1rem', width: '20rem', gridTemplateColumns: '100%' }}>
style

2023-04-17 19:37 UTC, akhdrv commented on packages/plasma-b2c/src/components/ElasticGrid/ElasticGrid.perftest.tsx
> +            {arr.map((_, k) => (
[...Array(5)]

2023-04-17 19:38 UTC, akhdrv commented
удали merge коммит

2023-04-17 19:39 UTC, akhdrv commented
@Yeti-or @neretin-trike гляньте тоже плиз

2023-04-18 06:08 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-18 06:18 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-04-18 07:05 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-04-18 12:02 UTC, Troff8 commented
@Yeti-or @neretin-trike почему-то падает релиз и документация, я это не трогал,помогите плиз

2023-04-24 10:13 UTC, Yeti-or requested changes
Очень сложно ревьюить > 1700 строк изменений, разбей пожалуйста на атомарные коммиты, без фиксов ревью итпа, 

отребейзь еще от мастера, падает от того что твои изменения поменяли API библиотеки такое не должно было случиться, но понять почему пока не получается, нужно все отсмотреть

2023-04-24 10:22 UTC, akhdrv commented
@Yeti-or уточни пожалуйста, в чем именно сложность ревью, изменений много, но друг от друга эти модули не зависят. Насчет коммитов, атомарности по пакетам будет достаточно? То есть 3 пакета, в которых делались тесты, соответственно 3 коммита. Так норм?

2023-04-24 10:23 UTC, Yeti-or commented
Можно по компонентам можно по пакетам

On Mon, 24 Apr 2023 at 15:52, Artem Khaydarov ***@***.***>
wrote:

> @Yeti-or <https://github.com/Yeti-or> уточни пожалуйста, в чем именно
> сложность ревью, изменений много, но друг от друга эти модули не зависят.
> Насчет коммитов, атомарности по пакетам будет достаточно? То есть 3 пакета,
> в которых делались тесты, соответственно 3 коммита. Так норм?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/salute-developers/plasma/pull/472#issuecomment-1519858418>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAN2XXEU5LEVF2MFSUMB4LTXCZH65ANCNFSM6AAAAAAWWMVNIU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-24 10:24 UTC, akhdrv commented
И еще, этот ПР даже с approved review пока не поедет, решили сначала ускорить прогон тестов, а то, как видите, будет тратиться очень много времени

2023-04-24 10:26 UTC, Yeti-or commented
Давай тогда его в драфт переведём

On Mon, 24 Apr 2023 at 15:54, Artem Khaydarov ***@***.***>
wrote:

> И еще, этот ПР даже с approved review пока не поедет, решили сначала
> ускорить прогон тестов, а то, как видите, будет тратиться очень много
> времени
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/salute-developers/plasma/pull/472#issuecomment-1519861457>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAN2XXAF2L4IPYPXFFJT5LLXCZIHDANCNFSM6AAAAAAWWMVNIU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-25 10:30 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-25 10:41 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-04-25 11:33 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-04-26 17:24 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-26 17:28 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-26 17:40 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-04-26 17:40 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-04-26 17:44 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-26 17:55 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-04-26 18:07 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-04-26 18:12 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-04-26 18:18 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-26 18:20 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-26 18:22 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-04-26 18:25 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-04-26 18:42 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-04-26 18:46 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-04-27 10:29 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-27 10:42 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-27 10:45 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-04-27 10:53 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-04-27 10:57 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-04-27 11:01 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-04-28 09:11 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-05-01 03:26 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-05-01 03:37 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-05-02 10:14 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-05-02 10:25 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-05-02 10:29 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-05-04 11:03 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-05-04 11:14 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-05-04 11:29 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-05-04 11:44 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-05-04 12:04 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-05-04 14:05 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-05-04 14:13 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-05-04 17:21 UTC, akhdrv commented
@Yeti-or @neretin-trike гляньте плз

2023-05-10 11:08 UTC, KateKate commented on packages/plasma-b2c/src/components/Button/Button.perftest.tsx
> +} as any;
убрать as any

2023-05-10 11:09 UTC, KateKate commented on packages/plasma-b2c/src/components/Button/Button.perftest.tsx
> +const onBlur = () => {};
инициализировать по месту ниже
```js
const defaultProps = {
...
onClick: () => {},
onFocus: () => {},
onBlur: () => {},
```

2023-05-10 11:12 UTC, KateKate commented on packages/plasma-b2c/src/components/Checkbox/Checkbox.perftest.tsx
> +const func = () => {};
onFocus и onBlur не нужны, func везде использовать

2023-05-10 11:14 UTC, KateKate commented on packages/plasma-b2c/src/components/PreviewGallery/PreviewGallery.perftest.tsx
> +            {...selectableProps}
{...selectableProps} - зачем? убери, не имеет смысла

2023-05-10 11:14 UTC, KateKate commented on packages/plasma-b2c/src/components/PreviewGallery/PreviewGallery.perftest.tsx
> +            {...draggableProps}
то же самое

2023-05-10 11:18 UTC, Troff8 commented on packages/plasma-b2c/src/components/Button/Button.perftest.tsx
> +} as any;
is any вроде стоит т.к в этом объекте есть поля - функции

2023-05-10 12:55 UTC, KateKate commented on packages/plasma-b2c/src/components/Button/Button.perftest.tsx
> +} as any;
и как это связано? any - это по сути убираешь проверку на TS типы

2023-05-11 10:47 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-05-11 11:04 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-05-11 11:07 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-05-11 11:21 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-05-11 11:34 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-05-11 11:39 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-05-11 11:40 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-05-11 11:56 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-05-11 12:06 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-05-11 18:55 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-05-11 19:05 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-05-11 19:25 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-05-11 19:32 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-05-16 15:41 UTC, KateKate approved these changes

2023-05-17 06:54 UTC, neretin-trike commented
судя по коду самих тестов, кажется, что он идентичный для библиотек plasma-web и plasma-b2c. Поэтому такой вопрос (просьба): а есть ли возможность перенести перф тесты для plasma-web / b2c на уровень plasma-hope? Дело в том, что в компонентах библиотек нет никакой бизнес логики, а только (в основном) ре-экспорты из plasma-hope. И соотвественно если будут какие-то изменения в компонентах, то они появятся и в plasma-web и в plasma-b2c

2023-05-17 07:49 UTC, akhdrv commented
Даже учитывая, что в web/b2c реэкспорты, тесты должны быть на компоненты которые непосредственно используются в проектах. Вы же не делаете cypress тесты на hope

2023-05-17 08:08 UTC, akhdrv commented
Если вы паритесь за время выполнения джобы, то perftool еще будет ускоряться

2023-05-17 08:14 UTC, Yakutoc commented on package.json
> +    "typescript": "5.0.4",
А почему тут версия typescript **меняется**?

2023-05-17 08:17 UTC, akhdrv commented on package.json
> +    "typescript": "5.0.4",
это быстрофикс для perftool. он использует ts-node, а ts-node подтягивает проектный typescript вместо пакетного. фикс на это будет позже, а пока вот так. версия не меняется в пакетах, ничего судя по всему не сломалось. если вдруг с этим будут проблемы — отревертим и буду фиксить уже в пакете

2023-05-17 08:21 UTC, Yakutoc approved these changes

2023-05-17 09:02 UTC, Yeti-or commented
> Если вы паритесь за время выполнения джобы, то perftool еще будет ускоряться

нет мы беспокоимся за дублирование тестов, можно же их положить на уровень plasma-hope и сделать симлинки, но в целом это можно сделать позже

2023-05-17 09:02 UTC, akhdrv commented on packages/plasma-b2c/src/components/Calendar/Calendar.perftest.tsx
> +    type: undefined,
возможно это лишнее, @Troff8 проверь

2023-05-17 09:04 UTC, akhdrv commented on packages/plasma-b2c/src/components/PreviewGallery/PreviewGallery.perftest.tsx
> +const images: Array<PreviewGalleryItemProps> = [
не, тут другая семантика и формат. должна быть возможность редактировать это на месте

2023-05-17 09:06 UTC, akhdrv commented on packages/plasma-b2c/src/components/Select/Select.perftest.tsx
> +export const Default = () => {
значит в Calendar есть разные виды/изначальные состояния компонента, которые рендерятся за разное время. если тут тоже нужно что-то конкретное протестить то давай сделаем тудушку

2023-05-17 09:06 UTC, akhdrv commented on packages/plasma-ui/src/components/Button/Button.perftest.tsx
> +} as any;
outdated, тут уже as const

2023-05-17 09:08 UTC, akhdrv commented on packages/plasma-web/src/components/Modal/Modal.perftest.tsx
> +const longText = `Если после применения правила Лопиталя неопределённость типа 0 / 0 осталась, мнимая единица традиционно
вообще количество текста вряд ли значительно повлияет на рендеринг, но можно добавить для однообразия

2023-05-17 09:09 UTC, akhdrv commented on packages/plasma-b2c/src/components/Switch/Switch.perftest.tsx
> -import { Switch, SwitchProps } from '.';
?

2023-05-17 09:09 UTC, akhdrv commented on packages/plasma-b2c/tsconfig.json
> -    "exclude": ["./src/__helpers", "./src/**/*.stories.tsx", "./src/**/*.component-test.tsx"]
не попадает

2023-05-17 09:11 UTC, akhdrv commented on packages/plasma-web/src/components/Select/Select.perftest.tsx
> +            <Select id="example-empty-select" value={null} items={[]} placeholder="Пустой список" />
@Troff8 вынеси в константу!

2023-05-17 09:14 UTC, akhdrv commented on packages/plasma-b2c/src/components/Button/Button.perftest.tsx
> +} as any;
тут уже any убрали и на as const поменяли

2023-05-17 09:38 UTC, Yeti-or commented on packages/plasma-b2c/src/components/PreviewGallery/PreviewGallery.perftest.tsx
> +const images: Array<PreviewGalleryItemProps> = [
понял, 👌

2023-05-17 09:40 UTC, akhdrv commented on packages/plasma-b2c/src/components/Carousel/Carousel.perftest.tsx
> +import { Headline4, Footnote1 } from '../Typography';
@Troff8 нужно поменять везде типографию тогда

2023-05-17 09:44 UTC, Yeti-or commented on packages/plasma-b2c/src/components/Select/Select.perftest.tsx
> +export const Default = () => {
давайте разделим на multiselect и обычный

2023-05-17 09:46 UTC, Yeti-or commented on packages/plasma-ui/src/components/Button/Button.perftest.tsx
> +} as any;
я смотрел по коммитам, по тому что много изменений и именно для такого просил их делать атомарными

2023-05-17 09:48 UTC, Yeti-or commented on packages/plasma-b2c/src/components/Switch/Switch.perftest.tsx
> -import { Switch, SwitchProps } from '.';
https://github.com/salute-developers/plasma/pull/472/commits/7758d0d62196d0d8086eaa42cb12cfd0bab4a75a
https://github.com/salute-developers/plasma/pull/472/commits/b00e255cbe10342ae2a2a5fa9798a82a63fd1b07

2023-05-17 09:55 UTC, akhdrv commented on packages/plasma-b2c/src/components/Switch/Switch.perftest.tsx
> -import { Switch, SwitchProps } from '.';
в смысле склеить хочется?

2023-05-17 09:58 UTC, Yeti-or commented on packages/plasma-b2c/src/components/Switch/Switch.perftest.tsx
> -import { Switch, SwitchProps } from '.';
Ну да, оно же невнесение смысла по отдельности, типа тут добавил а вот тут починил, 'git rebase -i origin/master' ведь это быстро помогает формировать пулл реквест

2023-05-17 10:14 UTC, Yeti-or commented on packages/plasma-b2c/src/components/Carousel/Carousel.perftest.tsx
> +import { Headline4, Footnote1 } from '../Typography';
Давайте ограничемся комментарием

// TODO: #507

2023-05-17 10:26 UTC, Troff8 commented on packages/plasma-b2c/src/components/Carousel/Carousel.perftest.tsx
> +import { Headline4, Footnote1 } from '../Typography';
комментарий куда поставить ? перед импортом ?

2023-05-17 10:37 UTC, akhdrv commented on packages/plasma-b2c/src/components/Carousel/Carousel.perftest.tsx
> +import { Headline4, Footnote1 } from '../Typography';
да

2023-05-17 13:52 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-05-17 14:01 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-05-17 14:02 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-05-17 14:11 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-05-17 14:11 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-05-17 14:22 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-05-17 14:42 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-05-19 12:55 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-05-19 13:08 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-05-19 14:38 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-05-19 14:48 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-05-19 14:56 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-05-19 20:23 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-05-19 20:32 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-05-19 20:45 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-05-20 09:39 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-05-20 09:49 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-05-20 09:58 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-05-20 10:45 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-05-20 10:54 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-05-20 11:01 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-05-20 11:36 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-05-20 12:08 UTC, akhdrv commented on .github/workflows/performance-test.yml
> +                    if (metric.mean && metric.mean.change && metric.mean.change.significanceRank !== 'high') {
достаточно только проверки metric.mean.change

2023-05-20 12:09 UTC, akhdrv commented on .github/workflows/performance-test.yml
> +                    if (metric.mean && metric.mean.change && metric.mean.change.percentage){
эту проверку целиком убери. если есть change, то есть и percentage

2023-05-20 12:09 UTC, akhdrv commented on packages/plasma-web/src/components/Select/Select.perftest.tsx
> +const itemsVoid = [];
просто items

2023-05-20 12:13 UTC, akhdrv commented on .github/workflows/performance-test.yml
> +                    if (metric.mean && metric.mean.change && metric.mean.change.significanceRank !== 'high') {
тут неправильное условие. если metric.mean.change falsy, то тебе тоже нужно заходить в условие, чтобы вызвался return

2023-05-20 12:13 UTC, akhdrv commented on .github/workflows/performance-test.yml
> +                    if (metric.mean && metric.mean.change && metric.mean.change.significanceRank !== 'high') {
```suggestion
                    if (!metric.mean.change || metric.mean.change.significanceRank !== 'high') {
```

2023-05-20 14:16 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-05-20 14:31 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-05-20 14:34 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-05-20 15:05 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-05-20 16:18 UTC, akhdrv commented on packages/plasma-web/src/components/Select/Select.perftest.tsx
> -const items = [
зачем ты это удалил) я не видел, что items уже есть. назови как-нибудь по-другому пустой массив, а это верни

2023-05-20 16:19 UTC, akhdrv commented on .github/workflows/performance-test.yml
> +                    if (!metric.mean.change || metric.mean.change.significanceRank !== 'high'){
верни отступы и пробел между круглой и фигурной скобкой, как было до этого

2023-05-20 16:20 UTC, akhdrv commented on .github/workflows/performance-test.yml
> +
верни после этой строки все как было

2023-05-20 17:09 UTC, Troff8 commented on .github/workflows/performance-test.yml
> +
вернуть как было у Арсения? после этой строчки

2023-05-20 17:34 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-05-20 17:43 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-05-20 17:50 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-05-20 17:56 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-05-20 17:59 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-05-20 18:03 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-05-20 18:08 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-05-20 18:16 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/pr/demo-canvas-app-pr-472/

2023-05-20 18:19 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

Top 5 significant render changes:
packages/plasma-ui/src/components/Pickers/Pickers.perftest.tsx#TimePicker: -29.74%
packages/plasma-ui/src/components/Pickers/Pickers.perftest.tsx#DatePicker: -28.35%
packages/plasma-ui/src/components/Pickers/Pickers.perftest.tsx#Default: -27.36%

2023-05-20 18:20 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-05-20 18:28 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-05-20 18:40 UTC, Salute-Eva commented
**Component performance testing**

Result: **🔴 Fail**

Check out report in job artifacts!

Top 5 significant rerender changes:
packages/plasma-ui/src/components/Carousel/Carousel.perftest.tsx#Basic: 47.38%
packages/plasma-ui/src/components/Carousel/Carousel.perftest.tsx#CarouselLiteBasic: 34.75%

2023-05-22 09:12 UTC, Yeti-or approved these changes

2023-05-22 15:17 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-472/

2023-05-22 15:37 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-472/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-472/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-472/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-472/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-472/temple-storybook/

2023-05-22 17:01 UTC, merged