feat(plasma-web): Add `Calendar` component
salute-developers/plasma pull request #51
Opened 2022-06-06 14:45 UTC by Yeti-or

пересоздал: https://github.com/salute-developers/plasma/pull/45

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.75.0-canary.51.2515156621.0
  npm install @salutejs/plasma-web@1.110.0-canary.51.2515156621.0
  # or 
  yarn add @salutejs/plasma-b2c@1.75.0-canary.51.2515156621.0
  yarn add @salutejs/plasma-web@1.110.0-canary.51.2515156621.0
  ```
</details>

2022-06-06 15:25 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-51/

2022-06-09 07:09 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-51/

2022-06-09 07:24 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-51/
  ui storybook: http://plasma.sberdevices.ru/pr-51/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-51/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-51/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-51/temple-storybook/

2022-06-09 12:19 UTC, kvpolyanskiy commented on packages/plasma-web/src/components/Calendar/Calendar.component-test.tsx
> +        cy.get('div > div > div > div').first().click();
Дата атрибут нельзя добавить?

2022-06-09 12:39 UTC, kvpolyanskiy requested changes

2022-06-09 12:39 UTC, kvpolyanskiy commented on packages/plasma-web/src/components/Calendar/utils.ts
> +export const SHORT_DAY_NAMES = ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'];
Получается мы жестко завязались на русский?  Если у нас нет привязки библиотеки только к русскому, то наверное нужно иметь возможность указывать локаль или по умолчанию автоматически ее определять и выводить имена в зависимости от локали?

2022-06-10 07:25 UTC, Yeti-or commented on packages/plasma-web/src/components/Calendar/utils.ts
> +];
```js


const date = new Date(2020, 0, 1);

function getShortMonths(locale = 'ru') {
    const formatter = new Intl.DateTimeFormat(locale, { month: 'short' });

    return Array.from(Array(12), (_,i) => formatter.format(date.setMonth(i)));
}

function getShortWeekDays(locale = 'ru') {
    const formatter = new Intl.DateTimeFormat(locale, { weekday: 'short' });

    return Array.from(Array(7), (_,i) => formatter.format(date.setDate(i + 6)));
}

function getMonths(locale = 'ru') {
    const formatter = new Intl.DateTimeFormat(locale, { month: 'long' });

    return Array.from(Array(12), (_,i) => formatter.format(date.setMonth(i)));
}


console.log(getShortMonths());
console.log(getShortWeekDays());
console.log(getMonths());
```

2022-06-10 11:18 UTC, neretin-trike commented on packages/plasma-web/src/components/Calendar/Calendar.component-test.tsx
> +        cy.get('div > div > div > div').first().click();
да можно по-идее, но мы почему-то нигде их не добавляем, и вместо этого городим сложные селекторы

2022-06-10 11:18 UTC, neretin-trike commented on packages/plasma-web/src/components/Calendar/utils.ts
> +export const SHORT_DAY_NAMES = ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'];
резонное замечание. Но мы пока решили оставить такой вариант, и в дальнейшем вернуться к вопросу локализации уже в следующих итерациях

2022-06-10 11:19 UTC, neretin-trike commented on packages/plasma-web/src/components/Calendar/utils.ts
> +];
сохраним на будущее

2022-06-10 11:49 UTC, kvpolyanskiy approved these changes

2022-06-10 11:50 UTC, kvpolyanskiy commented on packages/plasma-web/src/components/Calendar/Calendar.component-test.tsx
> +        cy.get('div > div > div > div').first().click();
ок, но наверное стоит все-таки добавлять?

2022-06-16 12:54 UTC, Yeti-or commented on packages/plasma-web/src/components/Calendar/Calendar.component-test.tsx
> +    // TODO: Перетащить подключение StandardTypoStyle в @salutejs/plasma-cy-utils
добавь сюда плиз: https://github.com/salute-developers/plasma/issues/69

2022-06-16 12:54 UTC, Yeti-or commented on packages/plasma-web/src/components/Calendar/CalendarDayItem.tsx
> +    tabIndex?: number;
тут точно должен быть tabIndex ? мы вроде говорили что это таб ставится на весь компонент?

2022-06-16 12:54 UTC, Yeti-or commented on packages/plasma-web/src/components/Calendar/CalendarDays.tsx
> +            const { day, monthIndex, year } = event.currentTarget.dataset;
а это быстрее чем прокидывать на каждом элементе данные в onClick ?

2022-06-16 12:54 UTC, Yeti-or commented on packages/plasma-web/src/components/Calendar/CalendarHeader.tsx
> +            return `${startYear}—${startYear + YEAR_RENDER_COUNT}`;
`YEAR_RENDER_COUNT - 1` ?

2022-06-16 12:54 UTC, Yeti-or commented on packages/plasma-web/src/components/Calendar/CalendarHeader.tsx
> +            return currentDate.year;
тут наверно стоит тоже к строке привести ?

2022-06-16 12:54 UTC, Yeti-or commented on packages/plasma-web/src/components/Calendar/CalendarHeader.tsx
> +        return 'Unknown';
давай может просто `''`; че лишнии байтики плодить

2022-06-16 12:54 UTC, Yeti-or commented on packages/plasma-web/src/components/Calendar/hooks.ts
> +    return [...new Array(offsetDayInWeek)].map((_, i) => ({
`return Array.from(Array(offsetDayInWeek), (_, i) => ({ ... }));`

2022-06-16 12:54 UTC, Yeti-or commented on packages/plasma-web/src/components/Calendar/CalendarYears.tsx
> +        selected({
выгляди сложно конечно

2022-06-16 12:54 UTC, Yeti-or commented on packages/plasma-web/src/components/Calendar/mixins.ts
> +        ${StyledItem} {
ох я понял почему так сложно

2022-06-17 07:59 UTC, neretin-trike commented on packages/plasma-web/src/components/Calendar/CalendarDayItem.tsx
> +    tabIndex?: number;
ага, по w3.org у элемента дня есть `tabIndex`, но у всех должно быть -1 кроме выбранного дня

2022-06-17 08:04 UTC, neretin-trike commented on packages/plasma-web/src/components/Calendar/CalendarDays.tsx
> +            const { day, monthIndex, year } = event.currentTarget.dataset;
решили оставить пока такой вариант, т.к. в дальнейшем всё-равно придётся обращаться к data- атрибутам для реализации доступности

2022-06-17 10:07 UTC, neretin-trike commented on packages/plasma-web/src/components/Calendar/hooks.ts
> +    [...new Array(daysInMonth)].map((_, i) => ({
ну по-идее пересчёт случится только если date или value изменился. В целом можно подумать над оптимизацией, но я бы пока так оставил

2022-06-17 10:53 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-51/

2022-06-17 11:06 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-51/
  ui storybook: http://plasma.sberdevices.ru/pr-51/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-51/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-51/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-51/temple-storybook/

2022-06-17 11:31 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-51/

2022-06-17 11:45 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-51/
  ui storybook: http://plasma.sberdevices.ru/pr-51/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-51/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-51/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-51/temple-storybook/

2022-06-17 12:01 UTC, merged