plasma-infra: improve perftest workflow
salute-developers/plasma pull request #553
Opened 2023-06-08 10:18 UTC by Yakutoc

2023-06-08 13:37 UTC, Salute-Eva commented
**Component performance testing**

Result: **🔴 Fail**

Check out report in job artifacts!

Top 5 significant render changes:
packages/plasma-ui/src/components/Pickers/Pickers.perftest.tsx#DatePicker: 29.85%
packages/plasma-ui/src/components/Pickers/Pickers.perftest.tsx#TimePicker: 23.34%
packages/plasma-ui/src/components/Pickers/Pickers.perftest.tsx#Default: 21.28%
Top 5 significant rerender changes:
packages/plasma-web/src/components/Select/Select.perftest.tsx#Default: -19.76%

2023-06-08 14:06 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-06-09 04:58 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-06-09 08:58 UTC, Salute-Eva commented
**Component performance testing**

Result: **🟢 Success**

Check out report in job artifacts!

2023-06-14 11:02 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr/pr-553/
  ui storybook: http://plasma.sberdevices.ru/pr/pr-553/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr/pr-553/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr/pr-553/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr/pr-553/temple-storybook/

2023-06-14 11:08 UTC, Yeti-or approved these changes

2023-06-14 11:08 UTC, Yeti-or commented on .github/workflows/performance-test.yml
> +    uses: ./.github/workflows/performance-test-processing.yml
а нужно ли здесь выносить в отдельную джобу?

2023-06-14 11:11 UTC, akhdrv requested changes
Неок, к сожалению так делать плохо — при прогоне в разных сессиях получаются большие ошибки и расхождения по значениям, так уже делали раньше. От перфтестов просто смысла не будет

2023-06-14 11:27 UTC, closed without merging