feat(plasma-core): Extract `Card` component to plasma-core
salute-developers/plasma pull request #70
Opened 2022-06-16 16:00 UTC by neretin-trike

<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @salutejs/plasma-b2c@1.77.0-canary.70.2534394414.0
  npm install @salutejs/plasma-core@1.62.0-canary.70.2534394414.0
  npm install @salutejs/plasma-icons@1.87.0-canary.70.2534394414.0
  npm install @salutejs/plasma-temple@1.75.0-canary.70.2534394414.0
  npm install @salutejs/plasma-typo@0.9.0-canary.70.2534394414.0
  npm install @salutejs/plasma-ui@1.111.0-canary.70.2534394414.0
  npm install @salutejs/plasma-web@1.112.0-canary.70.2534394414.0
  npm install @salutejs/plasma-cy-utils@0.15.0-canary.70.2534394414.0
  npm install @salutejs/plasma-sb-utils@0.61.0-canary.70.2534394414.0
  # or 
  yarn add @salutejs/plasma-b2c@1.77.0-canary.70.2534394414.0
  yarn add @salutejs/plasma-core@1.62.0-canary.70.2534394414.0
  yarn add @salutejs/plasma-icons@1.87.0-canary.70.2534394414.0
  yarn add @salutejs/plasma-temple@1.75.0-canary.70.2534394414.0
  yarn add @salutejs/plasma-typo@0.9.0-canary.70.2534394414.0
  yarn add @salutejs/plasma-ui@1.111.0-canary.70.2534394414.0
  yarn add @salutejs/plasma-web@1.112.0-canary.70.2534394414.0
  yarn add @salutejs/plasma-cy-utils@0.15.0-canary.70.2534394414.0
  yarn add @salutejs/plasma-sb-utils@0.61.0-canary.70.2534394414.0
  ```
</details>

2022-06-17 06:54 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-70/

2022-06-17 07:14 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-70/
  ui storybook: http://plasma.sberdevices.ru/pr-70/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-70/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-70/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-70/temple-storybook/

2022-06-17 11:00 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-70/

2022-06-17 11:11 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-70/
  ui storybook: http://plasma.sberdevices.ru/pr-70/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-70/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-70/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-70/temple-storybook/

2022-06-17 14:22 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-70/
  ui storybook: http://plasma.sberdevices.ru/pr-70/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-70/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-70/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-70/temple-storybook/

2022-06-20 08:07 UTC, LamaEats commented on packages/plasma-core/src/components/Card/CardBody.tsx
> +export const CardBody: React.FC<CardBodyProps> = ({ children, className, ...rest }) => {
А почему бы просто сразу стайлед компонент не экспортировать?

2022-06-20 08:07 UTC, LamaEats commented on packages/plasma-core/src/components/Card/CardContent.tsx
> +export const CardContent: React.FC<CardContentProps> = ({ cover, coverGradient = true, children, ...rest }) => {
да и здесь так же можно, что бы не создавать дополнительные компоненты

2022-06-20 08:07 UTC, LamaEats commented on packages/plasma-core/src/components/Card/CardMedia.tsx
> +            {children}
кажется тут не нужны дочерние компоненты

2022-06-20 09:00 UTC, Yeti-or requested changes

2022-06-20 09:03 UTC, neretin-trike commented on website/plasma-web-docs/docs/components/Card.mdx
> +                    <CardMedia src={src} placeholder={src} ratio="1/1" />
так, а это я удалил у себя, но не запушил, сорян

2022-06-20 09:08 UTC, neretin-trike commented on packages/plasma-core/src/components/Card/CardBody.tsx
> +export const CardBody: React.FC<CardBodyProps> = ({ children, className, ...rest }) => {
так то хороший вопрос, но у нас почему-то сделано именно так. Если я в `styled-component` переделаю, обратная совместимость нигде не сломается?

2022-06-20 09:08 UTC, neretin-trike commented on packages/plasma-core/src/components/Card/CardContent.tsx
> +export const CardContent: React.FC<CardContentProps> = ({ cover, coverGradient = true, children, ...rest }) => {
тот же вопрос 🤔

2022-06-20 09:09 UTC, neretin-trike commented on packages/plasma-core/src/components/Card/CardMedia.tsx
> +            {children}
почему не нужны?

2022-06-20 10:47 UTC, Yeti-or commented on packages/plasma-core/src/components/Card/Card.component-test.tsx
> +describe('plasma-core: Card', () => {
а как так ? почему там другие?

может нужно как тут: https://github.com/salute-developers/plasma/tree/master/packages/plasma-ui/src/components/Badge

разделить на те что чисто под web и общие

2022-06-20 10:48 UTC, Yeti-or commented on website/plasma-web-docs/docs/components/Card.mdx
> +                    <CardMedia src={src} placeholder={src} ratio="1/1" />
https://plasma.sberdevices.ru/pr-70/web/components/card

дока с этим сломана

2022-06-20 10:49 UTC, Yeti-or commented on packages/plasma-core/src/components/Card/CardBody.tsx
> +export const CardBody: React.FC<CardBodyProps> = ({ children, className, ...rest }) => {
Согласен с @LamaEats

2022-06-20 10:49 UTC, Yeti-or commented on packages/plasma-core/src/components/Card/CardMedia.tsx
> +            {children}
а тут давайте не менять

2022-06-20 10:51 UTC, neretin-trike commented on packages/plasma-core/src/components/Card/Card.component-test.tsx
> +describe('plasma-core: Card', () => {
чисто под web один простецкий тест в котором используются базовые компоненты.
В ui же юзаются сложные компоненты, которые сделаны специально для этой карточки типа - TextBox, CardTypography и т.д., соотвественно их не получится затащить

2022-06-20 10:53 UTC, neretin-trike commented on packages/plasma-core/src/components/Card/Card.component-test.tsx
> +describe('plasma-core: Card', () => {
могу в принципе их в web продублировать, но мне кажется это излишним

2022-06-20 10:55 UTC, neretin-trike commented on packages/plasma-core/src/components/Card/CardBody.tsx
> +export const CardBody: React.FC<CardBodyProps> = ({ children, className, ...rest }) => {
оке, сделаю 👌

2022-06-20 10:55 UTC, neretin-trike commented on website/plasma-web-docs/docs/components/Card.mdx
> +                    <CardMedia src={src} placeholder={src} ratio="1/1" />
ага, поэтому и говорю, что поменял, но не пушнул прост. Спасиб, что напомнил

2022-06-21 09:32 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-70/

2022-06-21 09:39 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-70/

2022-06-21 09:43 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-70/
  ui storybook: http://plasma.sberdevices.ru/pr-70/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-70/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-70/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-70/temple-storybook/

2022-06-21 09:46 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-70/

2022-06-21 09:48 UTC, Yeti-or approved these changes

2022-06-21 09:53 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-70/
  ui storybook: http://plasma.sberdevices.ru/pr-70/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-70/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-70/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-70/temple-storybook/

2022-06-21 10:15 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-70/
  ui storybook: http://plasma.sberdevices.ru/pr-70/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-70/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-70/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-70/temple-storybook/

2022-06-21 10:52 UTC, merged