Nikewht.new hope.switch
salute-developers/plasma pull request #816
Opened 2023-10-20 06:22 UTC by nikewht

Добавлена реализация компонента Switch

2023-10-20 06:25 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-816/

2023-10-20 06:35 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-816/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-816/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-816/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-816/new-hope-storybook/

2023-10-20 09:22 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-816/

2023-10-23 07:48 UTC, Yeti-or commented on packages/plasma-new-hope/src/examples/sds_engineer/components/Switch/Switch.ts
> +export const Switch = component(mergedConfig);
no newline 
eslint не сработал?

2023-10-23 07:53 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-816/

2023-10-23 08:02 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-816/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-816/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-816/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-816/new-hope-storybook/

2023-10-23 12:23 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-816/

2023-10-23 13:35 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-816/

2023-10-23 13:42 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-816/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-816/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-816/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-816/new-hope-storybook/

2023-10-24 09:49 UTC, kayman233 approved these changes

2023-10-24 10:03 UTC, Yeti-or reviewed
Все же по хорошему, было бы круто заменить, Switch внутри plasma-b2c и plasma-web на вот этот, чтобы мы поняли что все корректно покрыто, типо как в ссылке: https://github.com/salute-developers/plasma/blob/dev/packages/plasma-b2c/src/components/Link/Link.tsx#L1

ну либо можем это сделать отдельным пр конечно

cc @neretin-trike

2023-10-24 10:03 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/Switch/_focused/base.ts
> +    input[type='checkbox'][data-focus-visible-added]:indeterminate + label .switch-trigger {
`indeterminate` ?  это точно тут должно быть? 
это какое состояние в целом?

2023-10-24 10:03 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/Switch/_size/base.ts
> +    font-size: var(--plasma-switch-font-size);
а остальное типографическое не нужно ?

2023-10-24 10:04 UTC, Yeti-or commented on packages/plasma-new-hope/src/examples/sds_engineer/components/Switch/Switch.ts
> +export const Switch = component(mergedConfig);
надо разобраться таки с  WebStorm и линтерами, @Yakutoc как вернешься из отпуска расскажи как ты в WebStorm комитешь и не было ли проблем с  husky pre-commit

2023-10-25 09:01 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/sds_engineer/components/Switch/Switch.config.ts
> +                --plasma-switch-trigger-border-radius: 0.975rem;
переведи пожалуйста все css-переменные в js токены, как это сделано [тут](https://github.com/salute-developers/plasma/blob/7b3f9f569fd87503e9dd7eec7f07766c9f78c4ea/packages/plasma-new-hope/src/examples/sds_engineer/components/TextArea/TextArea.config.ts) 

так же нужно будет создать файл Switch.tokens.ts, в котором эти токены будут храниться, как [здесь](https://github.com/salute-developers/plasma/blob/7b3f9f569fd87503e9dd7eec7f07766c9f78c4ea/packages/plasma-new-hope/src/components/TextArea/TextArea.tokens.ts)

2023-10-25 09:08 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/sds_engineer/components/Switch/Switch.config.ts
> +                --plasma-switch-trigger-background: rgba(30, 131, 198, 0.11);
кажется, что эти значения нужно перенести в sds_engineer.css. Я это [сделал](https://github.com/salute-developers/plasma/blob/7b3f9f569fd87503e9dd7eec7f07766c9f78c4ea/packages/plasma-new-hope/src/examples/themes/sds_engineer.module.css#L61) для компонента TextArea, и просто пометил. что эти токены добавлены в ручную. Это нужно для того, чтобы в будущем при подключении вашей темы (и например изменения значения в ней) в компоненте цвета так же обновились

2023-10-25 09:14 UTC, neretin-trike commented on packages/plasma-new-hope/src/examples/sds_engineer/components/Switch/Switch.config.ts
> +                --plasma-switch-font-size: 14px;
но скорее всего эти значения вообще нужно забирать из нашей типографики, как [здесь](https://github.com/salute-developers/plasma/blob/7b3f9f569fd87503e9dd7eec7f07766c9f78c4ea/packages/plasma-new-hope/src/examples/sds_engineer/components/TextArea/TextArea.config.ts#L25)

2023-10-25 09:15 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Switch/_focused/tokens.json
> +    "tokens": ["--plasma-switch-focus-color", "--plasma-switch-trigger-border-radius"]
кажется, `--plasma-switch-trigger-border-radius` должен лежать в '_size/tokens.json'

2023-10-25 09:17 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Switch/Switch.tsx
> +const StyledTrigger = styled.div`
вынеси пожалуйста все `styled` компоненты со стилями в файл Swith.style.ts

2023-10-25 09:18 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Switch/Switch.tsx
> +    &:active div::after {
тут лучше обращаться не к div, а задать этому DOM элементу класс нейм

2023-10-25 09:18 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Switch/Switch.tsx
> +            props.disabled ? 'var(--plasma-switch-ellipse-size)' : 'var(--plasma-switch-trigger-height)'};
можно применить деструктуризацию на пропс

2023-10-25 09:20 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Switch/Switch.tsx
> +        box-shadow: 0 0 4px 0 rgba(70, 106, 251, 0.71);
значения 4px и rgba(70, 106, 251, 0.71) я бы вынес в css-переменные

2023-10-25 09:22 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Switch/_disabled/base.ts
> +    input:checked:disabled + label div {
я бы единообразно всё сделал, и везде бы заменил HTML тэги на соответствующие классы + вынес бы их в файл Switch.tokens.ts, как [тут](https://github.com/salute-developers/plasma/blob/7b3f9f569fd87503e9dd7eec7f07766c9f78c4ea/packages/plasma-new-hope/src/components/TextArea/TextArea.tokens.ts#L1)

2023-10-25 09:24 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Switch/Switch.tsx
> +    &::after {
а вообще кажется, что этот код можно попробовать перенсти в _view/base.ts, там как раз у тебя есть миксин для фокуса. Просто нужно будет его применить в компоненте `StyledTrigger` (для этого задать ему className)

2023-10-25 09:25 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Switch/_view/base.ts
> +    input:checked + label div {
здесь и выше тоже нужно на классы заменить

2023-10-25 12:38 UTC, nikewht commented on packages/plasma-new-hope/src/components/Switch/Switch.tsx
> +const StyledTrigger = styled.div`
У Popover файл со `styled components` лежит в файле `./styles/index.ts` https://github.com/salute-developers/plasma/blob/dev/packages/plasma-new-hope/src/components/Popover/styles/index.ts

Сделать как у popover или все же в ./Switch.style.ts ?

2023-10-25 13:49 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Switch/Switch.tsx
> +const StyledTrigger = styled.div`
да, мы изменили файловую структуру компонент и теперь все новые (а так же чуть позже старые) будут в новом формате

2023-10-27 13:21 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-816/

2023-10-27 13:30 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-816/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-816/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-816/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-816/new-hope-storybook/

2023-10-28 11:00 UTC, Yeti-or approved these changes
Нужен ok @neretin-trike  и можно вливать

2023-10-30 05:53 UTC, Yakutoc approved these changes

2023-10-30 05:56 UTC, Yakutoc commented on packages/plasma-new-hope/src/components/Switch/_focused/base.ts
> +const addFocus = (outlineOffset: string, outlineSize: string, outlineRadius: string, outlineColor = '') => {
[Уточнение]

@nikewht 

У нас есть в `packages/plasma-core/src/mixins/addFocus.ts`  mixin, он не подходит тебе?

2023-10-30 18:27 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Switch/_disabled/base.ts
> +const { styledInputClass, styledContentWrapperClass, styledTriggerClass } = switchClasses;
@nikewht спасибо, что поправил все основные замечания! 

Но возник вопрос, как этот компонент будет работать со styled-component. Сейчас при билде и сборке в сторибуке это происходит через linaria.  В итоге я склонировал твою веточку себе и попробовал это проверить на нашей библиотеке plasma-web (которая лежит по пути ./packages/plasma-web):
1. Я заменил текущую реализацию компонента Switch этой библиотеки на твою из plasma-new-hope:

`./packages/plasma-web/src/components/Switch/Switch.tsx`
```ts
import { switchConfig, component, mergeConfig } from '@salutejs/plasma-new-hope/styled-components';

import { config } from './Switch.config';

const mergedConfig = mergeConfig(switchConfig, config);
const SwitchComponent = component(mergedConfig);

/**
 * Визуальный переключатель между двумя взаимоисключающими состояниями — вкл. и выкл.
 */
export const Switch = SwitchComponent;
```

2. Так же скопировал конфиг, и заменил там на свои значения

И после запуска сторибука в этом пакете получил ошибку, что-то типа "не могу обратиться к свойству, т.к. объект `switchClasses` - undefined". 

3. Тогда я прошёлся по всем твоим местами, где ты импортируешь  switchClasses из index.ts и заменил на точечный импорт:

```diff,
-import { switchTokens, switchClasses } from '../index';
+import { tokens, classes } from '../Switch.tokens';
```

После чего эта ошибка пропала, но значения токенов из конфига всё ещё не подгружаются, и я не смог понять почему.

Можешь пожалуйста сделать так, чтобы этот компонент заработал со styled-components?

2023-10-31 06:20 UTC, nikewht commented on packages/plasma-new-hope/src/components/Switch/_focused/base.ts
> +const addFocus = (outlineOffset: string, outlineSize: string, outlineRadius: string, outlineColor = '') => {
Привет, `packages/plasma-core/src/mixins/addFocus.ts` возвращает `styled-components` хотя мы используем `linaria` не получилось подружить

2023-10-31 06:22 UTC, nikewht commented on packages/plasma-new-hope/src/components/Switch/_disabled/base.ts
> +const { styledInputClass, styledContentWrapperClass, styledTriggerClass } = switchClasses;
Привет, хорошо

2023-10-31 09:32 UTC, nikewht commented on packages/plasma-new-hope/src/components/Switch/_disabled/base.ts
> +const { styledInputClass, styledContentWrapperClass, styledTriggerClass } = switchClasses;
@neretin-trike Можешь показать как у тебя конфиг выглядит? 
> Так же скопировал конфиг, и заменил там на свои значения

2023-11-01 06:28 UTC, nikewht commented on packages/plasma-new-hope/src/components/Switch/_disabled/base.ts
> +const { styledInputClass, styledContentWrapperClass, styledTriggerClass } = switchClasses;
@neretin-trike Вот так выглядит `Switch.config.js` после билда

```
import { css } from 'styled-components';
import { switchTokens } from '../../../../components/Switch';
export var config = {
  defaults: {
    view: 'default',
    size: 's'
  },
  variations: {
    size: {
      xs: /*#__PURE__*/css(["", ":var(--plasma-typo-body-s-font-family);", ":var(--plasma-typo-body-s-font-style);", ":var(--plasma-typo-body-s-font-weight);", ":var(--plasma-typo-body-s-letter-spacing);", ":var(--plasma-typo-body-s-line-height);", ":var(--plasma-typo-body-s-font-size);", ":1.85rem;", ":1.1rem;", ":0.975rem;", ":0.125rem;", ":0.975rem;"], switchTokens.fontFamily, switchTokens.fontStyle, switchTokens.fontWeight, switchTokens.fontWeight, switchTokens.lineHeight, switchTokens.fontSize, switchTokens.switchTriggerWidth, switchTokens.switchTriggerHeight, switchTokens.switchEllipseSize, switchTokens.switchEllipseBoxShadowSize, switchTokens.switchTriggerBorderRadius),
      s: /*#__PURE__*/css(["", ":var(--plasma-typo-body-m-font-family);", ":var(--plasma-typo-body-m-font-style);", ":var(--plasma-typo-body-m-font-weight);", ":var(--plasma-typo-body-m-letter-spacing);", ":var(--plasma-typo-body-m-line-height);", ":var(--plasma-typo-body-m-font-size);", ":2.55rem;", ":1.55rem;", ":1.3rem;", ":0.25rem;", ":0.975rem;"], switchTokens.fontFamily, switchTokens.fontStyle, switchTokens.fontWeight, switchTokens.fontWeight, switchTokens.lineHeight, switchTokens.fontSize, switchTokens.switchTriggerWidth, switchTokens.switchTriggerHeight, switchTokens.switchEllipseSize, switchTokens.switchEllipseBoxShadowSize, switchTokens.switchTriggerBorderRadius),
      m: /*#__PURE__*/css(["", ":var(--plasma-typo-body-m-font-family);", ":var(--plasma-typo-body-m-font-style);", ":var(--plasma-typo-body-m-font-weight);", ":var(--plasma-typo-body-m-letter-spacing);", ":var(--plasma-typo-body-m-line-height);", ":var(--plasma-typo-body-m-font-size);", ":2.75rem;", ":1.75rem;", ":1.5rem;", ":0.25rem;", ":0.975rem;"], switchTokens.fontFamily, switchTokens.fontStyle, switchTokens.fontWeight, switchTokens.fontWeight, switchTokens.lineHeight, switchTokens.fontSize, switchTokens.switchTriggerWidth, switchTokens.switchTriggerHeight, switchTokens.switchEllipseSize, switchTokens.switchEllipseBoxShadowSize, switchTokens.switchTriggerBorderRadius)
    },
    view: {
      "default": /*#__PURE__*/css(["", ":var(--switch-bg);", ":var(--switch-bg-hover);", ":var(--switch-active-bg);", ":var(--switch-active-bg-hover);", ":var(--switch-ellipse-bg);", ":0 0 var(", ") 0 var(--switch-ellipse-shadow-off);", ":0 0 var(", ") 0 var(--switch-ellipse-shadow-on);"], switchTokens.switchTriggerBackground, switchTokens.switchTriggerBackgroundHover, switchTokens.switchTriggerBackgroundChecked, switchTokens.switchTriggerBackgroundCheckedHover, switchTokens.switchEllipseBackground, switchTokens.switchEllipseBoxShadow, switchTokens.switchEllipseBoxShadowSize, switchTokens.switchEllipseBoxShadowChecked, switchTokens.switchEllipseBoxShadowSize)
    },
    disabled: {
      "true": /*#__PURE__*/css(["", ":0 0 var(", ") 0 var(--switch-ellipse-shadow-off-disabled);", ":var(--surface-solid-secondary);"], switchTokens.switchEllipseBoxShadowDisabled, switchTokens.switchEllipseBoxShadowSize, switchTokens.switchTriggerBackgroundDisabled)
    },
    focused: {
      "true": /*#__PURE__*/css(["", ":var(--switch-focus-color);"], switchTokens.switchFocusColor)
    }
  }
};
```

Вот так выглядит `Button.config.js`

```
import { css } from 'styled-components';
export var config = {
  defaults: {
    size: 'm',
    focused: 'true',
    view: 'secondary'
  },
  variations: {
    view: {
      primary: /*#__PURE__*/css(["--plasma-button-color:var(--on-dark-text-primary);--plasma-button-bg-color:var(--surface-accent);--plasma-button-bg-color-hover:#18a2ff;--plasma-button-bg-color-active:#045891;"]),
      secondary: /*#__PURE__*/css(["--plasma-button-color:var(--text-primary);--plasma-button-bg-color:var(--surface-transparent-secondary);--plasma-button-bg-color-hover:rgba(11,126,203,0.12);--plasma-button-bg-color-active:rgba(11,126,203,0.19);"]),
      clear: /*#__PURE__*/css(["--plasma-button-color:var(--text-accent);--plasma-button-bg-color:var(--surface-clear);--plasma-button-bg-color-hover:rgb(11,126,203,0.12);--plasma-button-bg-color-active:rgb(11,126,203,0.19);"]),
      negative: /*#__PURE__*/css(["--plasma-button-color:var(--on-dark-text-primary);--plasma-button-bg-color:var(--surface-negative);--plasma-button-bg-color-hover:#e65260;--plasma-button-bg-color-active:#c60014;"]),
      white: /*#__PURE__*/css(["--plasma-button-color:var(--text-primary);--plasma-button-bg-color:var(--background-primary);--plasma-button-bg-color-hover:#ffffff;--plasma-button-bg-color-active:#ebeaea;"])
    },
    size: {
      m: /*#__PURE__*/css(["--plasma-button-height:40px;--plasma-button-padding:20px;--plasma-button-radius:4px;--plasma-button-font-family:var(--plasma-typo-body-m-font-family);--plasma-button-font-size:var(--plasma-typo-body-m-font-size);--plasma-button-font-style:var(--plasma-typo-body-m-font-style);--plasma-button-font-weight:var(--plasma-typo-body-m-font-weight);--plasma-button-letter-spacing:var(--plasma-typo-body-m-letter-spacing);--plasma-button-line-height:var(--plasma-typo-body-m-line-height);"]),
      s: /*#__PURE__*/css(["--plasma-button-height:28px;--plasma-button-padding:12px;--plasma-button-radius:4px;--plasma-button-font-family:var(--plasma-typo-body-m-font-family);--plasma-button-font-size:var(--plasma-typo-body-m-font-size);--plasma-button-font-style:var(--plasma-typo-body-m-font-style);--plasma-button-font-weight:var(--plasma-typo-body-m-font-weight);--plasma-button-letter-spacing:var(--plasma-typo-body-m-letter-spacing);--plasma-button-line-height:var(--plasma-typo-body-m-line-height);"]),
      xs: /*#__PURE__*/css(["--plasma-button-height:20px;--plasma-button-padding:12px;--plasma-button-radius:4px;--plasma-button-font-family:var(--plasma-typo-body-s-font-family);--plasma-button-font-size:var(--plasma-typo-body-s-font-size);--plasma-button-font-style:var(--plasma-typo-body-s-font-style);--plasma-button-font-weight:var(--plasma-typo-body-s-font-weight);--plasma-button-letter-spacing:var(--plasma-typo-body-s-letter-spacing);--plasma-button-line-height:var(--plasma-typo-body-s-line-height);"])
    },
    disabled: {
      "true": /*#__PURE__*/css(["--plasma-button-disabled-opacity:0.4;"])
    },
    focused: {
      "true": /*#__PURE__*/css(["--plasma-button-focus-color:var(--surface-accent);"])
    },
    square: {},
    pin: {
      square: /*#__PURE__*/css([""]),
      circle: /*#__PURE__*/css(["border-radius:calc(var(--plasma-button-height) / 2);"])
    }
  }
};
```

Есть подозрение, что в этом проблема

2023-11-01 07:44 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Switch/_disabled/base.ts
> +const { styledInputClass, styledContentWrapperClass, styledTriggerClass } = switchClasses;
привет. Кажется, что не должно быть в этом проблемы, т.к. в соседней [прке](https://github.com/salute-developers/plasma/pull/817) у меня так же используются импорты токенов  и там вроде всё работает нормально 🤔  

Или ты про что-то другое?

2023-11-01 08:28 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/Switch/_disabled/base.ts
> +const { styledInputClass, styledContentWrapperClass, styledTriggerClass } = switchClasses;
Вот так выглядит конфиг для Switch.config.js в проекте plasma-web

```js
var _templateObject, _templateObject2, _templateObject3, _templateObject4;
function _taggedTemplateLiteral(strings, raw) { if (!raw) { raw = strings.slice(0); } return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }
import { css, switchTokens } from '@salutejs/plasma-new-hope/styled-components';
export var config = {
  defaults: {
    view: 'default',
    size: 'm'
  },
  variations: {
    size: {
      m: /*#__PURE__*/css(_templateObject || (_templateObject = /*#__PURE__*/_taggedTemplateLiteral(["\n                --plasma-switch-font-weight: 500;\n                ", ": arial;\n                ", ": normal;\n                ", ": 20px;\n                ", ": 19px;\n                ", ": 2.75rem;\n                ", ": 1.75rem;\n                ", ": 1.5rem;\n                ", ": 0.25rem;\n                ", ": 0.975rem;\n            "])), switchTokens.fontFamily, switchTokens.fontStyle, switchTokens.lineHeight, switchTokens.fontSize, switchTokens.switchTriggerWidth, switchTokens.switchTriggerHeight, switchTokens.switchEllipseSize, switchTokens.switchEllipseBoxShadowSize, switchTokens.switchTriggerBorderRadius)
    },
    view: {
      "default": /*#__PURE__*/css(_templateObject2 || (_templateObject2 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": green;\n                ", ": purple;\n                ", ": red;\n                ", ": blue;\n                ", ": gray;\n                ", ": 0 0 var(", ") 0 var(--switch-ellipse-shadow-off);\n                ", ": 0 0 var(", ") 0 var(--switch-ellipse-shadow-on);\n            "])), switchTokens.switchTriggerBackground, switchTokens.switchTriggerBackgroundHover, switchTokens.switchTriggerBackgroundChecked, switchTokens.switchTriggerBackgroundCheckedHover, switchTokens.switchEllipseBackground, switchTokens.switchEllipseBoxShadow, switchTokens.switchEllipseBoxShadowSize, switchTokens.switchEllipseBoxShadowChecked, switchTokens.switchEllipseBoxShadowSize)
    },
    disabled: {
      "true": /*#__PURE__*/css(_templateObject3 || (_templateObject3 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": 0 0 var(", ") 0 var(--switch-ellipse-shadow-off-disabled);\n                ", ": var(--surface-solid-secondary);\n            "])), switchTokens.switchEllipseBoxShadowDisabled, switchTokens.switchEllipseBoxShadowSize, switchTokens.switchTriggerBackgroundDisabled)
    },
    focused: {
      "true": /*#__PURE__*/css(_templateObject4 || (_templateObject4 = /*#__PURE__*/_taggedTemplateLiteral(["\n                ", ": var(--plasma-token-accent);\n            "])), switchTokens.switchFocusColor)
    }
  }
};
```

2023-11-09 13:33 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-816/

2023-11-09 15:26 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-816/

2023-11-09 17:06 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-816/

2023-11-09 17:17 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-816/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-816/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-816/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-816/new-hope-storybook/

2023-11-14 06:24 UTC, Salute-Eva commented
Theme Builder app deployed!
  
  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-816/

2023-11-14 06:32 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-816/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-816/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-816/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-816/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-816/asdk-storybook/

2023-11-20 13:06 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-816/

2023-11-20 13:19 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-816/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-816/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-816/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-816/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-816/asdk-storybook/

2023-11-21 08:54 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-816/

2023-11-21 09:00 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-816/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-816/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-816/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-816/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-816/asdk-storybook/

2023-11-22 07:50 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-816/

2023-11-22 07:58 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-816/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-816/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-816/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-816/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-816/asdk-storybook/

2023-11-22 21:32 UTC, Yeti-or requested changes

2023-11-22 21:32 UTC, Yeti-or commented on packages/plasma-new-hope/src/examples/themes/sds_engineer.module.css
> +    --switch-ellipse-shadow-off-disabled: rgba(193, 193, 193, 0.48);
я понял откуда ошибки в тестах, тут не должно быть новых токенов, что-то пошло не так они должны быть на уровне конфига, надо разобраться почему цветов нет в теме и что с этим делать

2023-12-14 04:12 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-816/

2023-12-14 04:16 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-816/

2023-12-14 04:29 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-816/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-816/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-816/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-816/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-816/asdk-storybook/

2023-12-14 04:53 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-816/

2023-12-14 05:00 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-816/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-816/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-816/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-816/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-816/asdk-storybook/

2023-12-14 05:08 UTC, Yeti-or approved these changes
@neretin-trike посмотри потом на разницу плиз: https://github.com/salute-developers/plasma/compare/23c53508a72bb2f98c82415889cb62c7d10879da..0e8c7e869ae3577dc62706072e052b66b6ad390b

2023-12-14 05:14 UTC, merged

2023-12-14 05:26 UTC, Salute-Eva commented
<!-- GITHUB_RELEASE COMMENT: released -->
🚀 This PR is included in version: @salutejs/plasma-asdk@0.14.0-dev.0, @salutejs/plasma-b2c@1.254.0-dev.0, @salutejs/plasma-new-hope@0.21.0-dev.0, @salutejs/plasma-temple-docs@0.191.0-dev.0, @salutejs/plasma-ui-docs@0.240.0-dev.0, @salutejs/plasma-web-docs@0.208.0-dev.0, @salutejs/plasma-web@1.254.0-dev.0, @salutejs/plasma-website@0.216.0-dev.0 🚀

2023-12-14 05:26 UTC, Salute-Eva commented
<!-- GITHUB_RELEASE COMMENT: released -->
🚀 This PR is included in version: @salutejs/plasma-asdk@0.14.0-dev.0, @salutejs/plasma-b2c@1.254.0-dev.0, @salutejs/plasma-new-hope@0.21.0-dev.0, @salutejs/plasma-temple-docs@0.191.0-dev.0, @salutejs/plasma-ui-docs@0.240.0-dev.0, @salutejs/plasma-web-docs@0.208.0-dev.0, @salutejs/plasma-web@1.254.0-dev.0, @salutejs/plasma-website@0.216.0-dev.0 🚀

2023-12-14 05:26 UTC, Salute-Eva commented
<!-- GITHUB_RELEASE COMMENT: released -->
🚀 This PR is included in version: @salutejs/plasma-asdk@0.14.0-dev.0, @salutejs/plasma-b2c@1.254.0-dev.0, @salutejs/plasma-new-hope@0.21.0-dev.0, @salutejs/plasma-temple-docs@0.191.0-dev.0, @salutejs/plasma-ui-docs@0.240.0-dev.0, @salutejs/plasma-web-docs@0.208.0-dev.0, @salutejs/plasma-web@1.254.0-dev.0, @salutejs/plasma-website@0.216.0-dev.0 🚀

2023-12-14 05:26 UTC, Salute-Eva commented
<!-- GITHUB_RELEASE COMMENT: released -->
🚀 This PR is included in version: @salutejs/plasma-asdk@0.14.0-dev.0, @salutejs/plasma-b2c@1.254.0-dev.0, @salutejs/plasma-new-hope@0.21.0-dev.0, @salutejs/plasma-temple-docs@0.191.0-dev.0, @salutejs/plasma-ui-docs@0.240.0-dev.0, @salutejs/plasma-web-docs@0.208.0-dev.0, @salutejs/plasma-web@1.254.0-dev.0, @salutejs/plasma-website@0.216.0-dev.0 🚀

2023-12-14 05:26 UTC, Salute-Eva commented
<!-- GITHUB_RELEASE COMMENT: released -->
🚀 This PR is included in version: @salutejs/plasma-asdk@0.14.0-dev.0, @salutejs/plasma-b2c@1.254.0-dev.0, @salutejs/plasma-new-hope@0.21.0-dev.0, @salutejs/plasma-temple-docs@0.191.0-dev.0, @salutejs/plasma-ui-docs@0.240.0-dev.0, @salutejs/plasma-web-docs@0.208.0-dev.0, @salutejs/plasma-web@1.254.0-dev.0, @salutejs/plasma-website@0.216.0-dev.0 🚀

2023-12-14 05:26 UTC, Salute-Eva commented
<!-- GITHUB_RELEASE COMMENT: released -->
🚀 This PR is included in version: @salutejs/plasma-asdk@0.14.0-dev.0, @salutejs/plasma-b2c@1.254.0-dev.0, @salutejs/plasma-new-hope@0.21.0-dev.0, @salutejs/plasma-temple-docs@0.191.0-dev.0, @salutejs/plasma-ui-docs@0.240.0-dev.0, @salutejs/plasma-web-docs@0.208.0-dev.0, @salutejs/plasma-web@1.254.0-dev.0, @salutejs/plasma-website@0.216.0-dev.0 🚀

2023-12-14 05:26 UTC, Salute-Eva commented
<!-- GITHUB_RELEASE COMMENT: released -->
🚀 This PR is included in version: @salutejs/plasma-asdk@0.14.0-dev.0, @salutejs/plasma-b2c@1.254.0-dev.0, @salutejs/plasma-new-hope@0.21.0-dev.0, @salutejs/plasma-temple-docs@0.191.0-dev.0, @salutejs/plasma-ui-docs@0.240.0-dev.0, @salutejs/plasma-web-docs@0.208.0-dev.0, @salutejs/plasma-web@1.254.0-dev.0, @salutejs/plasma-website@0.216.0-dev.0 🚀

2023-12-14 06:35 UTC, Salute-Eva commented
<!-- GITHUB_RELEASE COMMENT: released -->
🚀 This PR is included in version: @salutejs/plasma-asdk@0.14.0, @salutejs/plasma-b2c@1.254.0, @salutejs/plasma-hope@1.248.0, @salutejs/plasma-new-hope@0.21.0, @salutejs/plasma-temple-docs@0.191.0, @salutejs/plasma-tokens-native@1.17.0, @salutejs/plasma-ui-docs@0.240.0, @salutejs/plasma-web-docs@0.208.0, @salutejs/plasma-web@1.254.0, @salutejs/plasma-website@0.216.0 🚀