feat(plasma-ui): Performance addon for ProductCart
salute-developers/plasma pull request #83
Opened 2022-06-28 05:31 UTC by SeanSilke

Добавил https://storybook.js.org/addons/storybook-addon-performance
Написал Interactions для переключения кол-ва товаров в ProductCart

Зафиксировал результаты прогона аддона на сбилженном сторебуке.

2022-06-28 13:11 UTC, Yeti-or requested changes

2022-06-28 13:11 UTC, Yeti-or commented on packages/plasma-ui/src/components/ProductCard/ProductCard.stories.tsx
> +export const ProductCardPerformance: Story<Product_CardProps> = () => {
надо поправить чтобы линтер не ругался

2022-06-28 14:25 UTC, SeanSilke commented on packages/plasma-ui/src/components/ProductCard/ProductCard.stories.tsx
> +export const ProductCardPerformance: Story<Product_CardProps> = () => {
Да, поправлю. Это код я не менял, видимо его добавили раньше чем правило линтера.

2022-06-28 16:04 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-83/

2022-06-29 06:36 UTC, Yeti-or commented on packages/plasma-ui/src/components/ProductCard/ProductCard.stories.tsx
> +export const ProductCardPerformance: Story<Product_CardProps> = () => {
🤔 это оч странно, @neretin-trike не видел такого?

2022-06-30 06:48 UTC, SeanSilke commented
@Yeti-or  @neretin-trike ping

2022-06-30 06:59 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-83/

2022-06-30 07:13 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-83/
  ui storybook: http://plasma.sberdevices.ru/pr-83/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-83/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-83/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-83/temple-storybook/

2022-06-30 07:58 UTC, neretin-trike commented on packages/plasma-ui/src/components/ProductCard/performance-results/content-productcard--product-card-performance.json
> +    "copies": 1
а это точно должно в репе храниться?

2022-06-30 12:58 UTC, Salute-Eva commented
Demo canvas app deployed!
  
  http://plasma.sberdevices.ru/demo-canvas-app-pr-83/

2022-06-30 13:16 UTC, Salute-Eva commented
Documentation preview deployed!
  
  website: http://plasma.sberdevices.ru/pr-83/
  ui storybook: http://plasma.sberdevices.ru/pr-83/ui-storybook/
  web storybook: http://plasma.sberdevices.ru/pr-83/web-storybook/
  b2c storybook: http://plasma.sberdevices.ru/pr-83/b2c-storybook/
  temple storybook: http://plasma.sberdevices.ru/pr-83/temple-storybook/

2022-07-01 08:18 UTC, Yeti-or approved these changes

2022-07-01 08:20 UTC, Yeti-or commented
https://github.com/salute-developers/plasma/pull/80#issuecomment-1172076651

2022-07-01 12:02 UTC, merged