feat(plasma-new-hope): TextField
salute-developers/plasma pull request #949
Opened 2023-12-24 21:57 UTC by Yeti-or

### Заголовок вносимых изменений (например Dropdown или CI) [Heading 3]

Здесь описываем резюме вносимых изменений.

В формате списка, например

-   добавили новый api
-   изменили свойство size

Пример такого описания, см. ниже

```md
### Raised hand

-   добавлена новая иконка

<img width="48" alt="raisedHand" src="https://github.com/salute-developers/plasma/assets/46107741/212dbd44-1739-456e-83c3-e4362a2a10fd">
```

Примечания:

-   По возможности приложите скриншоты решенной проблемы в формате "до/после" или скриншоты нового компонента.
-   Обязательно укажите соответствующий **label**. Это нужно для определения правильной категории вносимых изменений.

### What/why changed

Более подробное описание решаемой проблемы.

### Labels

Это то, что **решает** ваш pull request. Label может быть только один.

Список доступных labels:

-   Components (задача добавить новый компонент)
-   Infra (поправили CI/CD, обновили зависимости, etc)
-   Tokens (поправили в plasma-tokens, theme-builder)
-   Icons (добавили новые иконки)
-   Docs (задачи связанные с документацией)

Все что не попадает в вышеперечисленное, попадет в категорию Misc.

### Прежде чем перевести в статус "requested a review" убедитесь

-   Добавлен номер issue (если есть);
-   Добавлены/обновлены **cypress тесты** если PR касается визуальной составляющей;

2023-12-24 22:00 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-949/

2023-12-24 22:11 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-949/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-949/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-949/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-949/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-949/asdk-storybook/

2024-01-19 07:18 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-949/

2024-02-20 22:17 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-949/

2024-02-20 22:36 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-949/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-949/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-949/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-949/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-949/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-949/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-949/caldera-online-storybook/

2024-02-23 14:12 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-949/

2024-02-23 14:13 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> +export interface TextFieldPropsBase {
надо чекнуть об наши договоренности

2024-02-23 14:17 UTC, Yeti-or commented on packages/plasma-new-hope/src/engines/common.tsx
> +                css && Array.isArray(css) ? res.push(...css) : res.push(css);
это чтобы можно было labelPlacement запихать в конфиг вместе с доопределением, по сути если бы у нас были пересечения можно было бы без этого; но в целом вроде полезно не могу пока понять


```
            inner: [
                labelPlacement_inner,
                css`
                    &.${labelPlacement_inner} {
                        ${tokens.labelOffset}: 0.3125rem;
                        ${tokens.placeholderColor}: var(--plasma-input-label-color, var(--plasma-input-placeholder-color, var(--plasma-colors-secondary)));
                        ${tokens.labelInnerFontFamily}: var(--plasma-input-label-font-family, var(--plasma-typo-body-xs-font-family));
```

2024-02-23 14:18 UTC, Yeti-or commented on packages/plasma-web/src/components/TextField/TextField.component-test.tsx
> +                {/* for backward comp  */}
чтобы все тесты на plasma-web прошли

2024-02-23 14:24 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-949/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-949/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-949/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-949/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-949/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-949/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-949/caldera-online-storybook/

2024-02-23 14:35 UTC, Yeti-or commented on packages/plasma-web/src/components/TextField/TextField.config.ts
> + *  --plasma-field-helper-text-font-* // caption
надо будет от них всех избавиться

2024-02-23 14:35 UTC, Yeti-or commented on cypress/snapshots/tokens-b2b/components/TextField/TextField.component-test.tsx/plasma-web TextField -- content with label.snap.png
для этого теста эталон не сохранили в репозитории =/

2024-02-23 14:35 UTC, Yeti-or commented on packages/plasma-b2c/src/components/TextField/TextField.config.ts
> +                ${tokens.backgroundColor}: rgba(255, 46, 67, .3);
очень странная верстка у нас в TextField B2c приходится хакать чтобы получить теже цвета

2024-02-23 14:35 UTC, Yeti-or commented on packages/plasma-b2c/src/components/TextField/TextField.tsx
> +    let _placeholder = placeholder;
отдельной задачей:
caption deprecated => use label

2024-02-23 14:35 UTC, Yeti-or commented on packages/plasma-b2c/src/components/TextField/TextField.tsx
> +    let _labelPlacement = view ? viewToLabelPlacement[view] : 'outer';
отдельной задачей:
view innerLabel deprecated => use labelPlacement

2024-02-23 14:35 UTC, Yeti-or commented on packages/plasma-b2c/src/components/TextField/TextField.tsx
> +    const _view = status ? statusToView[status] : 'default';
отдельной задачей:
status is deprecated  use view positive / warning / critical

2024-02-23 14:35 UTC, Yeti-or commented on packages/plasma-web/src/components/TextField/TextField.tsx
> +    const _view = status ? statusToView[status] : 'default';
зажеприкейтить:
status
animatedHint
caption

2024-02-23 14:36 UTC, Yeti-or commented on packages/plasma-b2c/src/components/TextField/TextField.tsx
> +    let _placeholder = placeholder;
А может и не отдельной 🤔

2024-02-27 23:10 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-949/

2024-02-27 23:31 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-949/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-949/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-949/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-949/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-949/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-949/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-949/caldera-online-storybook/

2024-02-28 13:45 UTC, neretin-trike commented
<img width="555" alt="Screenshot 2024-02-28 at 19 45 13" src="https://github.com/salute-developers/plasma/assets/26903236/5dc4f44d-9deb-44cd-a2ac-da5d5db11002">

а не нужно добавить токены для textfield-placeholder-color?

2024-02-28 13:46 UTC, kayman233 commented on packages/plasma-new-hope/src/components/TextField/TextField.tsx
> +const base = css``;
обычно мы переносим весь css в файл .styles.ts

2024-02-28 13:46 UTC, kayman233 commented on packages/plasma-new-hope/src/components/TextField/TextField.tsx
> +        labelPlacement: 'outer',
мы прям на уровне конфига дефолтное значение `labelPlacement` хотим?

2024-02-28 13:46 UTC, kayman233 commented on packages/plasma-new-hope/src/components/TextField/_size/base.ts
> +/* import { _tokenBorderWidth } from '../TextField.styles'; */
лишний коммент кажется

2024-02-28 14:14 UTC, neretin-trike commented on packages/plasma-b2c/src/components/TextField/TextField.config.ts
> + */
а это важно сохранить в этом конфиге?

2024-02-28 14:17 UTC, neretin-trike commented on packages/plasma-b2c/src/components/TextField/TextField.config.ts
> +                --label_inner-offset: 0.5625rem;
давай тогда положим это в публичный токен? Или в новом дизайне этого не понадобится?

2024-02-28 14:18 UTC, neretin-trike commented on packages/plasma-b2c/src/components/TextField/TextField.config.ts
> +        labelPlacement: {
а почему вариант, как сделано в TextArea мене подходит? Просто конфиг читать сложно + генерировать его потом автоматически тоже слабо полуится

2024-02-28 14:23 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/TextField/_size/base.ts
> +/* import { _tokenBorderWidth } from '../TextField.styles'; */
можно удалить?

2024-02-28 14:26 UTC, neretin-trike commented on packages/plasma-new-hope/src/components/TextField/_view/base.ts
> +        ${_tokenBorderColor}: var(--plasma_private-textfield-border-color-hack);
хм, странно 🤔  Вообще не должно быть такой ошибки, т.к. я часто таку конструкцию использовал

2024-02-28 14:27 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/TextField/TextField.tsx
> +        labelPlacement: 'outer',
пожалуй нет

2024-02-28 14:27 UTC, Yeti-or commented on packages/plasma-b2c/src/components/TextField/TextField.config.ts
> + */
чтобы нахер выпилить эти токены не забыть

2024-02-28 14:29 UTC, Yeti-or commented
> <img alt="Screenshot 2024-02-28 at 19 45 13" width="555" src="https://private-user-images.githubusercontent.com/26903236/308569646-5dc4f44d-9deb-44cd-a2ac-da5d5db11002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzA2ODMsIm5iZiI6MTcwOTEzMDM4MywicGF0aCI6Ii8yNjkwMzIzNi8zMDg1Njk2NDYtNWRjNGY0NGQtOWRlYi00NGNkLWEyYWMtZGE1ZDVkYjExMDAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE0MjYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiYzgwOWExZjVjZDMzYjQ3ODNiOTM5YWM3OWJmNDQxNjFkOGFlNGMyMTI2MTFmYTU4NDUwYjIxY2UwM2QxOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FILXSQyKi89hzs0oQiIEUboZX-U7exL3AKXT6adjH6s">
> а не нужно добавить токены для textfield-placeholder-color?

мне кажется это был косяк в placeholder

2024-02-28 14:34 UTC, neretin-trike commented on packages/plasma-web/src/components/TextField/TextField.tsx
> +    const _view = status ? statusToView[status] : 'default';
а мы эту обёртку сможем удалить, когда будем делать редизайн?

2024-02-28 15:41 UTC, Yeti-or commented on packages/plasma-web/src/components/TextField/TextField.tsx
> +    const _view = status ? statusToView[status] : 'default';
нет, только в plasma-2.0

2024-02-28 16:35 UTC, neretin-trike approved these changes

2024-02-28 17:56 UTC, shuga2704 requested changes

2024-02-28 17:56 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/TextField/TextField.tsx
> +                if (event.keyCode === 13 && onSearch) {
`if (event.key === 'Enter' && onSearch) {`
Думаю так проще понять что за if

2024-02-28 17:56 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/TextField/TextField.tsx
> +        const handleChange = useCallback<ChangeEventHandler<HTMLInputElement>>(
Зачем useCallback?

2024-02-28 17:56 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/TextField/_label-placement/inner.ts
> +        height: var(--plasma-textfield-height);
Почему не `height: var(${tokens.height});`?

2024-02-28 17:56 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/TextField/_size/base.ts
> +import { Input, InputLabelWrapper, InputWrapper, Label, LeftHelper, _tokenBorderWidth } from '../TextField.styles';
_tokenBorderWidth можно удалить

2024-02-28 17:56 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/TextField/_size/base.ts
> +--plasma_private-textfield-border-width: var(${tokens.borderWidth});
Зачем это выносить в переменную, если можно сразу `tokens.borderWidth` вставить в box-shadow в TextField.styles.ts:26?

2024-02-28 17:56 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/TextField/TextField.styles.ts
> +export const _tokenBorderColor = '--plasma_private-textfield-border-color';
Я не нашел `--plasma_private-textfield-border-color` в рамках компонента TextField, разве он придет извне?

2024-02-28 17:56 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/TextField/_view/base.ts
> +        ${_tokenBorderColor}: var(--plasma_private-textfield-border-color-hack);
Я минут 10 сидел пытался понять смысл такой записи, пока не увидел ваши сообщения)) 
пс. в вебшторме все ок

2024-02-28 17:56 UTC, shuga2704 commented on packages/plasma-web/src/components/TextField/TextField.tsx
> +        view,
Неиспользуемый проп

2024-02-28 17:56 UTC, shuga2704 commented on packages/plasma-b2c/src/components/TextField/TextField.stories.tsx
>              status={status || undefined}
Не очень понял смысл этого `undefined`?

2024-02-29 07:58 UTC, Salute-Eva commented
Theme Builder app deployed!

  http://plasma.sberdevices.ru/pr/plasma-theme-builder-pr-949/

2024-02-29 08:12 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> +    contentRight?: React.ReactElement;
Может лучше расширим до React.ReactNode?

2024-02-29 08:13 UTC, Salute-Eva commented
Documentation preview deployed!

  website: http://plasma.sberdevices.ru/pr/pr-949/
b2c storybook: http://plasma.sberdevices.ru/pr/pr-949/b2c-storybook/
web storybook: http://plasma.sberdevices.ru/pr/pr-949/web-storybook/
new-hope storybook: http://plasma.sberdevices.ru/pr/pr-949/new-hope-storybook/
asdk storybook: http://plasma.sberdevices.ru/pr/pr-949/asdk-storybook/
caldera storybook: http://plasma.sberdevices.ru/pr/pr-949/caldera-storybook/
caldera-online storybook: http://plasma.sberdevices.ru/pr/pr-949/caldera-online-storybook/
sdds-serv storybook: http://plasma.sberdevices.ru/pr/pr-949/sdds-serv-storybook/

2024-02-29 08:16 UTC, Yeti-or commented on cypress/snapshots/b2c/components/TextField/TextFieldBase.component-test.tsx/plasma-core TextField -- success, warning, error.snap.png
да мне кажется это корректным поведением

2024-02-29 08:16 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/TextField/TextField.styles.ts
> +export const LeftHelper = styled.div``;
чтобы использовать это в верстке вариантов _size / _view ...

2024-02-29 08:17 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/TextField/TextField.tokens.ts
кажется это не важно с точки зрения написания,
но я ориенторовался на сущности, условно часть Textfiled или его вариация

2024-02-29 08:18 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/TextField/TextField.tsx
> +                if (event.keyCode === 13 && onSearch) {
поправил

2024-02-29 08:18 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/TextField/TextField.tsx
> +        const handleChange = useCallback<ChangeEventHandler<HTMLInputElement>>(
так было в старом textField – убрал

2024-02-29 08:18 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/TextField/_size/base.ts
> +import { Input, InputLabelWrapper, InputWrapper, Label, LeftHelper, _tokenBorderWidth } from '../TextField.styles';
убрал

2024-02-29 08:18 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/TextField/TextField.styles.ts
> +export const _tokenBorderColor = '--plasma_private-textfield-border-color';
нет он будет выставлен внутри _view

2024-02-29 08:18 UTC, Yeti-or commented on packages/plasma-web/src/components/TextField/TextField.tsx
> +        view,
убрал

2024-02-29 08:19 UTC, Yeti-or commented on packages/plasma-b2c/src/components/TextField/TextField.stories.tsx
>              status={status || undefined}
https://github.com/salute-developers/plasma/issues/961

2024-02-29 08:20 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/TextField/_size/base.ts
> +--plasma_private-textfield-border-width: var(${tokens.borderWidth});
Тут я имел ввиду вынос `tokens.borderWidth` вместо var(--plasma_private-textfield-border-width)

2024-02-29 08:21 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> +    contentRight?: React.ReactElement;
чтобы можно было строки передавать ?

2024-02-29 08:24 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/TextField/TextField.tsx
> +const base = css``;
ну мне кажется надо поправить engine так чтобы base  мог быть пустым

2024-02-29 08:26 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/TextField/TextField.tsx
> +const base = css``;
https://github.com/salute-developers/plasma/issues/1076

2024-02-29 08:31 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/TextField/_size/base.ts
> +--plasma_private-textfield-border-width: var(${tokens.borderWidth});
ну я и говорю:
`--plasma_private-textfield-border-width` задается на уровне textField.styles.ts , где лежит вся состовляющая TextField

внутри вариации использются классы из styles:

```css
${Input} {
 color: ...;
}
```

и выставляются приватные переменные:
```css
# _view/size.css

--plasma_private-textfield-border-width: 14px;

```

То есть вариации используют для стилизации только то что прописано в styles.ts
такое вот разграничение ответсвенности

2024-02-29 08:31 UTC, Yeti-or commented on packages/plasma-b2c/src/components/TextField/TextField.config.ts
> +        labelPlacement: {
подумаю об этом потом

2024-02-29 08:32 UTC, Yeti-or commented on packages/plasma-b2c/src/components/TextField/TextField.config.ts
> +                --label_inner-offset: 0.5625rem;
подумаю об этом потом

2024-02-29 08:32 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/TextField/TextField.tsx
> +        labelPlacement: 'outer',
Починил

2024-02-29 08:34 UTC, shuga2704 commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> +    contentRight?: React.ReactElement;
Ага, если конечно это не противоречит тз

2024-02-29 08:38 UTC, shuga2704 approved these changes

2024-02-29 08:38 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> +    contentRight?: React.ReactElement;
мы же сами себе тз

2024-02-29 08:39 UTC, Yeti-or commented on packages/plasma-new-hope/src/components/TextField/TextField.types.ts
> +    contentRight?: React.ReactElement;
я поменяю типы в след задаче

2024-02-29 09:58 UTC, merged